### ISSUE TITLE
How to resume playback after manipulating the timeline when in STATE_ENDED?

### ISSUE THREAD

**Issue by aljohnston112** [androidx/media#1018]
I am wanting to add a media item to ExoPlayer's timeline after the timeline is finished. I tried to do this when playback state is STATE_ENDED, but the commands do not appear to do anything.

Here is some code illustrating what I am trying to do. The added media item being the current media item is temporary while I try to figure this out. Note that ```playerHolder.getPlayer()``` returns a ForwardingPlayer that has no overrides and is wrapped around an ExoPlayer instance.
```kt
        override fun onPlaybackStateChanged(playbackState: Int) {
            super.onPlaybackStateChanged(playbackState)
            if (playbackState == STATE_ENDED) {
                playerHolder.getPlayer().addMediaItem(
                    playerHolder.getPlayer().currentMediaItem!!
                )
                playerHolder.getPlayer().play()
            }
        }
```

I have messed around a bit and notice it will work if I replace the playlist entirely and send the play command.

Also, I notice that this code does nothing at all
```kt
        override fun onPlaybackStateChanged(playbackState: Int) {
            super.onPlaybackStateChanged(playbackState)
            if (playbackState == STATE_ENDED) {
                playerHolder.getPlayer().play()
            }
        }
```
but if the user sends a play command through a MediaController after a timeline is over, then ExoPlayer will start playing the timeline again.

I am wondering why the two snippets above do not work, but something like below, where the playlist is replaced, does work.

```kt
        override fun onPlaybackStateChanged(playbackState: Int) {
            super.onPlaybackStateChanged(playbackState)
            if (playbackState == STATE_ENDED) {
                playerHolder.getPlayer().setMediaItems(
                    listOf(playerHolder.getPlayer().currentMediaItem!!)
                )
                playerHolder.getPlayer().play()
            }
        }
```

**Comment by marcbaechinger** [comment]
When in `STATE_ENDED` you need to seek to get out of `STATE_ENDED`. Like `player.seekTo(C.TIME_UNSET)` would be sufficient to get to the start of the last item and make playback resume.

I think this also applies to your case when adding an item.
What happens when you do

```
player.addMediaItem(itemToAppend)
player.seekTo(player.getMediaItemCount() - 1, C.TIME_UNSET)
```

?

> Also, I notice that this code does nothing at all: `playerHolder.getPlayer().play()`

`player.getPlayWhenReady()` only changes when requested by the user. When in `STATE_ENDED` the player is still ready for playing and resumes after a seek without `play()` being called again. Calling `play` again is redundant and hence a no-op.

> it will work if I replace the playlist entirely and send the play command.

When calling `player.setMediaItems(items)` this is delegated to `setMediaItems(List<MediaItem> mediaItems, /* resetPosition= */ true)` which implicitly seeks the default position of the first media items that is set.

**Comment by aljohnston112** [comment]
You can ignore that last question. I found a workaround using onPlaybackStateChanged and the onClickListener of the UI's play/pause button.
