### ISSUE TITLE
Sometimes controller.currentPositon is bigger than controller.duration when play end.

### ISSUE THREAD

**Issue by XuQK** [androidx/media#105]
### Media3 Version

1.0.0-beta01

### Devices that reproduce the issue

Samsung galaxy note 10 5G running Android 11

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. Just play the audio attached
2. Open it, drag the seekbar to where a few second left
3. Wait it play end
4. Print the `MediaController.getDuration` and `MediaController.getCurrentPosition`, you will find that the latter is greater than the former, 900ms.
5. if it does not appear, repeat.Usually two to three times.

### Expected result

The difference should not exceed 100ms I think.

### Actual result

The difference is close to a second.

### Media

[Help (Sunset Rollercoaster 落日飛車 Remake) - 혁오 (HYUKOH) _ 落日飛車.mp3.zip](https://github.com/androidx/media/files/9038436/Help.Sunset.Rollercoaster.Remake.-.HYUKOH._.mp3.zip)

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
I can repro this with the attached media in the demo app. The duration is 4.12 and the timebar goes to 4:13 when the songs play ends.

**Comment by tonihei** [comment]
Seeking in MP3 files is known to be inaccurate due to limitations in the format. See https://github.com/google/ExoPlayer/issues/7767#issuecomment-677760688 for more explanations. You can work around this by setting `Mp3Extractor#FLAG_ENABLE_INDEX_SEEKING` in `DefaultExtractorsFactory.setMp3ExtractorFlags`. But note that this setting should only be used for relatively short MP3 files like this one.
