### ISSUE TITLE
[media3-1.1.0] Codec, Bitrate and version info @ Playing audio/mpeg

### ISSUE THREAD

**Issue by MrBoe** [androidx/media#1081]
Hello,

By analyzing the Track.Group format output of our media3 implementation, I recognized that not every media content
contains the information about used codec and its values. 

**Especially the output for audio/mped files does not contain codec info and bitrate and the used codec version.** 

I also compared the format information to the output of the official media3 demo app while using different formats
and noticed that in general there are always some format fields missing depending on played format.

Output in Player.Listener onTracksChanged (mp3 file):
![grafik](https://github.com/androidx/media/assets/3763146/b47c1621-1152-4adf-a4e9-3c67fc0af417)

Output for same file in further processing CodecConfig/CCodec:
![grafik](https://github.com/androidx/media/assets/3763146/9774a214-f406-459f-a2d2-4c64bae2e487)

1.) Is this known behavior, since in some cases the audio playback of "MediaCodec" is operating asynchronously?
2.) Is there any general rule/info for which media formats the bitrate can be fetched within the Tracks.Group getTrackFormat?
3.) I also saw that the debug log of media3 internal "CCodec" has at least more information about bitrate,
   which is not available in the getFormat/getTrackFormat containing information. Is there any way to obtain
   the missing information manually within the media3 framework without customization of the framework itself?

Kind regards

**Comment by icbaker** [comment]
ExoPlayer generally only populates fields like codec and bitrate etc on `Format` if they're likely to be useful for track selection decisions. In the case of progressive containers, there's usually only a single track of each type (especially in an MP3 file), so there's need for ExoPlayer to populate these fields. To add some more detail to your specific questions:



> 1.) Is this known behavior, since in some cases the audio playback of "MediaCodec" is operating asynchronously?

This is not related to MediaCodec's operating mode. ExoPlayer populates the `Format` object from information it can parse from the container file (and/or playlist/manifest for adaptive content) - this happens before samples are passed to `MediaCodec`.

> 2.) Is there any general rule/info for which media formats the bitrate can be fetched within the Tracks.Group getTrackFormat?

As above, these fields are generally only populated where they might be neede for track selection decisions - so usually this is only for adaptive content (DASH and HLS)

> 3.) I also saw that the debug log of media3 internal "CCodec" has at least more information about bitrate,
> which is not available in the getFormat/getTrackFormat containing information. Is there any way to obtain
> the missing information manually within the media3 framework without customization of the framework itself?

ExoPlayer doesn't inspect the actual encoded media sample bytes - it unwraps the container and passes the encoded samples to a decoder (usually via MediaCodec). In the case of MP3, especially for variable bitrate files (VBR), I'm not sure there's an explicit bitrate field in the container metadata - I think each MP3 frame just has a different bitrate (so there's not really a convenient value for ExoPlayer to read).

---

It might help if you could outline why you need this info and what you want to do with it?

**Comment by icbaker** [comment]
Sorry for the robot's comment, something meant it didn't see your reply - we're not waiting for additional info.

**Comment by icbaker** [comment]
I have a change in review which will plumb MP3 bitrate into the `Format.averageBitrate` field. I'm not sure what you're referring to by 'codec' and 'version info' in the issue title.

**Comment by Tolriq** [comment]
@icbaker this was discussed also on ExoPlayer back then but there's more than just mp3 missing data.

[0656b3688a78a1374cb05bb6e500fd8b7bd2419d.patch](https://github.com/androidx/media/files/14756984/0656b3688a78a1374cb05bb6e500fd8b7bd2419d.patch)

Now using ffmpeg to get the data, but flac bitrate and bit per sample, alac bitrate would be nice too. Was using the rough patch attached before.

**Comment by MrBoe** [comment]
> I have a change in review which will plumb MP3 bitrate into the `Format.averageBitrate` field. I'm not sure what you're referring to by 'codec' and 'version info' in the issue title.

Thank you for caring! For the Mp3Extractor it's for sure a good thing to have this info available .
But our request is more kind of having general information of the used codec, container format and the bitrate,
as much as it is possible regardless of the used extractor. 

At the current state of the project we also aren't using the external decoders like ffmpeg. 
So it would be appreciated to have the _Format_ fields available for the internal decoder.

Thx in advance

**Comment by icbaker** [comment]
Each piece of data needs to be parsed from each container, so there isn't really a 'high-level' way to automatically provide the information you're asking for from every container.

> So it would be appreciated to have the _Format_ fields available for the internal decoder.

To clarify something here: `Format` is created during extraction, before any samples have been decoded, so nothing in it can be determined by the decoder implementation. The decoder used for a particular playback can be determined by listening to:
* [`AnalyticsListener.onAudioDecoderInitialized`](https://developer.android.com/reference/androidx/media3/exoplayer/analytics/AnalyticsListener#onAudioDecoderInitialized(androidx.media3.exoplayer.analytics.AnalyticsListener.EventTime,java.lang.String,long,long))
* [`AnalyticsListener.onVideoDecoderInitialized`](https://developer.android.com/reference/androidx/media3/exoplayer/analytics/AnalyticsListener#onVideoDecoderInitialized(androidx.media3.exoplayer.analytics.AnalyticsListener.EventTime,java.lang.String,long,long))

I'm going to close this issue, because the title and original comment are specifically about MP3 and that case is now handled by the commits linked above. If you have specific other similar combinations of data + container then I'd encourage you to file new issue(s), so each can be reasonably scoped. You may also want to consider sending PRs for the data you're interested in.
