### ISSUE TITLE
OverlayShaderProgram ignores "enableColorTransfers" and always converts overlay colors

### ISSUE THREAD

**Issue by kleiren** [androidx/media#1095]
### Version

Media3 pre-release (alpha, beta or RC not in this list)

### More version details

1.3.0-beta01

### Devices that reproduce the issue

All

### Reproducible in the demo app?

Not tested

### Reproduction steps

Create a composition with a video with an OverlayEffect with a simple bitmap applied.
Disable color transfer in the transformer.

```
 val videoProcessor = DefaultVideoFrameProcessor.Factory.Builder().setEnableColorTransfers(false).build()
 return Transformer.Builder(context).setVideoFrameProcessorFactory(videoProcessor)[...]
```

### Expected result

The colors of the bitmap used as an overlay are not changed in the final result

### Actual result

If the transformer has "setEnableColorTransfer(false)" the bitmap's colors on the video result are changed from the input.

This seems to be because OverlayShaderProgram.java has the shader defined inside, always applying "applyEotf()" to the texture's colors. This shader should probably listen to the "enableColorTransfers" variable to not apply these transformations. Also, this is not easy to change from an app, as OverlayShaderProgram depends on multiple protected classes. I arrived to this conclusion after this issue I was having previously: https://github.com/androidx/media/issues/1080

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tof-tof** [comment]
The DefaultVideoFrameProcessorFactory setting you mention only controls the colors of the input's to the VideoFrameProcessor, i.e. the input frames from the EditedMediaItem, not the input to individual effects or there corresponding shader programs. 

The OverlayEffect requires the input (video) frame to be in optical (aka linear) input colors so it can blend the overlay into the frame a linear color space, so since bitmaps are stored in electrical colors, we always to convert them to linear.

In future, we will support color management in the DefaultVideoFrameProcessor, which will allow shader programs to announce what input colors they expect and what output colors they produce so that the DefaultVideoFrameProcessor can automatically insert the needed color transfers between shader programs so that the input frame is in the correct color space when it's inputted into the shader program. Until that is implemented, it's up to the user to ensure that the effect's required color space and input frames color space is compatible.

**Comment by tof-tof** [comment]
The DefaultVideoFrameProcessorFactory setting you mention only controls the colors of the input's to the VideoFrameProcessor, i.e. the input frames from the EditedMediaItem, not the input to individual effects or there corresponding shader programs. 

The OverlayEffect requires the input (video) frame to be in optical (aka linear) input colors so it can blend the overlay into the frame a linear color space, so since bitmaps are stored in electrical colors, we always to convert them to linear.

In future, we will support color management in the DefaultVideoFrameProcessor, which will allow shader programs to announce what input colors they expect and what output colors they produce so that the DefaultVideoFrameProcessor can automatically insert the needed color transfers between shader programs so that the input frame is in the correct color space when it's inputted into the shader program. Until that is implemented, it's up to the user to ensure that the effect's required color space and input frames color space is compatible.
