### ISSUE TITLE
TTML subtitles - Opacity not compliant with TTML specification

### ISSUE THREAD

**Issue by Xlcghs** [androidx/media#1127]
In the TTML specification (https://www.w3.org/TR/ttml2/#style-value-border-color), section 10.3.1 , it is stated that "An <alpha> expression is used to express an opacity value, where 0 means fully transparent and 1 means fully opaque." However, Media 3 uses values between 0 and 255 for alpha values. How can I make Media3 support alpha values in the form of a real number?

Source code Media 3 v1.2 :

 /**
   * Parses a TTML color expression.
   *
   * @param colorExpression The color expression.
   * @return The parsed ARGB color.
   */
  @ColorInt
  public static int parseTtmlColor(String colorExpression) {
    return parseColorInternal(colorExpression, false);
  }

**Comment by icbaker** [comment]
You've linked to https://www.w3.org/TR/ttml2/#style-value-border-color which resolves to 10.3.5, but you reference section 10.3.1 in the text.

10.3.1 defines how `<alpha>` is used in the spec, which seems to **only** be referenced from [`tts:opacity`](https://www.w3.org/TR/ttml2/#style-attribute-opacity). ExoPlayer does not currently support this `tts:opacity` attribute.

The media3 source code you've linked is intended to parse a TTML `<color>` string as [defined in 10.3.9](https://www.w3.org/TR/ttml2/#style-value-color) (i.e. where the alpha component is between 0 and 255):
> A \<color\> expression is used to specify a named color, exact RGB color triple, or exact RGBA color tuple, where the alpha component, if expressed, is maximum (255) at 100% opacity and minimum (0) at 0% opacity, and where the applicable color space is defined by [[SRGB]](https://www.w3.org/TR/ttml2/#srgb).

I believe that all call-sites of `parseTtmlColor` are passing a `<color>` string - if you don't believe that's the case, please link to the specific call-site that you believe to be causing a problem. Please also provide a TTML file that you believe is not parsed correctly by ExoPlayer.

**Comment by Xlcghs** [comment]
Actually, shakaPlayer accepts float alpha values in rgba, unlike Exo which only accepts integers between 0 and 255 to achieve the desired transparency. Upon analyzing the two versions of the ttml standard (v1 vs v2), 
**it was found that in ttml v1:**
```
<color>
  : "#" rrggbb  | "#" rrggbbaa  | "rgb(" r-value "," g-value "," b-value ")"  | "rgba(" r-value "," g-value "," b-value "," a-value ")"  | <namedColor>

rrggbb
: <hexDigit>{6}

rrggbbaa
: <hexDigit>{8}

r-value | g-value | b-value | a-value
: component-value

component-value
: non-negative-integer // valid range: [0,255]

non-negative-integer
: <digit>+
```
**In ttml v2:** 

```
<alpha>
  : float
 
```

So, my question is: does Exo support only  the ttml v1 version? If not, is it possible to force it to support float alpha values without changing the Exo library? Or do I have to use exact colors instead of using the rgba format?

Thank you very much for your help.

**Comment by icbaker** [comment]
My reading of the TTML v1 spec suggests that it also expects `rgba(r, g, b, a)` where `a` is between 0 and 255. From [section 8.3.2 that defines `<color>`](https://www.w3.org/TR/ttml1/#style-value-color):
> A <color> expression is used to specify a named color, exact RGB color triple, or exact RGBA color tuple, where the alpha component, if expressed, is maximum (255) at 100% opacity and minimum (0) at 0% opacity, and where the applicable color space is defined by [[SRGB]](https://www.w3.org/TR/ttml1/#srgb).

And the [`tts:color` attribute](https://www.w3.org/TR/ttml1/#style-attribute-color) is type `<color>`. ExoPlayer's logic (of expecting an alpha value between 0 and 255 in an `rgba(r, g, b, a)` expression) seems to be compatible with both TTML v1 and v2.

---



> **In ttml v2:**
> 
> ```
> <alpha>
>   : float
>  
> ```

I'm not sure which part of the TTML v2 spec you're quoting here, but if it's 10.3.1, then I already addressed above in https://github.com/androidx/media/issues/1127#issuecomment-1966720279 that this is not relevant for the interpretation the `tts:color` and `tts:backgroundColor` attributes (since these are of type `<color>` not `<alpha>`).

---

Both TTML specs seem to be very clear to me. Shaka player is free to treat rgba(255, 0, 255, 1.0) as 'fully opaque', but this is not the expected behaviour from the spec, and it seems very risky for content producers to rely on this undefined behaviour (since it is unlikely to work consistently across players, as you're finding). It would be preferable for the content to obey the spec (that's sort of why the spec exists :)).

----

> If not, is it possible to force it to support float alpha values without changing the Exo library?

You can either provide a custom `SubtitleParser` implementation for TTML (likely inspired by forking `TtmlParser`), and configure the player with your custom `SubtitleParser.Factory` to construct it. Or you can fork the library, [depend on it locally](https://github.com/androidx/media/blob/release/README.md#locally), and change just the `parseTtmlColor` line you highlighted above in your original comment.

**Comment by Xlcghs** [comment]
Thank you for your feedback
