### ISSUE TITLE
Transformer - Is it possible to set effects for a specific time frame?

### ISSUE THREAD

**Issue by calren** [androidx/media#1282]
Using Transformer APIs to added effects to a video, if I wanted to add effects for only a specific time frame of a video, what's the best way to do that?

For example, given this code snippet to apply a speed change to a video, is it possible to only apply the speed change to the last second of the video?
```
EditedMediaItem.Builder(MediaItem.fromUri(videoUri))
    .setEffects(
        Effects(
            listOf(),
            listOf(
                SpeedChangeEffect(0.5f) // How can this only be applied to the last second of the video?
            ),
        ),
    ).
    .build()
```

**Comment by tof-tof** [comment]
The general solution will be to use the [`TimestampWrapper`](). This wraps the effect, allowing ensuring the effect is only applied in the time frame you specify.

For speed changes, we've recently [added an API](https://github.com/androidx/media/blob/b6d3cb4a7f3a1c556bba79f63f29b3e6b136b1c0/libraries/effect/src/main/java/androidx/media3/effect/SpeedChangeEffect.java#L62) (in the next release which is currently in alpha) so that you can provide a [`SpeedProvider`](https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/common/src/main/java/androidx/media3/common/audio/SpeedProvider.java#L23) which allows you to specify segments of the MediaItem to be adjusted.

**Comment by calren** [comment]
got it, thanks @tof-tof !
