### ISSUE TITLE
Exoplayer EOFException for progressive streams with moov atom at the end of the mp4 file

### ISSUE THREAD

**Issue by MBakhshi96** [androidx/media#1301]
### Version

Media3 1.0.2 / ExoPlayer 2.18.7

### Devices that reproduce the issue

Not device specific

### Reproducible in the demo app?

Not tested

### Reproduction steps

Stream the media uploaded to [this link](https://filebin.net/409s2y85ydbti2p5) (The direct link to the media item gets expired after some time so you need to create a link by yourself)

### Expected result

The media should play successfully. The mp4 file has moov atom at the end of the file but plays successfully on all players (even on Chrome and Firefox native players). Also when the file is downloaded and played from the local storage, it plays without any problem.

### Actual result

There is a source error with EOFException:
```
Playback error
    com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:644)
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:620)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
    Caused by: java.io.EOFException
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFromUpstream(DefaultExtractorInput.java:296)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:80)
        at com.google.android.exoplayer2.extractor.DefaultExtractorInput.readFully(DefaultExtractorInput.java:88)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.readAtomPayload(Mp4Extractor.java:441)
        at com.google.android.exoplayer2.extractor.mp4.Mp4Extractor.read(Mp4Extractor.java:254)
        at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1039)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

### Media

https://filebin.net/409s2y85ydbti2p5

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
I'm not able to reproduce the issue using the [demo app](https://developer.android.com/media/media3/exoplayer/demo-application) built at 1.0.2 using a Pixel 7a running Android 14 (UQ1A.240205.002).

----

> ### Reproducible in the demo app?
> Not tested

Please can you test this in order to give more information about whether it only reproduces for you in your app or also in the demo app.

**Comment by MBakhshi96** [comment]
The problem strangely seems to vanish when I download the original media and upload it somewhere else. I will send the original link to android-media-github@google.com since I can't post it publicly. The media plays with no problem on all players (browser native, etc.)

**Comment by icbaker** [comment]
I can reproduce the issue using the link provided over email.

This is happening when we re-open the HTTP connection to read the `moov` atom directly (this is more efficient than reading all the bytes of the file to get to the `moov` atom):

https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/extractor/src/main/java/androidx/media3/extractor/mp4/Mp4Extractor.java#L515-L523

I added some additional logging to show this (`1835295092` is `mdat`):

```
Seek required to 439807830 after reading 1835295092 atom
open() returned: 1906924
response headers:
{accept-ranges=[bytes], Connection=[keep-alive], content-disposition=[inline], content-range=[bytes 439807830-441714753/441714754], Content-Type=[video/mp4], Date=[Mon, 22 Apr 2024 13:34:42 GMT], Server=[nginx/1.25.0], Transfer-Encoding=[chunked]}
internalError [eventTime=1.75, mediaPos=0.00, window=0, period=0, loadError
  java.io.EOFException: length=265696 ,bytesAlreadyRead=1589, bytesRead=-1
```

It seems the HTTP server is not behaving in line with its response headers. When re-opening starting the read at `439807830` it includes the `content-range=[bytes 439807830-441714753/441714754]` header, which means this connection can be used to read bytes from `439807830` to `441714753` (which is `1906923` bytes). We then receive `-1` when trying to read beyond `1589` bytes. This indicates the server is refusing to provide the bytes it promised in the `content-range` response header. I suggest you raise this issue with the maintainers of this server.

I suspect (just a guess) that other players don't encounter this issue because they take the less efficient approach of reading the whole file to reach the `moov` atom at the end instead.

**Comment by MBakhshi96** [comment]
You are right. The problem is related to the web server not properly returning last bytes of the file, which includes the metadata. Specifically, the `stco` atom is missing in the response, causing Exoplayer to block playback with an `EOFException`. It seems that other players do not care much about the missing metadata and proceed with playback. Perhaps in the future, Exoplayer could provide developers with the option to decide whether to start playback of media with missing metadata and do not throw an exception (apparently, some functionalities like seeking may not work properly).

**Comment by icbaker** [comment]
> Specifically, the `stco` atom is missing in the response, causing Exoplayer to block playback with an `EOFException`.

I'm not sure I completely agree with this summary - I think ExoPlayer fails with `EOFException` simplly because the file promised N bytes and then failed to deliver N bytes - it's less about the specific data that was withheld by the server.

ExoPlayer generally expects media and its serving infrastructure to be well-formed and spec compliant. It's not feasible for us to workaround all the possible spec violations observed in the wild, and we generally feel the correct way to resolve issues like this to comply with the relevant spec instead of working around it. In this case, I would suggest you investigate the server implementation in more detail, I'm afraid we don't plan to change ExoPlayer's behaviour.
