### ISSUE TITLE
Document the fact that `desugar_jdk_libs` is required for media3 to work on old API levels

### ISSUE THREAD

**Issue by MGaetan89** [androidx/media#1312]
Since https://github.com/androidx/media/commit/889f435a49eff9dc9fb516bd0bee85c1ca7a3f7d, Media3 uses the `desugar_jdk_libs` library to use newer Java APIs on older API levels.
For example in `Format`:
https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/common/src/main/java/androidx/media3/common/Format.java#L982

This means that applications/libraries using Media3 also need to integrate `desugar_jdk_libs`. However, this is not documented in the Java 8 support section of the Readme:
https://github.com/androidx/media/tree/release?tab=readme-ov-file#2-turn-on-java-8-support

Would it be possible to add a note about it?

**Comment by MGaetan89** [comment]
By digging a bit more into this, here are all the newer API usages I could find in production code:
- `List.stream()`
https://github.com/androidx/media/blob/43d1fa933c8486f54d63079f539ceeddd68acbc8/libraries/common/src/main/java/androidx/media3/common/Format.java#L982

- `Map.getOrDefault()`
https://github.com/androidx/media/blob/43d1fa933c8486f54d63079f539ceeddd68acbc8/libraries/transformer/src/main/java/androidx/media3/transformer/FrameworkMuxer.java#L150

- `Map.getOrDefault()`
https://github.com/androidx/media/blob/43d1fa933c8486f54d63079f539ceeddd68acbc8/libraries/transformer/src/main/java/androidx/media3/transformer/FrameworkMuxer.java#L154

- `LongConsumer.accept()`
https://github.com/androidx/media/blob/43d1fa933c8486f54d63079f539ceeddd68acbc8/libraries/common/src/main/java/androidx/media3/common/audio/SpeedChangingAudioProcessor.java#L213

- `LongConsumer.accept()`
https://github.com/androidx/media/blob/43d1fa933c8486f54d63079f539ceeddd68acbc8/libraries/common/src/main/java/androidx/media3/common/audio/SpeedChangingAudioProcessor.java#L264

Since there aren't that many usages, maybe removing `desugar_jdk_libs` from production could also be a solution?

**Comment by tonihei** [comment]
Thanks for highlighting this issue! 

We added the [additional Java8 desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring) before releasing 1.3.0. Our assumption was that this automatically propagates to apps similar to other dependencies. This was unfortunately not the case because of a tooling gap (see https://issuetracker.google.com/203113147).

The tooling gap is now fixed and upgrading our AGP version ensures this requirement automatically propagates to apps depending on our libraries. However, it just triggers a build error if the desugaring is not activated in the app. This means it's not fully automatic and still requires every app developer to add these flags manually to their gradle files.

Given this additional effort and the small number of current usage sites within our code, we decided not to depend on the enhanced desugaring for now to avoid this additional app config burden. Only once other core AndroidX libraries require this as well, we probably reintroduce it for our libraries too in the future.

**Comment by MGaetan89** [comment]
> Given this additional effort and the small number of current usage sites within our code, we decided not to depend on the enhanced desugaring for now to avoid this additional app config burden. Only once other core AndroidX libraries require this as well, we probably reintroduce it for our libraries too in the future.

Will it be worked on internally, or are you open for contributions for this?

**Comment by tonihei** [comment]
Thanks for considering a contribution! We already have the internal code change in review though and it should appear here soon.

**Comment by tonihei** [comment]
Thanks for considering a contribution! We already have the internal code change in review though and it should appear here soon.

**Comment by MGaetan89** [comment]
Thanks @tonihei, I see the changes now.
Do you know if they'll land in 1.4.0-alpha02 (or any followup release)? Or will there be a 1.3.2 release?

**Comment by tonihei** [comment]
Most likely only in 1.4.0 pre-releases. So far we are not planning to do a 1.3.2. 

(Closing the issue now as the original problem has been fixed/avoided)

**Comment by icbaker** [comment]
https://github.com/androidx/media/commit/6ac60c6dffb464851140d2a4bb21b38b26c11f8a removed the problematic usages. It looks like they were mostly introduced in API 24 (e.g. [`Collection.stream()`](https://developer.android.com/reference/java/util/Collection#stream()) and [`LongConsumer`](https://developer.android.com/reference/java/util/function/LongConsumer)), so I think any API level before that is affected.

**Comment by cadalt** [comment]
@icbaker thank you!
