### ISSUE TITLE
Feedback for Media3 Demo App - Improved Internet Handling

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [androidx/media#1323]
### Version

Media3 main branch

## Feedback for Media3 Demo App - Improved Internet Handling

I'm using the latest stable version of the Media3 demo app (1.3.1) written in Java. While the playback functionality is great, I'd like to suggest a feature enhancement related to internet connectivity.

Currently, if the internet connection is lost during stream playback, the stream stops and doesn't attempt to reconnect automatically. 

**Feature Request:**

* Implement functionality in the demo app to handle internet connection loss gracefully. When the internet connection is lost:
    * The playback should be paused.
    * The user should be notified about the lost connection (e.g., a toast message).
* Once the internet connection is restored:
    * The playback should automatically resume from where it left off (if possible) or restart the stream.

**Implementation (if not already available):**

If this feature isn't already implemented, I'd be grateful if you could consider adding it. Here's a general approach using listeners:

```java
// In your activity/fragment

private ConnectivityManager connectivityManager;

// ...

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    // ...
    connectivityManager = (ConnectivityManager) getSystemService(Context.CONNECTIVITY_SERVICE);
}

// ...

// Implement a listener for network connectivity changes
private final NetworkCallback networkCallback = new NetworkCallback() {
    @Override
    public void onAvailable(Network network) {
        // Internet connection restored, try to resume playback
        if (/* check if playback was paused due to lost connection */) {
            // Resume playback or restart stream
        }
    }

    @Override
    public void onLost(Network network) {
        // Internet connection lost, pause playback and notify user
        player.pause();
        Toast.makeText(getApplicationContext(), "Internet connection lost!", Toast.LENGTH_SHORT).show();
    }
};

// ...

// Start listening for network changes when needed (e.g., onResume)
connectivityManager.registerNetworkCallback(ConnectivityManager.DEFAULT_NETWORK, networkCallback);

// ...

// Stop listening for network changes when done (e.g., onPause)
connectivityManager.unregisterNetworkCallback(networkCallback);
```

**Sharing Existing Implementation (if available):**

If this functionality is already implemented, please kindly share a link to the relevant documentation or code snippet.

Thank you for your time and consideration. This improvement would make the Media3 demo app even more user-friendly! Kindest and Warm Regards,
Sincerely and Seriously and Respectfully,
Pooya M
Pooya Mohammadhossein

### Devices that reproduce the issue

Google Tv 4K (Chromecast)

### Devices that do not reproduce the issue

NA

### Reproducible in the demo app?

Yes

### Reproduction steps

1. open Media3 demo most stable version (1.3.1) Android App
2. while using stream disconnect the internet
3. then you will see the stream pause and even after internet connection restored the stream is not played back

### Expected result

he stream after  pause and even after internet connection restored the stream must played back automatically .

### Actual result

 the stream pause and even after internet connection restored the stream is not played back

### Media

No need to attach anything just please kindly test and review this information I have just shared, Thanks in advance!

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment]
The current default behavior retries a few times, which generally works to cover any temporary network issues where the connection is restored quickly. The retry behavior (number of retries, delays etc) can also be configured via `LoadErrorHandlingPolicy`. There is an [old medium post](https://medium.com/google-exoplayer/load-error-handling-in-exoplayer-488ab6908137) about this class with some examples and the case labeled "Do not surface load errors due to lack of network connectivity" could be interesting if you want to continuously retry until the connection is back. Alternatively, you could just let the player fail and re-prepare the playback once the connection is back as you already outlined above. 

The reason we don't add this logic internally is that most apps wouldn't expect playback to continue if the network is lost for a long period of time. This may be really unexpected to the user if the network loss happened multiple minutes ago for example.

**Comment by tonihei** [comment]
> I'm not using Exoplayer. I'm actually using the latest version of the Google media library (written in Java) for the Android project (version 1.3.1). This library used to be Exoplayer, but it's now a separate component.

The old ExoPlayer repository and the Media3 repository are based on the same code, so everything related to ExoPlayer is still relevant. Given the linked blog post is quite old, some APIs may be outdated though. The best way to set the `LoadErrorHandlingPolicy` is in [`DefaultMediaSourceFactory`](https://developer.android.com/reference/androidx/media3/exoplayer/source/DefaultMediaSourceFactory#setLoadErrorHandlingPolicy(androidx.media3.exoplayer.upstream.LoadErrorHandlingPolicy)), which can be configured via `ExoPlayer.Builder.setMediaSourceFactory`. 

> CustomPolicy Class Missing. After reviewing the documentation you linked, I couldn't find any information about a CustomPolicy class specific to the media library version 1.3.1.

The `CustomPolicy` in the example is an implementation you need to provide yourself. `LoadErrorHandlingPolicy` is just an interface, it has a default implementation in `DefaultLoadErrorHandlingPolicy`, but otherwise you need to provide your own implementations if you want to customize it further. 

> Would you be able to point me in the right direction

Given your use case, I would actually still recommend to do what you are currently doing as it seems like the simplest solution:
 - Listen to player errors to see when the error is caused by a connection problem and the current network has no Internet connection. 
 - Register a network listener and call `player.prepare()` once the network is back.
