### ISSUE TITLE
How to calculate buffer ratio/ time for analytics purposes

### ISSUE THREAD

**Issue by shubhamvashisht** [androidx/media#1330]
Exoplayer provides multiple metrics through PlaybackStats. I wanted to understand which stats i can use to compute the time playback was stopped due to buffering. 
does `PLAYBACK_STATE_PAUSED_BUFFERING` means same thing?

Also is `totalValidJoinTimeMs` a good way to understand click to playtime of a stream?

**Comment by tonihei** [comment]
> compute the time playback was stopped due to buffering

You probably want [`PlaybackStats.getTotalRebufferTimeMs()`](https://developer.android.com/reference/androidx/media3/exoplayer/analytics/PlaybackStats#getTotalRebufferTimeMs()) if I understand your goal correctly. Specifically, this counts the time from `PLAYBACK_STATE_BUFFERING` only (= the time a user actively waited for playback). `PLAYBACK_STATE_PAUSED_BUFFERING` is not included because the assumption is that a paused playback is not something a user is actively waiting for.

> understand click to playtime of a stream

Most likely this is [`getTotalPlayTimeMs`](https://developer.android.com/reference/androidx/media3/exoplayer/analytics/PlaybackStats#getTotalPlayTimeMs()) or [`getTotalPlayAndWaitTimeMs`](https://developer.android.com/reference/androidx/media3/exoplayer/analytics/PlaybackStats#getTotalPlayAndWaitTimeMs()) depending on whether you want to include the wait times or not. 

> How to calculate buffer ratio

If you are just after the ratios, there are also the predefined [`getRebufferTimeRatio`](https://developer.android.com/reference/androidx/media3/exoplayer/analytics/PlaybackStats#getRebufferTimeRatio()) and [`getWaitTimeRatio`](https://developer.android.com/reference/androidx/media3/exoplayer/analytics/PlaybackStats#getWaitTimeRatio()) methods that might be of interest

**Comment by shubhamvashisht** [comment]
as per docs [PlaybackStats.getTotalRebufferTimeMs()](https://developer.android.com/reference/androidx/media3/exoplayer/analytics/PlaybackStats#getTotalRebufferTimeMs()) does not include initial buffer and buffer after user has seeks. 
to understand the full picture we want to include those as well. 
does [getTotalWaitTimeMs()](https://developer.android.com/reference/androidx/media3/exoplayer/analytics/PlaybackStats#getTotalWaitTimeMs()) makes more sense?

**Comment by tonihei** [comment]
> does [getTotalWaitTimeMs()](https://developer.android.com/reference/androidx/media3/exoplayer/analytics/PlaybackStats#getTotalWaitTimeMs()) makes more sense?

This depends on your exact needs. Please read the method documentation carefully to know what is included and what isn't.  The method also links to the other 'wait time' methods like `getTotalJoinTimeMs` or `getTotalSeekTimeMs`.
