### ISSUE TITLE
Transformer does not work with supported image MimeTypes when the type comes from ContentResolver

### ISSUE THREAD

**Issue by kleiren** [androidx/media#1373]
When adding an image with a supported mimeType (.heic) as a mediaItem, and generating a video using the transformer, it will return an error with the message "Image format not supported by given bitmapLoader", although it should be supported.

The issue seems to be that in function [isImage()](https://github.com/androidx/media/blob/95c13819af1bc2259d90bac3eef2364cd0581af0/libraries/transformer/src/main/java/androidx/media3/transformer/DefaultAssetLoaderFactory.java#L153) from the DefaultAssetLoaderFactory, the mimeType is coming from the contentResolver directly as heic, and then checked with the function [isBitmapFactorySupportedMimeType()](https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/common/src/main/java/androidx/media3/common/util/Util.java#L3262) that only checks for heif instead of heic and heif.

```java
[...]
    if (mimeType == null) {
      if (Objects.equals(localConfiguration.uri.getScheme(), ContentResolver.SCHEME_CONTENT)) {
        ContentResolver cr = context.getContentResolver();
        mimeType = cr.getType(localConfiguration.uri);
      } else {
        mimeType = getCommonImageMimeTypeFromExtension(localConfiguration.uri);
      }
    }
[...]
    checkState(
        bitmapLoader.supportsMimeType(mimeType),
        "Image format not supported by given bitmapLoader");
[...]
``` 

If the mimetype does not come from the content resolver, it will be extracted from the file extension and "commonized" using [getCommonImageMimeTypeFromExtension()](https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/transformer/src/main/java/androidx/media3/transformer/DefaultAssetLoaderFactory.java#L196)
In this case, if the image is heic, it will return a heif mimetype, and will pass the isBitmapFactorySupportedMimeType() check.
Of course this should happen with many other image types.

My question is, **is there any way of skipping this check?** I have tried setting the mimetype directly to the mediaItem, but it seems to be ignored for this case. Maybe this is a bug and supportsMimeType() should "commonize" all mimetypes.

Thanks!

**Comment by tof-tof** [comment]
It seems there is a bug in the fact that the checkState throws in this case. I'll submit a fix for this.

There is a few ways to surpass the check. you can set the mimetype to be `image/heif` instead of `image/heic` which passes the `supportsMimeType` check for the default bitmap loader.

Alternatively, you can pass a [BitmapLoader](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/util/BitmapLoader.java) implementation, for which `bitmapLoader.supportsMimeType("image/heic")` returns true (possibly just by wrapping the default [DataSourceBitmapLoader](libraries/datasource/src/main/java/androidx/media3/datasource/DataSourceBitmapLoader.java) and changing the relevant method) the bitmapLoader can be passed an an argument for the [DefaultAssetLoaderFactory](https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/transformer/src/main/java/androidx/media3/transformer/DefaultAssetLoaderFactory.java#L105), which can then be passed into [Transformer](https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/libraries/transformer/src/main/java/androidx/media3/transformer/Transformer.java#L410)
