### ISSUE TITLE
How to call setMediaSource method by MediaController? 

### ISSUE THREAD

**Issue by allenxu-passion** [androidx/media#1399]
I use media3 to implement a music player. The specific implementation is to connect to MediaSession through MediaController and then call ExoPlayer. (Recommended by the media3 official website)

Then I use MediaController to play audio. I need to use the setMediaSource method, but MediaController does not provide this method of calling. How to deal with it?

ExoPlayer provide setMediaSource method.

**Comment by marcbaechinger** [comment]
Like you say, the `setMediaSource` method is part of the `ExoPlayer` interface rather than the `Player` interface. The `Player` interface can be implemented by another player, while this would be much more difficult with `ExoPlayer`. That's the reason why the player of a session is only a `Player` as opposed to a`ExoPlayer`.

Said this, it seems apparent that the `setMediaSource` method which is ExoPlayer specific will never make it into the `Player` interface.

What you can do in your integration is using a custom `MediaSource.Factory` when building the player:

```kotlin
ExoPlayer.Builder(this)
    .setMediaSourceFactory(MyMediaSourceFactory())
    .build()
```

You can then use for instance `mediaController.setMediaItem(myMediaItem)`, this will be sent to the session and there to the ExoPlayer instance which will call the `createMediaSource(MediaItem)` method of your custom media source factory. The media item passed to your factory will be what the controller sends to the session, you can create your custom media source instance accordingly and return it. The player that called the factory, will then use your media source to call `exoPlayer.setMediaSource(source)` with it.

Sample `MediaSource.Factory` impl to get the idea and to start with: 

```Kotlin
class MyMediaSourceFactory(val defaultFactory: DefaultMediaSourceFactory) : MediaSource.Factory {
  override fun setDrmSessionManagerProvider(
    drmSessionManagerProvider: DrmSessionManagerProvider
  ): MediaSource.Factory {
    defaultFactory.setDrmSessionManagerProvider(drmSessionManagerProvider)
    return this
  }

  override fun setLoadErrorHandlingPolicy(
    loadErrorHandlingPolicy: LoadErrorHandlingPolicy
  ): MediaSource.Factory {
    defaultFactory.setLoadErrorHandlingPolicy(loadErrorHandlingPolicy)
    return this
  }

  override fun getSupportedTypes(): IntArray {
    return defaultFactory.supportedTypes
  }

  override fun createMediaSource(mediaItem: MediaItem): MediaSource {
    if (isMediaItemThatNeedsCustomSource(mediaItem)) {
      return createMySpecialMediaSource(mediaItem)
    }
    return defaultFactory.createMediaSource(mediaItem)
  }
}
```

**Comment by allenxu-passion** [comment]
@marcbaechinger That's a good idea. Thanks a lot. I also tried customize SessionCommand.
