### ISSUE TITLE
How to process each video frame when using Exoplayer play a RTSP stream?

### ISSUE THREAD

**Issue by gscholer** [androidx/media#1455]
Here is a similar question https://github.com/google/ExoPlayer/issues/7167, I am using exoplayer to pull and decode a RTSP stream, it can display the video now, but I want apply a deep learning model to detect something appeared on each frame.

From the answer of [andrewlewis](https://github.com/google/ExoPlayer/issues/7167#issuecomment-608306654), I think using a `ImageReader` is the easiest solution, but I am new to android development and couldn't find any examples trying my best. I hope someone can help me, and other solution to this problem can also be accepted.

**Comment by droid-girl** [comment]
Hi @gscholer ,
This issue seems to be similar to #1422. Are you also looking at using TFLite? 
Another suggestion is to check out MediaPipe integration with Transformer in the [demo app](https://github.com/androidx/media/tree/release/demos/transformer) to get an idea how to integrate with MediaPipe library.
If you want to use MediaPipe with ExoPlayer, you can:

- create your custom effect using MediaPipe (check out [transformer demo](https://github.com/androidx/media/blob/d833d59124d795afc146322fe488b2c0d4b9af6a/demos/transformer/src/main/java/androidx/media3/demo/transformer/TransformerActivity.java#L483) for more info)
- use `.setVideoEffects` in ExoPlayer to set your custom MediaPipe effect

For TFLite, I will add more details on integration shortly to #1422.

**Comment by gscholer** [comment]
Hi @droid-girl, Thanks for your reply. I am looking forward your TFLite integration.

**Comment by droid-girl** [comment]
More info is now added to https://github.com/androidx/media/issues/1422. Closing this issue
