### ISSUE TITLE
The progress of the still video screen seems to change in milliseconds

### ISSUE THREAD

**Issue by kwonjae-lee** [androidx/media#1466]
### Version

Media3 main branch

### Devices that reproduce the issue

Samsung S21+, AOS 13

### Reproducible in the demo app?

Yes

### Reproduction steps

1. disable release/initialize player on stop/start the activity (from sample)
<img width="629" alt="스크린샷 2024-06-17 오후 11 00 11" src="https://github.com/androidx/media/assets/98582953/3ee0fb53-a67c-4b52-ac0e-0bbec8dca00c">
2. select 'Clear DASH' -> 'HD (MP4, H264)' (or other MP4 example)
3. click the pause button
4. go background and back to foreground
5. repeat step4 and check the video

### Expected result

The progress of the still screen should remain unchanged.

### Actual result

The progress of the still screen appears to change in milliseconds.

### Media

https://github.com/androidx/media/assets/98582953/a6fce97b-3926-4398-915d-7326d4bdfc2c

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by kwonjae-lee** [comment]
I found this issue when I tried to re-use a view in RecyclerView.
And it looks similar to this issue - https://github.com/androidx/media/issues/1278

**Comment by kwonjae-lee** [comment]
Thanks for your explanation.
And I totally understand your concern( `keeping the player (and the codec in particular) while the app is in background may cause unexpected side effects`)
But my service has a requirement which is focused on visibility not on performance.
Because there is flicker of screen when I release and initialize the player.
(The screen is black while the player load media file.)
So isn't this supposed to be fixed? I mean, should I explain to my team member that this is not a problem.

**Comment by tonihei** [comment]
> So isn't this supposed to be fixed?

Could you highlight what exactly you are trying to achieve? There may be alternatives to your current usage pattern.

But generally, the way codecs work is that they release frames to a surface and there is no way to get the last released frame back again. To avoid this, you need to either recreate the codec or not destroy the surface:
 - New codec, new (or same) surface -> some initial delay during set up, but can start with the previous frame precisely. This is what the Media3 demo is doing by default.
 - Same codec, new surface -> current test setup as described above, can only release the next frame
 - Same codec, same surface -> keeps content, but there is no guarantee you can keep the surface. Surfaces are automatically destroyed when the Activity is stopped or they are no longer connected to the view hierarchy. If you handle them in RecyclerView, you may be able to move an existing Surface to an out-of-screen position while you don't need it, or you try `SurfaceControl` to reparent an exiting Surface in another View. 

> The screen is black while the player load media file

The typical solution to this is to show a placeholder image. You may be able to achieve this by using `TextureView` and then call `getBitmap` when the surface is destroyed. Or preferably, you can start preparing the output early enough so that it's already ready when it comes into view.

**Comment by kwonjae-lee** [comment]
Thank you, you already suggested alternative solution for me.
Actually I wanted to keep the surface even if it was disconnected from the view hierarchy.
I used "TextureView" and the "TextureView" was destroyed when detached from window (as you mentioned)
I think "SurfaceControl" or "Placeholder image"(from "getBitmap") can be a solution.
