### ISSUE TITLE
Which HLS versions are supported by Exoplayer?

### ISSUE THREAD

**Issue by jonathanlassen** [androidx/media#1498]
Which HLS versions are fully supported by Exoplayer? Alternatively, which features of the most recent non-draft version (15) are NOT supported by Exoplayer? I have been unable to locate this information. Asked in the video-dev Slack space, was referred here.

Thanks!

**Comment by icbaker** [comment]
ExoPlayer doesn't generally claim to support **all** features covered by specific profiles of versions of specifications, preferring instead to focus on implementing support for the features that are most demanded by our community of developers. This way we can ensure we're investing in features that people will actually use, rather than implementing potentially unused features just to fulfil a particular profile or version of a spec.

I would suggest the best way to determine if a feature that you're interested in is supported is to simply try it with a playlist containing the feature.

You can see some more detail on the reasoning behind this approach here: https://github.com/google/ExoPlayer/issues/8010#issuecomment-706364494
