### ISSUE TITLE
How hide service notification while player in foreground?

### ISSUE THREAD

**Issue by VolodymyrYeletskyi** [androidx/media#152]
Hello, I have a question. In our app we want to implement video player's behaviour like on YouTube or Netfix: when user presses Home button player goes to the background and a notification appears. After user re-opens the app the notification hides. We want to use MediaSession Service, however in all examples that we found service always shows the notification. So, the question is: how can we hide service notification while player is not in the background?

**Comment by buggily** [comment]
I believe you could achieve such behavior by overriding the [`onUpdateNotification`][MediaSessionServiceOnUpdateNotification] method of your [`MediaSessionService`][MediaSessionService] or [`MediaLibraryService`][MediaLibraryService]. As you described, the [Get Started][Media3Notification] documentation verifies a "MediaSessionService automatically creates a MediaNotification," but the documentation comment of [`onUpdateNotification`][MediaSessionServiceOnUpdateNotification] elaborates by inviting you to "override this method to create your own notification and customize the foreground handling of your service." The service uses the session (rather than the notification itself) to determine when "a notification needs to be shown, updated or cancelled," so I believe this would be sufficient for your use case. But please note the [`MediaSessionSerivce`][MediaSessionService] documentation comment does specify, "you must also start or stop the service from the foreground [...] when playback starts or stops respectively" when implementing such behavior.

[MediaSessionService]: https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSessionService.java

[MediaLibraryService]: https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaLibraryService.java

[MediaSessionServiceOnUpdateNotification]: https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSessionService.java#L408

[Media3Notification]: https://developer.android.com/guide/topics/media/media3/getting-started/playing-in-background#notification

**Comment by VolodymyrYeletskyi** [comment]
So, if we start and stop service manually, should we have two player instances: first one for service and second one for foreground player ?

**Comment by rohitjoins** [comment]
@VolodymyrYeletskyi You can achieve this by overriding [onUpdateNotification](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSessionService.java#L408) method as explained in https://github.com/androidx/media/issues/152#issuecomment-1217386939. We recommend to start the service only using `MediaController`. We cannot provide 1:1 support for achieving this and recommend understanding how `DefaultMediaNotificationProvider` works to implement one for your specific use case.
