### ISSUE TITLE
Media3 Exoplayer Not showing Embedded Video Subtitle for HLS(M3U8) Stream

### ISSUE THREAD

**Issue by Ottanddev** [androidx/media#1526]
### Version

Media3 1.3.1

### More version details

Media3 1.3.1

### Devices that reproduce the issue

All devices

### Reproducible in the demo app?

Yes

### Reproduction steps

Issue HLS stream shared on mail :- android-media-github@google.com

### Expected result

ExoPlayer should able to show Embedded Subtitle.

### Actual result

ExoPlayer not able to show Embedded Subtitle of HLS Stream which is shared on (android-media-github@google.com)

### Media

Issue HLS stream shared on mail :- android-media-github@google.com

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
This is because the playlist does not declare the `TYPE=CLOSED-CAPTIONS` as described in https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.6.1.

I would recommend fixing the playlist to fully declare the expected info.

If that's not possible, you can disable chunkless preparation in order to expose these subtitles in ExoPlayer: https://developer.android.com/media/media3/exoplayer/hls#disabling-chunkless

**Comment by Ottanddev** [comment]
Thank you @icbaker .
By declaring TYPE=CLOSED-CAPTIONS in playlist, embedded subtitles working fine.
