### ISSUE TITLE
Suppressing KEYCODE_MEDIA_PLAY in onMediaButtonEvent causes ForegroundServiceDidNotStartInTimeException

### ISSUE THREAD

**Issue by Digipom** [androidx/media#1528]
### Version

Media3 1.3.1

### More version details

androidx.media3:media3-session:1.3.1

### Devices that reproduce the issue

Pixel 7

### Reproducible in the demo app?

Not tested

### Reproduction steps

1) Set a custom callback on the media session
2) Override onMediaButtonEvent
3) Return true when keyCode == KEYCODE_MEDIA_PLAY so that the key is not processed.
4) Swipe the app away and make sure that the process is ended.
5) Start the app via a Bluetooth event.

### Expected result

Event can be suppressed without further crashes.

### Actual result

After around 10 seconds, the service will crash with ForegroundServiceDidNotStartInTimeException

### Media

N/A

### Additional info

The context behind this is that I want to suppress my app from being automatically started by Bluetooth players such as cars when the app isn't currently running. The logic for this is working correctly, however, when the service was just started by the event and the process wasn't running previously, then the app will eventually crash with a ForegroundServiceDidNotStartInTimeException. 

My short-term workaround is to show a dummy notification and then immediately stop the service. 

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by marcbaechinger** [comment]
I think it's difficult to suppress the play event in such a case.  Once the service is started as a foreground service, it must be put into the the foreground or the system crashes the service.

From your description it seems that this is a problem only, when your started when the service isn't yet running which means the play event comes as a media button event through the `MediaButtonReceiver`. The only way I see to avoid this crash is to not start the service. If the intent is intercepted before the [`MediaButtonReceiver` starts the service](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaButtonReceiver.java#L147), then that problem can't happen.

However, there isn't a way to do that with the current version. If you want to verify this you can write your own media button receiver and intercept the intent there. You've described the event there with the `Intent.EXTRAS_PACKAGE_NAME` lkey which could be a way to recognize the BT event early enough. It's mostly about whether your approach to check foreground and the like works there. In general, any media button events routed trough the receiver starting and after API 26 that you support can be expected to be a playback resumption event. Everything else goes either directly to `onStartCommand` of the service or to `onMediaButtonEvent` of the `MediaSessionLegacyStub`.

From the library side it's difficult to decide this, but we can create a method `shouldStartService(Intent)` or similar, which by default always returns true for medi abutton intents, but can be overriden by an app to do a custom decision. The receiver would then just do nothing.

Would that an approach for you that works for your use case?

**Comment by Digipom** [comment]
@marcbaechinger There's a lot to untangle here. I'd like to summarize it just to be sure I understand:

1) To avoid the "ForegroundServiceDidNotStartInTimeException", we can provide a custom MediaButtonReceiver.

If we do 1), then do we still have to worry about the service state in onMediaButtonEvent? If the button event is coming through onStartCommand or onMediaButtonEvent? When would it go through the first, and when would it go through the second? Just trying to better understand.

**Comment by marcbaechinger** [comment]
If you don't start the service in the receiver, the intent does not arrive in the the service and or the session callback.

From the library side (excluding apps that may try to broadcast a media button event) there are 2 ways how a media button event `Intent` arrives at `onStartCommand()`:

1. Below API 32 and when the service is running and receives a `PendingIntent` that Media3 has posted as part of a media notification.

2. When the service is not running and the system routes a media button event from BT to the media button receiver (unless you intercept in the receiver as described in my post).

> When would it go through the first, and when would it go through the second?

Both of these cases are delegated by Media3 to `MediaSession.Callback.onMediaButtonEvent`.

Note that `Callback.onMediaButtonEvent` can also be called when an app uses the legacy library and uses [`MediaControllCompat.dispatchMediaButtonEvent`](https://developer.android.com/reference/kotlin/android/support/v4/media/session/MediaControllerCompat#dispatchMediaButtonEvent(android.view.KeyEvent)). However, this only happens when the service is already running through the controller connecting to the service.

> If we do 1), then do we still have to worry about the service state in onMediaButtonEvent?

1) prevents the `ForegroundServiceDidNotStartInTimeException` in the first place.

I'm not totally familiar with the case you described regarding the auto-play in cars. If this can happen when the service is already running, then it would come to your callback through the case with `MediaControllCompat.dispatchMediaButtonEvent`. Intercepting this call an not playing shouldn't cause a `ForegroundServiceDidNotStartInTimeException` as far as I can tell. 

> The "shouldStartService(Intent)" you were suggesting, would that also be called by MediaButtonReceiver? 

Only there. That would be a method in `MediaButtonReceiver` that returns true by default and that an app can override and then check the `Intent` to decide.

> If we wanted to fix this today, would the best way be to just override
> MediaButtonReceiver and then continue handling in onMediaButtonEvent as we're doing now?

Yes, that sounds like a good plan. I have sent a CL for review that does offer this method with the Media3 `MediaButtonReceiver` . But this won't be included in 1.4. So you can fix that like you say today and then move back to the library one later to avoid needing to maintain that some further. (or you can copy ours from the main branch here as soon as available as source).

**Comment by Digipom** [comment]
@marcbaechinger OK excellent, I think I know what to do now to test out a fix to this for now. Will try and report back.

**Comment by Digipom** [comment]
@marcbaechinger OK it works with a custom media button receiver. Unfortunately, I had to copy/paste all of the code because onReceive is final. A side benefit is that we also don't get the weird intent where the controller is set to our own package, but EXTRA_PACKAGE is set to bluetooth. I also did not receive any ForegroundServiceDidNotStartInTimeExceptions.

Essentially we have to drop the request at two places: 
1) In the media button receiver,
2) In onMediaButtonEvent.

It would be great from an API standpoint if it was possible to only drop the request in one spot. Barring that, making it possible to override the button receiver instead of copy/pasting the whole thing would also be an improvement.

Thanks very much for your time with this.

**Comment by marcbaechinger** [comment]
The commit above offers a method 'shouldStartForegroundService(Intent)' that an app can override to decide whether to start the service for the given `Intent`.

I'm closing this issue. Please re-open if required.

**Comment by Digipom** [comment]
@marcbaechinger Thank you so much for adding this feature. How can I check which version it will be merged into?

I just have a question that is tangentially related to this issue -- If we wanted the app to not open at all (not only just ignore the Bluetooth request), what would that mean in terms of behavior?

My thought is to just disable the MediaButtonReceiver component, but I'm not sure how that applies to background session handling if the process is already running and the session is considered active. Do we need to do something with onPlaybackresumption so that the system ignores our session and tries to connect to another session (or does nothing) instead? Could you please clarify this one?

A second question: the docs say "Important: If you add the MediaButtonReceiver, you must implement MediaSession.Callback.onPlaybackresumption() as a second step.". We don't do this, but we're also overriding MediaSessionService, not MediaLibraryService. Everything still seems to work and always has.

**Comment by marcbaechinger** [comment]
> but I'm not sure how that applies to background session handling if the process is
> already running and the session is considered active

When there is a session, the media button event is never delivered to the `MediaButtonReceiver` (except below API 21). See [these diagrams](https://developer.android.com/media/legacy/media-buttons#finding-a-media-session) for details.

>  but we're also overriding MediaSessionService, not MediaLibraryService. 

This is relevant for both services, not only `MediaLibraryService`. Playback resumption is a feature of `MediaSession/MediaSession.Callback`. `MediaLibraryService` is required for playback resumption over the System UI notification.

> We don't [override `onPlaybackResumption()`]. Everything still seems to work and always has.

Overriding `onPlaybackResumption()` is mandatory, because the library assumes that when the service is newly started, the player is empty without media items populated into the playlist. 

If you are saying this works, then I guess your app already populates media items into the playlist in `onCreate` or at some other point before the play event should be executed. Playback resumption is then [not triggered](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSessionImpl.java#L846-L848) because `player.getCurrentMediaItem() != null`. You could instead implement `onPlaybackResumption()` and return the items there to make the library populate the playlist with it for you.
