### ISSUE TITLE
Current application thread check for player.createMessage

### ISSUE THREAD

**Issue by sdryganets-sc** [androidx/media#1554]
Currently we are using createMessage player's method for the cases where we could have a different thread.
I would like to double check whenever it is a safe approach as latest exoplayer version has a thread check for that method and it makes it impossible to call it.

There is still an option to create a handler and schedule new runnable, though the way we use seems more elegant.

Do you think it worth to excuse createMessage from this check? It should be safe to create the message on different thread anyway, right?

```
player.createMessage(audioRenderer).setType(Renderer.MSG_SET_VOLUME).setPayload(volume).send();
```

What do you think?

Maybe this particular case is not very convincing (I'm changing the code to the post runnable as it is more clean) though it is still weird that you can create the player message only on specific thread.

**Comment by marcbaechinger** [comment]
Thanks for your suggestion. 

> It should be safe to create the message on different thread anyway, right?

I don't think simply removing the check would be safe but I think it can be done in a sufficiently safe way, so that the check can be removed. I'll send a change into internal review as a proposal and will update this issue when there is some news.

**Comment by dryganets** [comment]
Thank you for doing that Marc!

**Comment by marcbaechinger** [comment]
Well, sorry for creating a wrong expectation. Like I said just removing the thread check would be problematic, because creating the `PlayerMessage` involves accessing state that can be access only from the application thread. If we would remove this check then it can be that the data used for creating the message is stale, because it has been changed in the app thread already but isn't available in another thread. Doing for instance:

```
player.setMediaItems(mediaItems);
handlerOfOtherThread.post(() -> player.createMessage(...).send());
```

could potentially create a message with data that isn't up to date with the items just set.

We can't waive this check unfortunately, as loosening that around `createMessage()` would introduce problems with such calls that isn't really forseeable.

Like you state, you can crate a handler to the app thread which the thread on which you create the player or the looper that you explicitely pass to the `ExoPlayer.Builder`. You can then do:

```
new Handler(player.getApplicationLooper(), /* callback= */ null).post(() -> {
   player.createMessage(sender).send();
});
```

Sorry for jumping the gun with giving an quick and early but not well thought response.
I'm closing this issue as won't fix: intended behaviou. Please re-open if you think this isn't right.

**Comment by sdryganets-sc** [comment]
NP, it is also good to know it is not safe to do what we were doing :)
Thank you Marc!
