### ISSUE TITLE
External subtitle with 1.4.0

### ISSUE THREAD

**Issue by michaelnimbs** [androidx/media#1569]
I use Exoplayer to play videos from remote urls together with an external subtitle, also from a remote url, like:

Video: `https://example.url/video.mkv`
Subtitle: `https://example.url/video.srt`

Before 1.4.0 I basically used
```
val subtitleSource = SingleSampleMediaSource.Factory(httpDataSourceFactory.value)
    .createMediaSource(subtitleConfiguration, C.TIME_UNSET)
MergingMediaSource(videoSource, subtitleSource)
```

What is the migration path due to the architectural changes regarding "parsing during extraction" subtitles with 1.4.0?
Do I need to download the subtitle file first and convert it to `application/x-media3-cues`?

Any help on figuring this out would be greatly appreciated.

**Comment by icbaker** [comment]
Instead of manually creating `MediaSource` instances, can you use `DefaultMediaSourceFactory` (the default when using `ExoPlayer.Builder`) with `Player.setMediaItem` and `MediaItem.Builder.setSubtitleConfigurations`? That way, you won't have to make any further changes to handle the subtitle changes in 1.4.0 because it's all handled by `DefaultMediaSourceFactory`.

----

If that's not possible, you need to change your instantiation of `SingleSampleMediaSource` to be a `ProgressiveMediaSource` with an `ExtractorsFactory` configured to handle subtitles, the same way it's done in `DefaultMediaSourceFactory`:

https://github.com/androidx/media/blob/b01c6ffcb3fca3d038476dab5d3bc9c9f2010781/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/source/DefaultMediaSourceFactory.java#L512-L538

**Comment by michaelnimbs** [comment]
Perfect, works great with `DefaultMediaSourceFactory` and `MediaItem`, thank you!
