### ISSUE TITLE
How to Test if Video is Playing in Hardware or Software Mode in ExoPlayer?

### ISSUE THREAD

**Issue by PratikLahagora** [androidx/media#1573]
I want to implement the option to choose between hardware and software decoding in ExoPlayer based on user selection. I've implemented the following code:

```kotlin
 private fun buildRenderersFactory(useHardwareDecoders: Boolean): RenderersFactory {
    return DefaultRenderersFactory(this).apply {
        if (useHardwareDecoders) {
            setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_OFF)
                .setMediaCodecSelector { mimeType, requiresSecureDecoder, requiresTunnelingDecoder ->
                    var decoderInfos: List<MediaCodecInfo> = MediaCodecSelector.DEFAULT.getDecoderInfos(
                        mimeType, requiresSecureDecoder, requiresTunnelingDecoder
                    )
                    if (MimeTypes.VIDEO_H264 == mimeType) {
                        // Copy the list because MediaCodecSelector.DEFAULT returns an unmodifiable list
                        decoderInfos = ArrayList(decoderInfos).asReversed()
                    }
                    decoderInfos
                }
        } else {
            setExtensionRendererMode(DefaultRenderersFactory.EXTENSION_RENDERER_MODE_PREFER)
        }
    }
}
````

However, I'm not sure if this is working correctly. I want to test whether the video is being played with hardware or software acceleration. I tried the following approach:

```kotlin
private inner class CustomAnalyticsListener : AnalyticsListener {
    override fun onVideoDecoderInitialized(
        eventTime: AnalyticsListener.EventTime,
        decoderName: String,
        initializedTimestampMs: Long,
        initializationDurationMs: Long
    ) {
        Log.d("EXOPLAYER_DECODER", "Video decoder initialized: $decoderName")
    }

    override fun onVideoInputFormatChanged(eventTime: AnalyticsListener.EventTime, format: Format) {
        Log.d("EXOPLAYER_DECODER", "Video input format changed: $format")
    }

    // Override other methods if needed
}
```

No matter what I select (HW or SW), the decoder name gives me the same result every time: "Video decoder initialized: OMX.Exynos.avc.dec".

How can I accurately test whether my video is being played using hardware or software acceleration in ExoPlayer?

**Comment by microkatz** [comment]
Hello @PratikLahagora,

Based on your code, it appears that whether `useHardwareDecoders` is true or false, you are calling `setExtensionRendererMode`.  As per the javadoc, `setExtensionRendererMode` determines if and how available extension renderers are used. These are software decoding libraries like [ffmpeg](https://github.com/androidx/media/tree/release/libraries/decoder_ffmpeg), [LibopusAudioRenderer](https://github.com/androidx/media/tree/release/libraries/decoder_opus), etc. You would have to build out the modules according to the directions and by setting the extension preference, those extensions may be used if supporting the content. Also discussed [here](https://developer.android.com/media/media3/exoplayer/supported-formats#sample-formats).

With ExoPlayer playback without extensions, ExoPlayer will generally use decoders supplied by MediaCodec. These may be hardware or software decoders. What your code seems to be doing is overriding the getDecodersInfo method to reverse the list of decoders that will be supplied to the renderer. However, generally hardware is preferred for decoding so that is why OMX.Exynos.avc.dec keeps getting selected.

If you are trying to change if hardware or software decoders are used via the MediaCodec route, you can return a stripped version of that decodersInfo object by the selector. MediaCodecInfo has a field called [hardwareAccelerated](https://source.corp.google.com/piper///depot/google3/third_party/java_src/android_libs/media/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/mediacodec/MediaCodecInfo.java;bpv=1;bpt=1;rcl=658431584;l=121?gsn=hardwareAccelerated&gs=KYTHE%3A%2F%2Fkythe%3A%2F%2Fgoogle3%3Flang%3Djava%3Fpath%3Dandroidx.media3.exoplayer.mediacodec.MediaCodecInfo%23042ad7d45ac5630b9c84c11d6ce959756a4703810fb7878ad1a1685e52add49a). If `!useHardwareDecoders` then remove all MediaCodecInfo in decodersInfo that have hardwareAccelerated as `true`.

Hope that helps! Please reach out if you have any additional questions!

**Comment by microkatz** [comment]
As there has been no response I am assuming that my comment helped address your problem. I will close this issue. Please reopen or create a new one if you have additional questions!
