### ISSUE TITLE
Old extensions & Media3 ExoPlayer compatibility

### ISSUE THREAD

**Issue by NikSatyr** [androidx/media#16]
We rely on some ExoPlayer extensions for audio playback within our app. These include ffmpeg, mpegh, flac & some other proprietary extensions. They have been developed & built based on `com.google.android.exoplayer2`. And as we suspect, these proprietary extensions will require some (unknown :)) time to be updated to use media3.

So far we decided to continue to use old `com.google.android.ExoPlayer` that works fine with our extensions and plug that into Media3 MediaSession by creating an adapter. That adapter would implement `androidx.media3.common.Player`, proxying calls to a wrapped `com.google.android.ExoPlayer`. However, this is going to be really cumbersome due to lots of conversions of objects.

Is there any chance that some compatibility tool will be provided or should we go with the described adapter? Or maybe there's even a better & recommended way to do this?

**Comment by icbaker** [comment]
> And as we suspect, these proprietary extensions will require some (unknown :)) time to be updated to use media3.

`media3` contains pretty much everything that `exoplayer2` does - the only catch is that some classes have moved between packages. I suspect it wouldn't actually be that hard to migrate these extensions to work with `media3` - it should basically just be a case of resolving compilation failures caused by classes moving around.

> So far we decided to continue to use old `com.google.android.ExoPlayer` that works fine with our extensions and plug that into Media3 MediaSession by creating an adapter. That adapter would implement `androidx.media3.common.Player`, proxying calls to a wrapped `com.google.android.ExoPlayer`. However, this is going to be really cumbersome due to lots of conversions of objects.
> 
> Is there any chance that some compatibility tool will be provided or should we go with the described adapter? 

We don't have any plans to create a tool to convert objects between `exoplayer2` and `media3` at runtime.

> Or maybe there's even a better & recommended way to do this?

I think you're better off migrating everything to `media3`, rather than trying to use both `exoplayer2` and `media3` concurrently in the same project.

**Comment by NikSatyr** [comment]
yep, that absolutely makes sense that migrating the extensions should be as simple as changing the package, but that should be done by our vendors. we'll try to push them, but anyway, it's our call now.

Thanks!
