### ISSUE TITLE
Issue with oldPosition and newPosition when changing audio using seekbar.

### ISSUE THREAD

**Issue by debz-eight** [androidx/media#1617]
Reference: Issue #1537 

So I have media player with `MediaSessionService` and `MediaController` implemented.

Now in the player listener I have implemented `onPositionDiscontinuity()` that has `oldPosition` and `newPosition` and `reason`.

For reason I am checking for `DISCONTINUITY_REASON_AUTO_TRANSITION` and `DISCONTINUITY_REASON_SEEK`.

When I click the next button on my UI which triggers `controller.seekToNext()` it is trigerring REASON_SEEK and say `oldPosition.mediaItemIndex` is **2**, then `newPositon.mediaItemIndex` is **3**. This is working fine as expected.

But when I am seeking via the seekbar in my UI to the end of player for `mediaItemIndex` **2** and then moving to next media item which is the **3rd**, the `oldPositon.mediaItemIndex` and `newPosition.mediaItemIndex` are both **2**.

Is this expected or am I doing something wrong?

@marcbaechinger Can you please take a quick look at this?

**Comment by icbaker** [comment]
> But when I am seeking via the seekbar in my UI to the end of player for `mediaItemIndex` **2** and then moving to next media item which is the **3rd**, the `oldPositon.mediaItemIndex` and `newPosition.mediaItemIndex` are both **2**.

It's possible I'm misunderstanding your repro steps here, and maybe a video would help, but based on my understanding this sounds expected to me. If you drag the seek bar to the end of 'item 2' then the resulting discontinuity would have both old and new index of 2 - since "end of 2" is still within 2.

This is contrast to `seekToNext()` which results in seeking to the **start** of item 3 - and therefore the "new index" in the discontinuity is 3.

**Comment by debz-eight** [comment]
Got it. This seems to be the expected behavior as you explained.
