### ISSUE TITLE
[ExoPlayer Downloader] How to map new keySetId (license) to earlier downloaded content

### ISSUE THREAD

**Issue by rdutta2020** [androidx/media#1640]
We are trying download and playback of offline content using ExoPlayer Downloader.
Steps which we are following now :
1. WidevineOfflineLicenseFetchTask / execute (OfflineLicenseHelper/downloadLicense) 
2. "keySetId" returned from above step is saved
3. Track Selection happens
4. DownloadRequest is made with "uri" , "keySetId" is also used for DownloadRequest preparation
5. DownloadRequest prepared in above step is used to call "DownloadService.sendAddDownload" which downloads actual content

-> Now after few days, license gets expired and we want to refresh license **without downloading the content again**.
There is **no "renew" support from our backend** so we **cannot call** "OfflineLicenseHelper/renewLicense".
Instead of that, our backend wants us to download license again.
To do that, we can call "OfflineLicenseHelper/downloadLicense" again, it will return new "keySetId" , but as we would not be initiating step 4 and 5 again, so how can we map this updated "keySetId" to earlier downloaded content ?

Concisely, we want to map new keySetId (license) to earlier downloaded content.

**Comment by icbaker** [comment]
I think you must already have some wiring in your app code to plumb the `keySetId` into the player when it comes to playing the downloaded content. The demo app does this here:

https://github.com/androidx/media/blob/51622b6d80f5e73734d43b4c0b4fd63902ddb0ff/demos/main/src/main/java/androidx/media3/demo/main/PlayerActivity.java#L565-L568

If you have stored the new `keySetId` somewhere, then you can simply use that new value at this point instead of the `keySetId` from the `DownloadRequest`.

**Comment by rdutta2020** [comment]
It worked, thats for the help.
