### ISSUE TITLE
AnalyticsCollector's  java.lang.ArraylndexOutOfBoundsException

### ISSUE THREAD

**Issue by captain81** [androidx/media#1645]
```
java.lang.ArraylndexOutOfBoundsException length=11; index=11
at android.util.ContainerHelpers.binarySearch(ContainerHelpers.java:28)
at android.util.SparseArray.get(SparseArray.java:134)
at android.util.SparseArray.get(SparseArray.java:125)
at com.oplus. tbl.exoplayer2.analytics.AnalyticsListenerb.d (AnalyticsListener.java:19)
at com.oplus.tbl.exoplayer2.analytics.a.12 (AnalyticsCollector.java:3)
atcom.oplus.tbl.exoplayer2.analytics.a. LO(Unknown Source:0)at bd3.d.a(Unknown
80352513Source:8)
at we3.p$c.b(ListenerSet.java:24)
at we3.p.f(ListenerSet.java:28)
atwe3.p.a(Unknown Source:0)
at we3.n.handleMessage(Unknown Source:2)at
android.Os.Handler.dispatchMessage(Handler.java:102)
```

I am creating three exoplayer instances and runs in Multi-thread. AnalyticsCollector's eventTimes and listeners are defined as 
```
private final SparseArray<EventTime> eventTimes;
private ListenerSet<AnalyticsListener, AnalyticsListener.Events> listeners;
```

Reported up ArraylndexOutOfBoundsException crash error in Multi-thread. 
eventTimes and listeners are SparseArray type. They are not safe in Multi-thread.
So I add synchronized for all eventTimes and listeners operated by Multi-thread In AnalyticsCollector. 
Is there any risk in making this modification?

```
    synchronized (this) {
      eventTimes.put(eventFlag, eventTime);
      listeners.sendEvent(eventFlag, eventInvocation);
    }
```

**Comment by tonihei** [comment]
> I am creating three exoplayer instances and runs in Multi-thread.

ExoPlayer only supports running on a single thread. If you need access to data from another thread, you'd need to forward the call to the same thread ExoPlayer is running one. The exception you see is simply the symptom of using a class on multiple threads that was only designed to be used on a single thread.

> So I add synchronized for all eventTimes and listeners operated by Multi-thread In AnalyticsCollector.
Is there any risk in making this modification?

It might remove the exceptions, but it's not necessarily correct because callbacks may be called on unexpected threads, events may get out of order or a thread may be blocked for too long waiting for an operation on another thread.
