### ISSUE TITLE
show frame freeze/ black screen , instead of pixelations.

### ISSUE THREAD

**Issue by amit12kumardish** [androidx/media#1660]
In ExoPlayer, my input stream is pixelated , causing the player to display those pixelations. Instead of showing pixelated frames, I want the player to either freeze on the last frame or display a black screen when pixelation occurs.

**Issue**: The input stream is pixelated, possibly due to packet loss, leading to the player displaying distorted or pixelated frames.

**Impact**: The pixelated frames disrupt the viewing experience and can be visually jarring for the user.

**Objective**: Implement a solution where the player either:
Freezes on the last known good frame.
Displays a black screen instead of showing pixelated frames.

**Comment by amit12kumardish** [comment]
thanks in advance,

**Comment by tonihei** [comment]
I agree with the sentiment that it might be better to show an error message instead of pixelated or distorted output. However, the output of the video decoder is completely transparent to the library and we have no way to inspect or verify its correctness. What you are asking for would need to be solved by however is implementing the actual codec I believe. If you know which codec produces the output (see ExoPlayer `EventLogger` output), you may try to report it to the codec producer, but unfortunately our library can't do anything about it.
