### ISSUE TITLE
SampleQueueMappingException when loading HLS video

### ISSUE THREAD

**Issue by JonWatson** [androidx/media#1675]
### Version

Media3 main branch

### More version details

Issue occurs on all recent versions(1.3.0 and up were tested)

### Devices that reproduce the issue

Pixel 7 (14) 
Nvidia Shield (11)

### Devices that do not reproduce the issue

None

### Reproducible in the demo app?

Different error in Demo App

### Reproduction steps

In the Demo app, I get an `UnrecognizedInputFormatException` for this HLS manifest.  In my implementation, I get the `SampleQueueMappingException`.  In both apps, other m3u8's play correctly.

I have no doubt there is something that Media3 doesn't like about the manifest.  However, AVPlayer(iOS) plays it without error and it's my job to figure out exactly what the problem is with the manifest and how we can get it working on Android/ExoPlayer

Manifest: https://shorturl.at/Yq1kr

Demo app can be reproduced by adding this to the `media.exolist.json`

    "samples": [
      {
        "name": "HLS Test Stream SampleQueueMappingException",
        "uri": "https://shorturl.at/Yq1kr"
      },

Can you please help us figure out what exactly the problem is with this manifest and why ExoPlayer doesn't like it?  We have the ability to ask the Video Encoding team to help fix the manifests, if we just knew what the problem is.  This is a DRM-protected asset, but I believe the problem can be debugged without the need for DRM keys.

Also please note that the URL that I'm providing is only good for about 72 hours.  I will immediately reply to updates here with a new Manifest URL if someone can take a look and the manifest is no longer available.

### Expected result

Successful HLS playback

### Actual result

My (HlsMediaSource.Factory) implementation:

androidx.media3.exoplayer.hls.SampleQueueMappingException: Unable to bind a sample queue to TrackGroup with MIME type video/avc.

Demo app: UnrecognizedInputFormatException

### Media

https://shorturl.at/Yq1kr

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tianyif** [comment]
Hi @JonWatson,

Looking at your manifest, I saw `EXT-X-KEY:METHOD=SAMPLE-AES`, however this is not currently supported. Please referring to https://developer.android.com/media/media3/exoplayer/supported-formats#hls ("Content protection" section). As a result for that, the `DefaultTsPlayloadReaderFactory` will not recognize the "streamType" of `0xDB` (ITU-T Rec. H.264 and ISO/IEC 14496-10 with AES-128-CBC slice encryption in a packetized stream) nor `0xCF` (ITU-T Rec. H.264 and ISO/IEC 14496-10 with AES-128-CBC slice encryption in a packetized stream) and create payload readers for those streams, thus no sample queues can be created.

In terms of the `UnrecognizedInputFormatException` in demo app, I think it is just due to the usage of the shortened url. We are using `DefaultMediaSourceFactory`, where the content type was [inferred](https://github.com/androidx/media/blob/release/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/source/DefaultMediaSourceFactory.java#L471) from the uri. The shortened uri doesn't content `.m3u8` extension, then it won't be treated as an HLS stream.

Hope the above helps!
