### ISSUE TITLE
How to enable preloading of ads?

### ISSUE THREAD

**Issue by AdityaSinghShekhawat** [androidx/media#1679]
Hey, we are updating Exoplayer to media3 exoplayer `1.3.1`. For ads we are using Exoplayer IMA extension. Is there any way to set preloading of ads? Previosly, we were using `onAdsManagerLoaded` to get ads manager and set `adsRenderingSettings.setEnablePreloading`.  Now,  `onAdsManagerLoaded` callback is never getting triggered ([Ref](https://github.com/google/ExoPlayer/issues/9453#issuecomment-924865612)). I have gone through `ImaAdsLoader` [file](https://github.com/google/ExoPlayer/blob/release-v2/extensions/ima/src/main/java/com/google/android/exoplayer2/ext/ima/ImaAdsLoader.java) and found other `AdsRenderingSettings` like `setBitrateKbps` and `setLoadVideoTimeout` but no `setEnablePreloading`.  Is there a way to enable preloading of ads?, as this would be helpful in seemless transition between video content and ads.

**Comment by marcbaechinger** [comment]
Thanks for your question. 

Can you explain a bit what preloading you expect when playing ads and what measured latency that would improve? 

I'm asking because ExoPlayer already preloads ads. For instance when playing from the content into the ad period, then an ad is alreeady preloaded. Similarly, when an ad ends without being skipped, the content following the add is preloaded as well.

Please bear with me regarding not knowing the ad SDK API. Can you instead of the API calls, let me know what latency you measured and how you expect this to be improved?

**Comment by AdityaSinghShekhawat** [comment]
Thanks for the reply @marcbaechinger.

After some digging I found out that in androidx media3 Exoplayer IMA extension preloading is set by [default](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/preload#:~:text=When%20integrated%2C%20the%20ExoPlayer%2DIMA%20extension%20has%20preloading%20enabled%20by%20default%20and%20includes%20built%2Din%20preloading%20support.). Earlier we need to set `setEnablePreloading` to true.

Closing this ticket.

**Comment by AdityaSinghShekhawat** [comment]
Closing this ticket.
