### ISSUE TITLE
androidx.collection:collection for CircularIntArray when using media3 in an external plugin

### ISSUE THREAD

**Issue by Ste-RH** [androidx/media#1686]
Hi all.

I work on the Unity plugin AVPro Video.  We are looking to upgrade our plugin from using media 3 v1.1.0 to the latest v1.4.1 (and beyond in the future).

I have stumbled upon an issue that the latest release requires androidx.collection:collection for CircularIntArray.

The use case is that AVPro Video is a Unity plugin that uses media3 (ExoPlayer) implemented in a java/cpp plugin.  The need for CircularIntArray means that users will have to override a Unity build gradle file for every project that uses AVPro Video to add to the dependencies.  This is not a heavy-weight task, but a step we do not really want to ask every user of the plugin to perform as we will likely be inundated with 'the plugin is not working on Android' issues every hour of the day!

The only solution I can think of is to bundle the library with AVPro Video alongside media3.  This opens up multiple-use and version conflicts though (similar to guava we have already).

Am I missing/overlooking an obvious fix?

Thanks!

**Comment by icbaker** [comment]
I'm not sure I fully understand the problem you're describing, and why media3 1.1.0 is OK but 1.4.0 is problematic.

At 1.1.0, the `lib-exoplayer` module [depends on](https://github.com/androidx/media/blob/1.1.0/libraries/exoplayer/build.gradle#L45) `androidx.core:core:1.8.0` ([version from `constants.gradle`](https://github.com/androidx/media/blob/1.1.0/constants.gradle#L47)).

Looking at the output of `./gradlew :lib-exoplayer:dependencies` you can see that `androidx.core:core:1.8.0` depends on `androidx.collection:collection:1.0.0` [1]. You can confirm this by looking at the `gradle-module-metadata` file from the [`androidx.core:core:1.8.0` release](https://maven.google.com/web/index.html?q=androidx.cor#androidx.core:core:1.8.0):

```
{
  "group": "androidx.collection",
  "module": "collection",
  "version": {
    "requires": "1.0.0"
  }
},
```

So the dependency on `androidx.collection:collection` is already (transitively) present at 1.1.0.

The only differences I can see between media3 1.1.0 and 1.4.0 is that we now:
1. Directly depend on `androidx.collection:collection` instead of transitively
2. We depend on `androidx.collection:collection:1.2.0` instead of `androidx.collection:collection:1.0.0`

If you're using our prebuilt artifacts, then (1) shouldn't make a difference (because from your perspective the dependency is still transitive via us, and the number of transitive hops is surely not relevant).

Please could you add a bit more info about why media3 1.1.0 is OK but 1.4.0 is problematic for you?

[1]
```
releaseRuntimeClasspath - Resolved configuration for runtime for variant: release
....
\--- androidx.core:core:1.8.0
     +--- androidx.annotation:annotation:1.2.0 -> 1.3.0
     +--- androidx.annotation:annotation-experimental:1.1.0 -> 1.2.0
     +--- androidx.collection:collection:1.0.0
     |    \--- androidx.annotation:annotation:1.0.0 -> 1.3.0
     +--- androidx.concurrent:concurrent-futures:1.0.0
     |    +--- com.google.guava:listenablefuture:1.0 -> 9999.0-empty-to-avoid-conflict-with-guava
     |    \--- androidx.annotation:annotation:1.1.0 -> 1.3.0
     +--- androidx.lifecycle:lifecycle-runtime:2.3.1
     |    +--- androidx.arch.core:core-runtime:2.1.0
     |    |    +--- androidx.annotation:annotation:1.1.0 -> 1.3.0
     |    |    \--- androidx.arch.core:core-common:2.1.0
     |    |         \--- androidx.annotation:annotation:1.1.0 -> 1.3.0
     |    +--- androidx.lifecycle:lifecycle-common:2.3.1
     |    |    \--- androidx.annotation:annotation:1.1.0 -> 1.3.0
     |    +--- androidx.arch.core:core-common:2.1.0 (*)
     |    \--- androidx.annotation:annotation:1.1.0 -> 1.3.0
     \--- androidx.versionedparcelable:versionedparcelable:1.1.1
          +--- androidx.annotation:annotation:1.1.0 -> 1.3.0
          \--- androidx.collection:collection:1.0.0 (*)
```

**Comment by icbaker** [comment]
> no exception due to missing CircularIntArray

Is this exception happening at runtime?

Hypothesis: The `androidx.collection` dependency is also "required" at 1.1.0, but we (or you in your testing) just didn't exercise any code that needed it. This is basically luck that we didn't call any code in `androidx.core` that relied on it. Now that it is required on a critical path in the exoplayer library, it's more obvious that the dependency is missing.

If this hypothesis is correct then I don't think reverting back to the media3 1.1.0 situation is the right fix here - I think you should fix your distribution to ensure that all the libraries that we declare are (transitively) required at runtime are actually available at runtime - otherwise you're likely to see more errors like this in future, and sometimes they will occur on untested paths (and therefore only show up in production).

**Comment by Ste-RH** [comment]
Yes, only at runtime.

I think you are 100% correct.  So how can we pull in all required libs?

If we include them all as jar/aar files with the plugin, then there will without a doubt be many people raising issues with us when the libs are loaded/used/etc by other plugins or even maybe Unity itself using them.

As outlined initially, the other way is to list them all in the dependency section of an overridden main gradle template (setup per Unity project).  This is a fair inconvenience for every user on our plugin and will itself cause a big increase in 'issues' reported.

Is there a third way I am missing?!

**Comment by icbaker** [comment]
> So how can we pull in all required libs?

I think this question is a bit out of scope for this issue tracker.

Gradle implements this sort of transitive dependency resolution for you (including respecting version constraints etc), so this "just works" for an Android project depending on us from Gradle. I'm afraid we don't have the expertise to help you get this working in your slightly custom build set-up. I would recommend trying to re-use the Gradle logic in one way or another though, rather than trying to re-implement it, because I think choosing the right version of each dependency (and choosing where to download it from) is quite fiddly to get right.

**Comment by Ste-RH** [comment]
I hear ya...and thanks for your input on my question.  Much appreciated.

One last final question if I may...

I think we are going to have to shuffle around how we signal media3's use in AVPro Video.  Instead of compiling and copying around the media3 libs, I think we might as well just flag the libs as dependencies in every Unity project that uses AVPro Video.  This should pull in media3 libs we list - and also should pull in all the dependencies media3 libs use, yeah?  I mean...if we are having to interject into the Unity Android build process for dependencies, we might as well just do it at the core set of libs!

**Comment by icbaker** [comment]
> This should pull in media3 libs we list - and also should pull in all the dependencies media3 libs use, yeah?

I'd assume so, but hard to say for sure because I'm not familiar with how unity manages dependencies.

**Comment by Ste-RH** [comment]
Thought I would just crack on and try to test the theory...but getting guava headaches.  Can you point me in the right direction?  Current dependencies are:

![image](https://github.com/user-attachments/assets/683f00af-a282-4f5c-83f4-bac6f6b28c6e)

...and the build failure is:

![image](https://github.com/user-attachments/assets/6fbb58ad-945f-42cc-948d-ad86dc4a7429)

**Comment by icbaker** [comment]
Not sure I'm afraid. A bit of naive searching turns up this SO answer from a googler that works on Guava (Chris Povirk): https://stackoverflow.com/a/77746619

Might be worth a try (or the answer below that seems to be in-line under the `implementation` declaration)?

**Comment by Ste-RH** [comment]
Yeah, also turned up similar: https://stackoverflow.com/questions/78197256/resolving-guava-dependency-when-using-gradle-8-5-to-download-an-android-package

Guess I will just have to work out how to get that set in the gradle template Unity spits out.  Thanks for your help...much appreciated.

**Comment by Ste-RH** [comment]
To round this off.  It appears the magic sauce here is to add the following to the mainTemplate.gradle Unity produces for you to edit:

![image](https://github.com/user-attachments/assets/b672ec8c-56ca-49e5-a67d-405d95cfdf25)

...as outlined [here](https://github.com/google/guava/releases/tag/v32.1.0).

Thanks again for your help.  Closing this one now.
