### ISSUE TITLE
Disable seek in app notification but enable it for android auto companion app

### ISSUE THREAD

**Issue by Flyktsodan** [androidx/media#1727]
We want to disable seeking in the regular media notification for our app so I've added a check in 

`override fun onConnect(session: MediaSession, controller: MediaSession.ControllerInfo): MediaSession.ConnectionResult {  
`
that disables it:

```
val playerCommands = if (session.isMediaNotificationController(controller)) {
    connectionResult.availablePlayerCommands.buildUpon()
        .remove(Player.COMMAND_SEEK_IN_CURRENT_MEDIA_ITEM) // Disable seek scrubbing in the timeline
```
The problem is that this will also disable seeking when using the android auto companion app. Doesn't make sense to me since that is a completely different controller but the UI removes the functionality to drag the seekbar. Seems like android auto builds its UI based on the mediaNotificationController playerCommands rather than the autoCompanionController?

**Comment by marcbaechinger** [comment]
Android Auto, Automotive OS and System UI are all using the legacy `MediaControllerCompat` API. Such controller don't connect to the Media3 session directly, but instead read from the platform `android.media.session.MediaSession`. Unlike the more modern Media3 session, the legacy platform session provides only one single `PlaybackState` that is delivered to the any controller as the very same instance.

So the problem you are seeing was the state of the art apps can do with the legacy library. Unless these clients are not migrating to the Media3 session library, all legacy controller will get the same available commands. In the Media3 world, the media notification controller is used as a proxy for the legacy session, because the media notification is the most prominent use case that is reading from the platform session.

I'm sorry for not being able to give you a better answer than as long as these clients are using the legacy library, Media3 can't really do something to change this.

While Media3 intents to improve this situation, we can't change something for clients that haven't yet moved to the Media3 library. I know that Automotive OS people have started looking into migrating, but I'm not well informed enough to tell whether and when this happens and what this would mean regarding roll out to OEM devices.

**Comment by Flyktsodan** [comment]
Thanks for the reply, with your reply in mind I came up with a workaround where "Seeking" is enabled if android auto is connected. Downside is that the notification will also allow seeking but people show hopefully not fiddle with their phone when connected to android auto. 


```
 override fun onPostConnect(session: MediaSession, controller: MediaSession.ControllerInfo) {
        Timber.d("onPostConnect controllerVersion: ${controller.controllerVersion}")
        val isAndroidAutoConnected = session.connectedControllers.find { it.packageName == ANDROID_AUTO_PACKAGE_NAME } != null

        // If we are connected to android auto we want to enable seeking
        if (isAndroidAutoConnected) {
            // Find the MediaNotificationController and set Player.Commands where scrubbing is enabled.
            val mediaNotificationController = session.connectedControllers.find { session.isMediaNotificationController(it) }
            if (mediaNotificationController != null) {
                // Since Android Auto still use MediaControllerCompat all controllers will get the same Player.Commands.
                // This is a workaround to enable seeking when connected to Android auto.
                session.setAvailableCommands(
                    mediaNotificationController,
                    DEFAULT_SESSION_AND_LIBRARY_COMMANDS,
                    DEFAULT_PLAYER_COMMANDS.buildWithoutSeek(isScrubbingEnabled = true),
                )
            }
        }

        if (controller.controllerVersion != 0) {
            // Let Media3 controller (for instance the MediaNotificationProvider) know about the custom
            // layout right after it connected.
            session.setCustomLayout(controller, audioPlayerService.customCommands)
        }
    }

    private fun Player.Commands.buildWithoutSeek(isScrubbingEnabled: Boolean): Player.Commands {
        val builder = this.buildUpon()
        if (!isScrubbingEnabled) {
            builder.remove(Player.COMMAND_SEEK_IN_CURRENT_MEDIA_ITEM) // Disable seek scrubbing in the timeline
        }
        builder.remove(Player.COMMAND_SEEK_TO_NEXT)
        builder.remove(Player.COMMAND_SEEK_TO_PREVIOUS) // Disable seeking back to the beginning
        builder.remove(Player.COMMAND_GET_TIMELINE) // Removes the queue button in Android Auto
        return builder.build()
    }
```

**Comment by Flyktsodan** [comment]
Thanks for the reply. I guess we can work around this by updating the Player.Commands for the Media notification controller when Android auto is connected (even though it will be messy).

**Comment by Flyktsodan** [comment]
Closing since now I know why it happens.
