### ISSUE TITLE
Removing player commands behaviour on Android14 vs Android12/10

### ISSUE THREAD

**Issue by abouda** [androidx/media#1735]
Using this code snippet from the docs:
https://developer.android.com/media/media3/session/background-playback#media-notification-controller
I am trying to remove the seek to previous button from the notification while adding custom seek commands.
```
                .remove(Player.COMMAND_SEEK_TO_NEXT)
                .remove(Player.COMMAND_SEEK_TO_NEXT_MEDIA_ITEM)
                .remove(Player.COMMAND_SEEK_TO_PREVIOUS)
                .remove(Player.COMMAND_SEEK_TO_PREVIOUS_MEDIA_ITEM)
```

It works fine on android 14:

![image](https://github.com/user-attachments/assets/8ff86293-369f-46c3-834f-dd27bdd5b6b3)

But on Android 12 and 10, the skip back button is still there:

![image](https://github.com/user-attachments/assets/25b2139c-36a5-485e-a4ed-10982a715cdd)

I also tried removing the skip commands in the ForwardingPlayer. The button is removed from the notification but the custom commands are not placed correctly on android 12/10.

![image](https://github.com/user-attachments/assets/8a51b18d-34f9-4722-ab3c-cd6652d8e372)

Note that removing `.remove(Player.COMMAND_SEEK_IN_CURRENT_MEDIA_ITEM) // Disable seek scrubbing in the timeline` works fine on all tested android versions.

**Comment by tianyif** [comment]
Hi @abouda,

Before Android 13, the notification actions and buttons are populated by the `MediaNotification` provided by the [`MediaNotification.Provider`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaNotification.java#L154). We have a default implementation [`DefaultMediaNotificationProvider`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/DefaultMediaNotificationProvider.java). In the default logic, the buttons are derived from the [`player.getAvailableCommands()`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/DefaultMediaNotificationProvider.java#L328), so that's why removing the skip commands works, but you may want to customize the placement by extending the `DefaultMediaNotificationProvider` and implement the [`addNotificationActions`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/DefaultMediaNotificationProvider.java#L533) method. 

From Android 13 onwards, the notification actions are directly derived from the `Player` state from the session, so that's why you see there is a behavior difference on Android 14.
