### ISSUE TITLE
Design Choice for Exoplayer Download Manager

### ISSUE THREAD

**Issue by Amud** [androidx/media#1767]
Hi,  
I noticed ExoPlayer uses an end-to-end implementation of a custom Download Manager instead of Android's built-in Download Manager. Could you highlight the design choices behind this decision? Were there specific performance, limitations or flexibility considerations involved?

Thanks.

**Comment by icbaker** [comment]
> Android's built-in Download Manager

are you referring to https://developer.android.com/reference/android/app/DownloadManager?

It looks like that operates on URIs, and just downloads the content the URI points to - whereas although ExoPlayer's `DownloadManager` also basically operates on URIs, it doesn't always **only** download the content of that URI. This might be more clear if you consider a DASH or HLS stream, where the URI points to manifest/playlist. Therefore in order to download the "media" ExoPlayer has to parse the manifest(s) and use it to decide which media files to download.

So I guess the answer is: Because `android.app.DownloadManager` doesn't really work well for the more complex downloading use-cases that ExoPlayer can handle.
