### ISSUE TITLE
Green and pixelated screen when reproducing m3u8 video

### ISSUE THREAD

**Issue by emenjivar** [androidx/media#178]
### Media3 Version

1.0.0-alpha03

### Devices that reproduce the issue

* Pixel 3 API 30 (emulator)
* Pixel 4 API 30 (emulator)
* Pixel 3 API 32 (emulator)
* AX1078 Android 10 (physical device)

### Reproducible in the demo app?

Yes

### Reproduction steps

1. Play the video provided on this issue

### Expected result

The media plays successfully

### Actual result

The video is playing lagged, pixelated and displaying a green screen

https://user-images.githubusercontent.com/19592284/193645448-5b5fb319-e954-41de-ac17-3c84d02cf893.mp4

<img width="443" alt="Screen Shot 2022-10-03 at 11 51 36 AM" src="https://user-images.githubusercontent.com/19592284/193644966-e99c3339-8cfa-4985-a8a7-8ea669cfb7a2.png">

### Media

https://storage.googleapis.com/howwefeel.appspot.com/strategies/hwf_ataseia_1/stream_0/stream.m3u8

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
The emulator codec specifically classifies this stream as exceeding its capabilities (see `Track:0, id=0, mimeType=video/avc, codecs=avc1.F40032, res=1080x1920, supported=NO_EXCEEDS_CAPABILITIES` in the logcat of the demo app).

ExoPlayer still attempts to play this stream because it's the only one available in the provided HLS playlist, but there is no guarantee this actually works. I don't have the physical device you tested with (AX1078), but I suspect it's the same problem. If the codec doesn't support this type of stream, then there is not much we can about it (given it's already marked as unsupported).
