### ISSUE TITLE
live video request ignore query parameters

### ISSUE THREAD

**Issue by jimie-chaos** [androidx/media#1812]
### Version

Media3 main branch

### More version details

    implementation("androidx.media3:media3-exoplayer:1.4.1")
    implementation("androidx.media3:media3-ui:1.4.1")
    implementation("androidx.media3:media3-exoplayer-dash:1.4.1")
    implementation("androidx.media3:media3-exoplayer-hls:1.4.1") // hls(m3u8)支持
    implementation("androidx.media3:media3-datasource-okhttp:1.4.1") //
    implementation("androidx.media3:media3-exoplayer-ima:1.4.1")

### Devices that reproduce the issue

Redmi Note 12 Pro android 13

### Reproducible in the demo app?

Yes

### Reproduction steps

PlayerActivy:
~~player.setMediaItems(mediaItems, /* resetPosition= */ !haveStartPosition);~~
```java
player.setMediaItem(MediaItem.fromUri("https://iot.something.cn:9443/rtp/33030300452007000002_33030300451377000002/hls.m3u8?sign=f9051de85973951fcd3c2decf667103e"));
```

### Expected result

success

### Actual result

request:
1. https://iot.something.cn:9443/rtp/33030300452007000002_33030300451377000002/hls.m3u8?sign=f9051de85973951fcd3c2decf667103e
2. https://iot.something.cn:9443/rtp/330303004
52007000002_33030300451377000002/hls.m3u8?sign=f9051de85973951fcd3c2decf667103e
3. https://iot.something.cn:9443/rtp/33030300452007000002_33030300451377000002/2024-10-18/09/51-52_287.ts
throw androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 401
3 lost auth params

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
Are the URLs you provided meant to resolve, or are they just placeholders? They don't load for me (I also tried VPNing to China based on the ccTLD).

The report sounds similar to https://github.com/androidx/media/issues/1671 but without access to playlist I can't determine if it is using the `QUERYPARAM` HLS config (see that issue for more details).

Either:
1. The playlist is using `QUERYPARAM` config, and this is an enhancement request for ExoPlayer to support this config.
2. The playlist is not using `QUERYPARAM`, so that would need to be fixed before ExoPlayer's lack of support matters.

Please let us know whether this is case (1) or (2). If it's case (1), please provide a copy of the HLS playlist. Please either upload it here or send it to android-media-github@google.com with the subject `Issue #1812`. Please also update this issue to indicate you’ve done this.

**Comment by jimie-chaos** [comment]
Thank you for your attention.
this is hls link ,date limit is 24 hour
https://iot.moshme.cn:9443/rtp/33030300452007000002_33030300451377000002/hls.m3u8?type=user&code=f9051de85973951fcd3c2decf667103e&token=386b54dd-f984-4f06-92c8-6e9d87feb125
this is maybe (1）.because the link must add
`type=user&code=f9051de85973951fcd3c2decf667103e&token=386b54dd-f984-4f06-92c8-6e9d87feb125
`.
if you need long effective link,please let me know.

Ian Baker ***@***.***> 于2024年10月18日周五 16:34写道：
