### ISSUE TITLE
user MergingMediaSource but Legacy decoding is disabled

### ISSUE THREAD

**Issue by qazxcs113** [androidx/media#1824]
### Version

Media3 main branch

### Devices that reproduce the issue

piexel6

### Reproducible in the demo app?

Not tested

### Reproduction steps

1. use HlsMediaSource ,and use MediaItem.Builder().setSubtitleConfigurations.
just player.setMediaSource(mergedSource). it not subtitle. but DefaultFactory.create, ok.
2.1.4.1 ，I use SingleSampleMediaSource to other load my subtitle.but error 1004 and have this.
Caused by: java.lang.IllegalStateException: Legacy decoding is disabled, can't handle application/x-subrip samples (expected application/x-media3-cues).
3.I must user hlsSource , so what i can do?

### Expected result

 error 1004

### Actual result

Caused by: java.lang.IllegalStateException: Legacy decoding is disabled, can't handle application/x-subrip samples (expected application/x-media3-cues)

### Media

xxx

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
The problem is not `MergingMediaSource`, it's `SingleSampleMediaSource`. You either need to switch to `DefaultMediaSourceFactory` (which will do the merging of subtitles for you and supports HLS), or instantiate your own `ProgressiveMediaSource` for subtitles like we do in `DefaultMediaSourceFactory` - see https://github.com/androidx/media/issues/1569#issuecomment-2255506625 for more info.
