### ISSUE TITLE
Display multiple subtitles

### ISSUE THREAD

**Issue by ValentinPostindustria** [androidx/media#1850]
I develop the application for learning languages by watching movies with two subtitles (original at the top and translated at the bottom). So I need to show 2 different subtitles on the screen at once. 
I tried to override the selection, but the selected subtitle can be only one, and both subtitle views show the same text. Maybe it's possible to select two subtitles at once? 

What can I do in this situation? Maybe it's possible to get different cues for different subtitle views? 
```kotlin
            override fun onCues(cueGroup: CueGroup) {
                super.onCues(cueGroup)
                subtitleView.setCues(cueGroup.cues)
            }
```

Or maybe I can somehow get all the subtitle texts and timings from embedded into video subtitles? I will handle displaying by myself then.

**Comment by icbaker** [comment]
ExoPlayer maps tracks (or track groups) to renderers. In the example you've outlined, each text track will be a separate track group (because they have different content - see more here: https://developer.android.com/media/media3/exoplayer/track-selection#querying-available). By default, ExoPlayer only constructs a single `TextRenderer` instance, so can only select a single text track group at once.

You can customize this behaviour to construct multiple `TextRenderer` instances instead. There's more discussion on this topic in these issues:
* https://github.com/androidx/media/issues/1473
* https://github.com/google/ExoPlayer/issues/9876#issuecomment-1017646244

Please have a read through those, and try it out, and let us know if you have any follow-up questions.
