### ISSUE TITLE
Live DAI DASH streaming freezing with multi periods and no closed caption Ad.

### ISSUE THREAD

**Issue by linhai326** [androidx/media#1863]
### Version

Media3 1.4.0 and beyond.

### More version details

**Issue doesn't happen in 1.3.1. and before**

### Devices that reproduce the issue

issue can be reproduced on all Android devices we tested: amazon FireTV stick 4K, for example.

### Reproducible in the demo app?

Yes

### Reproduction steps

- Launch exoplayer demo app
- choose the test content (sent email to android-media-github@google.com)
- Turn on CC: Click "SELECT TRACKS" --> TEXT --> "Unknown"
- Streaming for a couple of minutes
- 
### Expected result

Stream should play without issue

### Actual result

streaming will be freezing in a couple of minutes.

### Media

will send content in email.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by linhai326** [comment]
We believe this bug was introduced in 1.4.0 when removing "IsDecodeOnly" commits:

https://github.com/androidx/media/commit/0f42dd47526c70e38b1048bb18c994c281800485
https://github.com/androidx/media/commit/6e0f8e3b0d251a06a6af8d03204db2ba0dfd6464

Particularly, it seems this is the bug, in CeaDecoder.java, line 88:

`  public void queueInputBuffer(SubtitleInputBuffer inputBuffer) throws SubtitleDecoderException {
    Assertions.checkArgument(inputBuffer == dequeuedInputBuffer);
    CeaInputBuffer ceaInputBuffer = (CeaInputBuffer) inputBuffer;
    if (outputStartTimeUs != C.TIME_UNSET && ceaInputBuffer.timeUs < outputStartTimeUs) {
      // We can start decoding anywhere in CEA formats, so discarding on the input side is fine.
      releaseInputBuffer(ceaInputBuffer);
    } else {
      ceaInputBuffer.queuedInputBufferCount = queuedInputBufferCount++;
      queuedInputBuffers.add(ceaInputBuffer);
    }
    dequeuedInputBuffer = null;
  }`

there seems should be a check for ceaInputBuffer.timeUs != C.TIME_END_OF_SOURCE when releasing the ceaInputBuffer.
Without this check, the playback could be stuck due to the text render is keeping waiting for end of source.

**Comment by linhai326** [comment]
any update?

**Comment by icbaker** [comment]
I think I was able to repro the issue using the media links provided over email. I then added a single log line and went to retry, and now the content is consistently 503ing.

Could you please check to make sure the content is still accessible?

**Comment by icbaker** [comment]
The fix for the `CeaDecoder` is submitted and linked above.

I also investigated the garbled captions. The problem is due to your MP4 container marking **every** video sample as a keyframe, meaning that we flush our reordering queue of CEA-608 samples here on **every sample** (which means it can't re-order anything): 
https://github.com/androidx/media/blob/19b38c83b6ce1d13effc08da834cc8ff284cb969/libraries/extractor/src/main/java/androidx/media3/extractor/mp4/FragmentedMp4Extractor.java#L1650-L1652

This MP4 metadata is inconsistent with the H.264 bytes contained in each sample (not every H.264 sample is a keyframe). 

If I change the `if` condition to just `(trackBundle.getCurrentSampleFlags() & C.BUFFER_FLAG_END_OF_STREAM) != 0` then the subtitles become un-garbled (because the queue is able to correctly re-order the out-of-order samples). However, I'm not sure this is a correct change in general (we should be able to rely on flushing our queue on each keyframe, and we should be able to rely on the MP4 keyframe metadata being correct).

This seems to be an issue with your content muxing, rather than with ExoPlayer's logic - I suggest you report it to whoever is producing your content.

**Comment by linhai326** [comment]
@icbaker 
Thanks a lot for looking into this issue. 
We will check with our content provider!!

**Comment by icbaker** [comment]
We discussed as a team and decided the benefit of relying on the MP4 sync sample metadata for flushing is marginal, and the result of poor behaviour on malformed media like this is quite catastrophic - so we decided to remove the assumption that MP4 sync sample metadata is correct for this use-case (re-ordering SEI CEA-608 samples) - see the change linked above.
