### ISSUE TITLE
How does Android Auto pagination work with media3?

### ISSUE THREAD

**Issue by gookman** [androidx/media#189]
So as the tittle says, I'm looking for information about how pagination works in Android Auto and media3. I haven't been able to find documentation on the topic so maybe someone from the team can answer directly. 

I currently have a `MediaService` that extends `MediaLibraryService` and implements all the methods needed by Android Auto to fetch data
```
class MediaService : MediaLibraryService() {
    // extra code here 

    override fun onGetLibraryRoot(
        session: MediaLibrarySession, 
        browser: ControllerInfo, 
        params: LibraryParams?
    ): ListenableFuture<LibraryResult<MediaItem>> {
        // get root here
    }

    override fun onGetItem(
        session: MediaLibrarySession,
        browser: ControllerInfo,
        mediaId: String
    ): ListenableFuture<LibraryResult<MediaItem>> {
        // get item with id
    }

    override fun onGetChildren(
        session: MediaLibrarySession,
        browser: ControllerInfo,
        parentId: String,
        page: Int,
        pageSize: Int,
        params: LibraryParams?
    ): ListenableFuture<LibraryResult<ImmutableList<MediaItem>>> {
        // get children of item with id
    }

    // extra code here
}
```

I can see that `onGetChildren` has both `page` and `pageSize` attributes, but when testing (with the desktop head unit) these values are always `0` and `Int.MAX_VALUE`. I have looked into the source code and see that this is all handled in `MediaLibraryServiceLegacyStub` and these arguments are retrieved with `MediaBrowserCompat.EXTRA_PAGE` and `MediaBrowserCompat.EXTRA_PAGE_SIZE`. It looks like in my case in `onLoadChildren` the `options` argument is always null. I'm not sure where these options are coming from.

So my question is where are `page` and `pageSize` coming from and how can they be controlled (if they can be controlled)? Is this something that Android Auto decides? Is there some configuration option that I am missing?

**Comment by marcbaechinger** [comment]
Yes, you are correct that these `options` are coming from the client app that is using `MediaBrowserCompat`.

As a such, Android Auto is using a `MediaBrowserCompat` that subscribes to a `parentId` that eventually calls  `onLoadChildren` of the legacy `MediaBrowserServiceCompat` that is then mapped to `onGetChildren()` of `MediaLibraryService`. If the options a `null` I _think_  that Android Auto is using the [`subscribe` method](https://developer.android.com/reference/android/support/v4/media/MediaBrowserCompat#subscribe(java.lang.String,android.support.v4.media.MediaBrowserCompat.SubscriptionCallback)) without a `Bundle`. 

I'm not sure how you are testing this. I'm wondering because it may depend on the actual version of Android Auto that is accessing your app. Can you give me some more details about this? When I test with an Emulator with API 29, then I can confirm your findings that the options are `null`.

We have a test case for Media3 that [asserts whether the pagination extras arrive](https://github.com/androidx/media/blob/release/libraries/test_session_current/src/androidTest/java/androidx/media3/session/MediaBrowserCompatWithMediaLibraryServiceTest.java#L283) in the `MediaLibraryService` when sent by a client.

From this I would say if you see what you reported, then Android Auto is not sending any pagination options.

**Comment by gookman** [comment]
Thanks for the quick reply! So for testing I am using the `Android Auto Desktop Head Unit v2.0` with a Samsung S22 (Android 12) that has `Android Auto v8.1.626474`. The Media3 version is `1.0.0-beta02`.

I did a bit more digging and from what I can see `MediaBrowserServiceCompat` is receiving a message `CLIENT_MSG_ADD_SUBSCRIPTION` where we are expecting some options (`DATA_OPTIONS`) and in my case these are indeed null.

So if I understand this correctly the Android Auto app decides how pagination is handled and we do not have control over these values. If that is the case it's a bit unfortunate but at least I know I should handle this situation. 

Since for Media3 there are tests for pagination extras does it mean that this is a bug? Is it guaranteed that Android Auto will send pagination extras?

**Comment by gookman** [comment]
All right! I think I have gotten all my questions answered. Thank you! I will close the issue.
