### ISSUE TITLE
DTS-HD Support

### ISSUE THREAD

**Issue by NineKain** [androidx/media#1896]
Before filing a feature request:
-----------------------
- Search existing open issues, specifically with the label ‘enhancement’:
  https://github.com/androidx/media/labels/enhancement
- For ExoPlayer-related feature requests, please also check for existing feature
  requests on the ExoPlayer tracker:
  https://github.com/google/ExoPlayer/labels/enhancement
- Search existing pull requests:
    - On this tracker: https://github.com/androidx/media/pulls,
    - On the ExoPlayer tracker: https://github.com/google/ExoPlayer/pulls

When filing a feature request:
-----------------------
Replace the content in the sections below.

### [REQUIRED] Use case description
I'd like DTS-HD support, audio sounds strange on my Android TV without it.
### Proposed solution
Implement DTS-HD, even DTS-X for better audio support

### Alternatives considered
VLC, Just Player, lots of other players support this with no issues.

**Comment by icbaker** [comment]
ExoPlayer generally relies on decoders provided by the device, so DTS-HD support is down to whether the device supports it or not (and not all Android (TV) devices are required to support it). I believe that when a device supports decoding DTS-HD, playback of such content should work with ExoPlayer.

You may be able to use the [FFmpeg extension](https://github.com/androidx/media/tree/release/libraries/decoder_ffmpeg) to decode DTS-HD if it's not supported by your device, but I don't know if FFmpeg supports decoding DTS-HD.

I'm going to close this issue, because it isn't really a feature request for ExoPlayer, since we don't maintain media decoder implementations in this library.
