### ISSUE TITLE
Request to Upgrade Media3 IMA SDK Dependency to v3.34.0+ in Future Media3 Releases

### ISSUE THREAD

**Issue by amitpremi-zee** [androidx/media#1927]
In our Android app, we are using Media3 v1.3.1 with the IMA SDK extension. 
Recently, we attempted to upgrade to Media3 v1.4.1, which includes IMA SDK v3.33.0. However, after the upgrade, we observed an issue where two instances of our app were being created as soon as the IMA SDK was initialized for video ads.

Upon investigation, we identified the following changes between Media3 v1.3.1 and v1.4.1:

1. IMA SDK was upgraded from v3.31.0 to v3.33.0.
2. In IMA SDK v3.33.0, a change was introduced in the AndroidManifest.xml file at app level with android:taskAffinity="", causing the issue of two app instances.
3. This issue has been addressed by the IMA SDK team in v3.34.0.

Therefore, we kindly request that future Media3 releases (post v1.5.0) include IMA SDK v3.34.0 or later.

We strongly recommend upgrading to the latest available IMA SDK in future Media3 releases to avoid such issues.

Reference snapshot:-
---------------------------------
<img width="808" alt="image" src="https://github.com/user-attachments/assets/9e2b1625-3f32-40b9-a473-a786601ca5a2">

<img width="915" alt="image" src="https://github.com/user-attachments/assets/d4dad044-2690-477b-aa18-985490cdab63">

**Comment by andrewlewis** [comment]
Just for reference, this is related to the eventual root cause you found in #1910.

In the short term, I think you can work around this by adding a explicit dependency on IMA with version 3.35.1 in your app. Gradle should resolve to the higher version number (and in this specific case there shouldn't be any incompatible changes in the IMA SDK).

Media3 1.6 is expected to use that version (or later) when it's released.
