### ISSUE TITLE
Session library: How to handle playback resumption if media file finished playing (player in STATE_ENDED)?

### ISSUE THREAD

**Issue by nift4** [androidx/media#1933]
Normally, when a file is playing, playback state is happily STATE_READY, and at some point, the file ends; the player will change to STATE_ENDED. Then, user presses play button, and media3 seeks to default position to be able to resume playback:
https://github.com/androidx/media/blob/df887a942222914836081f868067960eb0149547/libraries/common/src/main/java/androidx/media3/common/util/Util.java#L3623-L3626
so far so good.

However, in the following scenario, play button will not work:
1. the song is currently ended and player is in STATE_ENDED
2. Android destroys process, calls onDestroy()
3. I save media item list, current media item index and current media item position to disk
4. Later, user presses bluetooth headset play button
5. MediaButtonReceiver gets called
6. service onCreate(), exoplayer created and in STATE_IDLE (no playlist, not playing)
7. media3 calls onPlaybackResumption()
8. I give MediaItemsWithStartPosition (with the exact same values I got from exoplayer earlier!) to SettableFuture
9. media3 calls setMediaItems(), player still in STATE_IDLE
10. media3 handlePlayButtonAction() calls prepare()
11. ExoPlayer moves to STATE_BUFFERING
12. ExoPlayer noticed the playback position is end-of-file, goes to STATE_ENDED
13. media3 calls play()
14. play() is dropped because it's not available in STATE_ENDED

The end result is media not playing. However, expected result would be playing media.

To work around this, I have created a ForwardingPlayer that pretends to be in STATE_ENDED even if ExoPlayer is not until there is a seek event. That exhibits correct behavior, but is hacky. Looking forward to a better solution proposal. Thanks

**Comment by marcbaechinger** [comment]
Thanks for your report. 

> The end result is media not playing. However, expected result would be playing media.

You are at the end of the playlist when the user terminates. Then on playback resumption the user asks for resuming from there. What would you as a user, without any technical background, expect to happen? Then think about how you would technically implement implement this behavor. I think we can deduct from the report:

From your description:

> Then, user presses play button, and media3 seeks to default position to be able to resume playback:

If you accept this as a valid solution in the resumption case as well you can just do this. It sounds like a good solution as this would be what happens when the user presses `play` without playback resumption. Even if there is a termination of the app in between you'd have the same behavior for your user. SGreat to me. 

You would have to detect the `STATE_ENDED`:

```
public void onPlaybackStateChanged(int playbackState) {
   if (playbackState == STATE_ENDED) {
      saveResumptionPosition(player.getCurrrentMediaItemIndex(), C.TIME_UNSET);
   }
}
```

Then when you need to resume playback use these two properties. You can just store `C.TIME_UNSET` because this makes the player start at the default position.

WDYT?
