### ISSUE TITLE
`MediaMetadata.Builder().populateFromMetadata()` miss some fields from `.flac` files 

### ISSUE THREAD

**Issue by cyanChill** [androidx/media#1958]
### Version

Media3 1.5.0

### More version details

I've also encountered the issue when using version 1.4.1.

### Devices that reproduce the issue

- OnePlus 6 running Android 11
- Nothing Phone 2a running Android 14

### Reproducible in the demo app?

Not tested

### Reproduction steps

I went through the route of using `MetadataRetriever` to get the metadata for audio files based on https://developer.android.com/media/media3/exoplayer/retrieving-metadata#wo-playback.
- Basically: MetadataRetriever → TrackGroupArray → TrackGroup → Format → Metadata → MediaMetadata.

A basic summary of what I did is (assume everything is defined):

```kotlin
val mediaItem = MediaItem.fromUri(uri)
val trackGroupArray = MetadataRetriever.retrieveMetadata(context, mediaItem).get()
val format = trackGroupArray[0].getFormat(0)
val metadata = format.metadata
val mediaMetadata = MediaMetadata.Builder().populateFromMetadata(metadata).build()
```

Then I return the fields available such as `artist`, `title`, `trackNumber`, etc..

### Expected result

Accessing the `title`, `artist`, `discNumber`, and `trackNumber` fields on the `MediaMetadata` object should return the respective values.

### Actual result

The `title` & `artist` fields both return the expected strings while `discNumber` & `trackNumber` returns `null`. This only happens when following the process for `.flac` files.

I do know that the vorbis comments for the `discNumber` & `trackNumber` fields are present as running `metadata.toString()` returns:

```
entries=[
  VC: TITLE=One Step Closer,
  VC: TOTALDISCS=1,
  VC: TOTALTRACKS=12,
  VC: ARTIST=Linkin Park,
  VC: DISCNUMBER=1,
  VC: ALBUM=Hybrid Theory,
  VC: GENRE=Alternative,
  VC: GENRE=Metal,
  VC: GENRE=Nu Metal,
  VC: COMMENT=CD, Warner Records 093624893226,
  VC: ALBUMARTIST=Linkin Park,
  VC: DATE=2000,
  VC: TRACKNUMBER=02,
  Picture: mimeType=image/jpeg, description=
]
```

I'm currently working around this problem by using `MediaMetadataRetriever` for `.flac` files instead since it correctly returns the disc & track numbers.

### Media

I'll send the file to the specified email, but I think it affects all `.flac` files.

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
The conversion logic from vorbis comments to `MediaMetadata` is here:

https://github.com/androidx/media/blob/df887a942222914836081f868067960eb0149547/libraries/extractor/src/main/java/androidx/media3/extractor/metadata/flac/VorbisComment.java#L60-L80

Some of the tags mentioned at https://xiph.org/vorbis/doc/v-comment.html are missing from our logic, including `TRACKNUMBER` and `GENRE` - adding those is relatively uncontroversial.

The rest of the 'unrecognized' tags are less clear. It seems there's **a lot** of possible variety out in the wild, both in terms of the key names and the format of their values. Some examples of disc numbering from [this 2009 comment](https://hydrogenaud.io/index.php/topic,69292.msg613808.html#msg613808):

> * `DISC=n`
> * `DISCNUMBER=n`
> * `DISCNUMBER=n/x`
> * `DISC #=n`
> * `DISCC=x`
> * `DISCTOTAL=x`
> * `TOTALDISCS=x`

----

Since `TRACKNUMBER` is one of the 'official' ones, and its description doesn't suggest the `x/y` formatting, it seems reasonable to me to derive that a `TOTALTRACKS` or similar key may also exist, and to follow the same convention for disc numbering. So I'll send a change adding support for:

```
TOTALDISCS
DISCNUMBER
TOTALTRACKS
TRACKNUMBER
```

If we get additional feedback with examples of the `x/y` numbering format, or different key names, we can add support for that too.

**Comment by icbaker** [comment]
Disc and track number & totals (and genre) should now be populated by https://github.com/androidx/media/commit/12546070ee6bb8b41dc7c54714592f330d8794ba
