### ISSUE TITLE
How to show 3 Media buttons (previous/play/next) by default  in notification？

### ISSUE THREAD

**Issue by CallBackMe** [androidx/media#1970]
Hello teacher, I am currently developing below API 33. However, the mini player on the notification bar only shows 2 media buttons (Previous/Play). I expect 3 media buttons to be displayed by default. May I ask how I can achieve this?

![8a99d1e5016e6efc49bbabc4d0212504](https://github.com/user-attachments/assets/fe714b8a-b06c-4ce8-96cd-e63a5b4ba9cc)

Of course, I now rewrite DefaultMediaNotificationProvider, which seems to be possible, but the previous/next button events cannot be monitored. Below is my code, is it the problem I wrote?

![2B791973-D9AA-4236-8736-07E8002BE29A](https://github.com/user-attachments/assets/5dcd3b62-8c28-427e-9da6-92676d2e5729)

I hope the teacher can help answer the above, thank you very much.

**Comment by marcbaechinger** [comment]
Thanks for your question.

We have the following documentation about customizing the notification, which mentions that below API 33 the `MediaNotificationProvider` is used while starting with API 33 the notification is drawn based on the information in the media session.

Because of this I'd recommend to achieve what you are trying by using a custom layout. Media3 then makes sure to replicate the custom layout for APIs below 33 with `DefaultMediaNotificationProvider` and staring from API 33 by converting the custom layout to custom actions in the platform session.

https://developer.android.com/media/media3/session/background-playback#notification
https://developer.android.com/media/implement/surfaces/mobile


> Below is my code, is it the problem I wrote?

I think yes. The [JavaDoc of `DefaultNotificationProvider`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/DefaultMediaNotificationProvider.java#L418-L419) says that you should override `DefaultNotificationProvider.getMediaButtons()` to customize.

However, as mentioned above I'd go with the custom layout approach because you possibly want to keep the notification on API 32 and API 33 about the same so you don't sprise yur users when they upgrade.

Let me know if the documentation leaves questions open, so we can add this.

**Comment by lovegaoshi** [comment]
I suspect its bc ur current mediaItem is the last one in the exoplayer queue. it used to only not show a next button below android 13, but now its like that on all versions.

I use the default media3 MediaSessionService to populate the notification, and you might need a combination of these settings:

1. wrap exoplayer into a forwarding one, [override isCommandAvailable and/or getAvailableCommands](https://github.com/lovegaoshi/react-native-track-player/blob/c032d75d82e8f567e2da2a4c7920264bf56fa5e1/android/src/main/java/com/lovegaoshi/kotlinaudio/player/AudioPlayer.kt#L546), and use the forwarded player when constructing the mediasession;

2. set MediaSession's availablePlayerCommands to [include all commands](https://github.com/lovegaoshi/react-native-track-player/blob/c032d75d82e8f567e2da2a4c7920264bf56fa5e1/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt#L1015) (which should be default)

and u can capture button events via MediaSession's [onMediaButtonEvent](https://github.com/lovegaoshi/react-native-track-player/blob/c032d75d82e8f567e2da2a4c7920264bf56fa5e1/android/src/main/java/com/doublesymmetry/trackplayer/service/MusicService.kt#L1122)

**Comment by CallBackMe** [comment]
@marcbaechinger @lovegaoshi  Thanks to the two teachers, the problem was solved.
![9F931F5241E986D83F77906A4A6D1404](https://github.com/user-attachments/assets/0242bb81-abd0-48d3-8ec8-51cd5df26c0a)

![6742CE42771F38CF1744263C4A59369A](https://github.com/user-attachments/assets/da1aecc5-6857-4357-979e-a6084d4e6fff)

**Comment by CallBackMe** [comment]
thanks again ！
