### ISSUE TITLE
MediaController doesn't pass full exception data in the onPlayerError method

### ISSUE THREAD

**Issue by ziem** [androidx/media#225]
Hello!
I'm using media3 version 1.0.0-beta03. The issue happens when my video endpoint returns 403 status code. `onPlayerError` method from `Player.Listener` that was added to an instance of `ExoPlayer` returns:
```
androidx.media3.exoplayer.ExoPlaybackException: Source error
cause = androidx.media3.datasource.HttpDataSource$InvalidResponseCodeException: Response code: 403
```
on the other hand `onPlayerError` attached to an instance of `MediaController` returns:
```
androidx.media3.common.PlaybackException: Source error
cause = android.os.RemoteException: Response code: 403
```

I understand why is that, but `RemoteException` holds only a message and I cannot access things like response code, etc. The only thing I get is `errorCode` from `PlaybackException` (`2004`/`ERROR_CODE_IO_BAD_HTTP_STATUS` in this case) but it's not enough. It doesn't tell what happened, it's too general for my use case. I want to tell my users what happened and what to do when different status codes are returned from my backend).

It there a way to access status codes in `onPlayerError` method when using `MediaController`?

**Comment by microkatz** [comment]
@ziem 
Would you be able to add error message info to your PlaybackException? PlaybackException inherits from `Exception` and `Throwable` and detailed error message info can be retrieved using `getMessage`. The `PlaybackException` constructors can take `String message` that can be passed along through to `onPlayerError` when using `MediaController`. You can then tell your users using the `String message` what to do even though its a generic status code.

**Comment by ziem** [comment]
I can't do that as I don't control when and how `PlaybackException` is created. It's internal to the `MediaController`/`ExoPlayer` implementation. What do you mean by "can be passed along through to `onPlayerError` when using `MediaController`?

If I described my issue not clearly enough, just let me know. 😉 

Maybe I should've created a feature request instead of this question to make `androidx.media3.common.PlaybackException` carry more data.

**Comment by microkatz** [comment]
Hmm. @ziem. Could you provide a media examples/endpoints for us to test against?

**Comment by ziem** [comment]
@microkatz yes. I created [this PR](https://github.com/ziem/media/pull/1) to illustrate what I would like to achieve: 
- [the first commit](https://github.com/ziem/media/pull/1/commits/a2306f78f0f89d4bd4f5b3d462a3d05163e6cdca) shows what `onPlayerError` returns when it is attached to `ExoPlayer` vs `MediaController`;
- [the other one](https://github.com/ziem/media/pull/1/commits/93507d500cbdb3f8695d6176804d0c002e2b691d) shows my use case.

My goal is to handle errors inside `CustomPlayerView`. I would like to inform users based on returned errors what happened. 

This is what I tried to do to make it work. When the `setPlayer` method with a new `Player` (in this case `MediaController`) is called I attach `Player.Listener` to listen for errors (`onPlayerError`). Based on errors (response status codes) I would like to display custom messages (inside a toast or something else, it doesn't matter). What's stopping me from achieving it is the fact that `onPlayerError` attached to `MediaController` returns "simplified" exceptions, they no longer contain information like status codes, etc. At some point exceptions from `ExoPlayer` are converted to `RemoteException`s with just a message.

I know that I could pipe these errors through some shared component (from `PlaybackService` where `ExoPlayer` lives to `PlayerActivity`) but `CustomPlayerView` seems like a good place to do it.

**Comment by microkatz** [comment]
Thank you for the example code. I investigated and the crux of the issue is the reconstruction of the PlaybackException error across the Binder in the Session. The reconstruction can only occur with bundleable data and the HttpDataSource$InvalidResponseCodeException of which is not a bundleable class. You can file an enhancement request and we can take a look at bettering bundling error data across the binder.

For your scenario however, there are two solutions I thought of for the meantime.

The first is that you note the exception error is `2004/ERROR_CODE_IO_BAD_HTTP_STATUS` and then parse the error message for the response code. Based on your parsing you can post Toast messages etc as you planned to do. 

The alternative is a bit more complicated which is implementing your own custom ForwardingPlayer around the Player instead of using the base ExoPlayer. You would then have to override the addListener and removeListener methods and with your own custom version of the ForwardingPlayer::ForwardingListener. For the overridden CustomForwardingListener::onPlayerError, you would intercept the errors and for HTTP errors, you would alter the cause to be a PlaybackException with custom error message string. You would then parse the message at the end as you planned to do. The benefit of the second option is that you can control the error message string yourself.

**Comment by ziem** [comment]
Thank you @microkatz. I will check the solutions you suggested.
