### ISSUE TITLE
What's the best approach to seamlessly switch to downloaded content?

### ISSUE THREAD

**Issue by JaCobbMedia** [androidx/media#253]
Hello,

As stated in the title I'm looking for a best approach to seamlessly switch current media item that is being played with downloaded one. In our current approach we track downloading progress and whenever it finishes we immediately replace current item with downloaded one and seek to the same position. It's fine but it creates a small delay while player quickly goes through states which interrupts listening experience, so we are looking on how to achieve a seamless switch.

Any help is appreciated

**Comment by marcbaechinger** [comment]
> replace current item with downloaded one

If you have two different URIs, I'd be surprised this is possible seamlessly, because you interrupt playback when setting the new item. I'd even expect this would need to buffer some data for the new item at the requested playback position.

I think using a `CacheDataSource` and a [`CacheWriter`](https://github.com/androidx/media/blob/release/libraries/datasource/src/main/java/androidx/media3/datasource/cache/CacheWriter.java) would be the preferred approach. See [Playing downloaded content](https://exoplayer.dev/downloading-media.html#playing-downloaded-content) in the DevGuide. You wouldn't even know if the player is reading from the cache or downloads directly. I'd expect this would just read from the cache when data is cached, and if not it reads from the upstream data source. 

If you do that, you will pretty soon understand that you will download some media twice if playback is ahead of downloading. That's the next level that is a bit more complicated if you are ambitious and want to avoid this.  Probably start with the above and then look into #8645 for further experimentation.

**Comment by JaCobbMedia** [comment]
Items are identical with same URIs and we are actually using `CacheDataSource`.  When download completes we are taking  `MediaItem` from `Download` and replacing `currentMediaItem`  with it. So if I understood correctly we don't actually need to do any of this as long as URIs are identical, `DataSource` should be able to automatically read from cache as soon as it's available for current playing item and ignore upstream data? Basically what we are trying to reduce network activity as much as possible, so if user is listening to item and decides to download it, we want to make sure that after download is finished no more listening over network is happening and everything is played from downloads/cache

**Comment by JaCobbMedia** [comment]
Okay, so I tested with network profiler and it seems that my guess was correct, that there's no need to force switch items if they have identical uri. I guess I haven't properly understood before how `CacheDataSource` really works. I removed our code which was responsible for switching to downloaded media item and I can see that there's no network activity after item was downloaded, which was our goal.

**Comment by marcbaechinger** [comment]
Sorry for lagging behind. 

> we don't actually need to do any of this as long as URIs are identical,

Yes. And if URIs are not identical (like because of a hash that expires or similar), you can set  `DataSpec.key` to an identical value for the URI and it works as well.  

For instance you can set `DataSpec.key` to `media1234` for these URIs pointing to the same file

http://www.example.com/media1234/token/oisadjaosdjaksdjnakljsnd
http://www.example.com/media1234/token/121231289312381290830

(or use a custom `CacheKeyFactory` with `CacheDataSource.Factory.setCacheKeyFactory(factory)`)
