### ISSUE TITLE
What is Playback Resumption

### ISSUE THREAD

**Issue by neonwarge04** [androidx/media#260]
I don't seem to understand what this is for Supporting playback resumption as described in this [article](https://developer.android.com/guide/topics/media/media-controls)

Is this related to when I close the application completely (UI dead, service dead), and then I am able to resume the application where it left off, as such:

- Remembers the track it last played
- Remembers the last seek position (e.g. 250_000 ms elapsed)
- Remembers the tracks that was set via browser.setMediaItems()

Currently what I was doing before I used exoplayer, is I cached the current track, the group the track belongs to (album, artist, genre etc.) which then I use to load the tracks and reinsert it again into the player once the application starts.

This in turn provides me the information I need to show in the UI (like the current track and the current group).

Is this what playback resumption is? Is this what this new feature already doing? Because if it is, then probably I don't need my caching logic anymore.

**Comment by marcbaechinger** [comment]
Playback resumption as described by the article is basically a notification that is populated by SystemUI when your app (as the last playing media app) has terminated. [This article](https://android-developers.googleblog.com/2020/08/playing-nicely-with-media-controls.html) has a bit of more info in case this is of interest but is also still based on the legacy API not Media3.

The system knows the last audio app that has played audio and if this app has a `MediaLibraryService/MediaBrowserService` the system is keeping track of the last played media item as described by the article. With that metadata, SystemUI then creates a notification. When the user taps the notification, SystemUI starts the service, calls `onGetLibraryRoot` to tell the app to prepare and then issues a `controller.play()` command. Because this is initiated by the notification, the service is allowed to start in the foreground by exemption.

SystemUI always tries to get that information from a `MediaLibraryService`. If the method calls return the expected data, SystemUI assumes that the app/service is able to resume playback once triggered by the user tapping the notification.

However, when `onGetLibraryRoot` is called the app still needs to know by itself what the most recent item was, at which playback position playback stopped and also which other media items were in the playlist. So you still need to maintain this information yourself for proper support. The call to `onGetLibraryRoot` with the `EXTRA_RECENT` flag tells you to do something like this (all `getMostRecentXyz()` methods need to be provided by the app):

```
List<MediaItems> mostRecentPlaylist = getMostRecentPlaylist();

player.setMediaItems(mostRecentPlaylist, getMostRecentWindowIndex(), getMostRecentPlaybackPosition());
player.prepare();
player.play();
```

What media resumption by SystemUI does is just presenting a notification with the most recently played item metadata and then give your service a nudge to start playing.

Note: Currently, you need to register your service as a `MediaBrowserService` as well to have SystemUI recognize your service:

```
    <service
        android:name=".PlaybackService"
        android:foregroundServiceType="mediaPlayback"
        android:exported="true">
      <intent-filter>
        <action android:name="androidx.media3.session.MediaLibraryService"/>
        <action android:name="android.media.browse.MediaBrowserService"/>
      </intent-filter>
    </service>
```


UAMP has thi simplemented with Media3 in the `media3` branch of UAMP. See [here](https://github.com/android/uamp/blob/media3/common/src/main/java/com/example/android/uamp/media/MusicService.kt#L327) and [here](https://github.com/android/uamp/blob/media3/common/src/main/java/com/example/android/uamp/media/MusicService.kt#L347).
