### ISSUE TITLE
What if MediaItemTree.initialize() takes awhile?

### ISSUE THREAD

**Issue by neonwarge04** [androidx/media#263]
So I found this following [issue](https://github.com/androidx/media/issues/167), as I believe I encountered this issue as well. So I checked the demo-session app and checked the PlaybackService and I found the following code in `MediaTree.initialize()`

```
  fun initialize(assets: AssetManager) {
   ....
    // Here, parse the json file in asset for media list.
    // We use a file in asset for demo purpose
    val jsonObject = JSONObject(loadJSONFromAsset(assets))
    val mediaList = jsonObject.getJSONArray("media")

    // create subfolder with same artist, album, etc.
    for (i in 0 until mediaList.length()) {
      addNodeToTree(mediaList.getJSONObject(i))
    }
  }
```

This looks fine as it establishes the tree node, `MediaItem.initialize()` is called on `PlaybackService.onCreate()`. What would you recommend to do if `MediaItem.initialize()` takes awhile to load? I have a data source (querying using ContentResolverCompat) of some sort which I called but this takes time to load and it uses coroutines.My entire data source hasn't been loaded yet by the time my service is destroys itself because it didn't called `startForegroundService` soon enough. My understanding here is that `onGetLibraryRoot` returns empty and in turn couldn't play anything because I am still initializing.

I don't know why Google samples are always like this, kept on loading resources from the assets folder. What if I am loading my information from some source which may take awhile (remotely, or I have to query `ContentResolverCompat` for the tracks I can play)? Is it possible to give me sometime to load without hitting that exception? What is the best approach here?

**Comment by marcbaechinger** [comment]
> What would you recommend to do if MediaItem.initialize() takes awhile to load? 

I'd recommend to load the media catalog asynchronously.

> Is it possible to give me sometime to load without hitting that exception?

Loading the database and starting playback is not necessarily coupled by the library, if it is, it is by app logic. With the exception of the 'resume playback case by BT' (see below), an app starts the service by building a controller/browser. This way an app doesn't need to hurry with starting playback because there is no need to start foreground at all. We are happily in the bound state and starting the player can wait.

There is one case I can think of that the service needs to be started with an start-foreground-service intent and this is when playback is resumed from a BT headset. In such a case the service is started as a foreground service with an `Intent`, needs to prepare the player with the least recently played item and start playback swiftly. For this use case the recommended approach is to store the least recently played media item metadata in a way that can be loaded quickly.

Besides this BT case I would say starting the service by `Intent` is an anti-pattern or even not supported by the `MediaLibraryService`. There is an API for starting the service which is not base on `Intent` for a reason. Apps can do differently, but then they may run into problems.

In other cases separate from BT, I'd expect that the service is started by building a `MediaBrowser` or `MediaController`. In this case the browser/controller binds to the service. The service is not started with a start foreground service intent and hence there is no rush in calling start foreground I think. Your app is bound to the service and app and service is happy because we are in a bound state. You can load data as long as it requires you to do so from a content provider, a json file on disk or the internet, a local database or another method that loads data in a background thread or with coroutines/suspend in Kotlin.

The service methods like 'onGetChildren' can and need to wait. They return a `Future` and can wait until loading has completed. UAMP has [`callWhenMusicSourceReady`](https://github.com/android/uamp/blob/media3/common/src/main/java/com/example/android/uamp/media/MusicService.kt#L294) in case you want to look at a Google sample that doesn't read from the asset folder.

If I missed a use case that can not be served with the above approach, please explain me your use case in a bit more detail and why you need to start foreground quickly in that case.

**Comment by neonwarge04** [comment]
Hello thanks for the prompt response @marcbaechinger! I do understand when something takes awhile I need to load asynchronously, my question is how? The sample is using Futures but I am using Coroutines, I can't seem to connect the dots here. When loading from source, I use coroutines here is a very small snippet from my code:

```
class MyService : MediaLibraryService() {
    override fun onCreate() {
        ...
        // ExoPlayer setup goes here
        ...
        initializer.init() // Inside this init is a coroutine.launch{} which executes my initialization logic. In a device with 700+ tracks, 200+ groups, the best time this complete under debug mode is 10 seconds which it appear it isn't enough to keep this instance alive
    }
}
```

Please assume the following steps where I encounter the Foreground service exception:
- Pause the player
- Kill the app
- Start the player from notification (e.g. in the example I mentioned, this step was triggered by Bluetooth)
- The service will go alive (for like 5 seconds in my case?), it will call my Initializer which when it finishes  successfullyI have all the information I need including:
  - The current track that was last played
  - The progress of the track
  - The containing group the track was playing on
- Then crash because I didn't call `startForegroundService` soon enough.  

The only thing I suppose to be missing is the minimal 'metadata' information of the tracks under a group which I can read of off disk.

When I enable my breakpoints on and put one `onGetLibraryRoot`  this one gets hit (right before the entire service goes dead). At this point I realized my system that facilitates my contents are not yet finish initializing. I have like 5 seconds before I provide something which clearly I don't have. Its goes dead while my Initializer is initializing. The thing is I am tempted to call `startForegroundService` but I think this is not intended to do within `MediaBrowserService` or `MediaSessionService`.

But in your 2nd paragraph you have given the answer to this, which I believe you must put into documentation this specific case in order to prevent this problem. 

What I will try would be the following, when a track has been played, I will gather all the following information (3 of which I am already doing right now, I will just add one more information):
  - The current track that was last played
  - The progress of the track
  - The containing group the track was playing on
  - [New] The tracks under that group (which would be containing the minimal metadata)

Given this case, what I will do is simply allow my initializer to fire off but along side it I will just load the metadata I store on disk and load it back, parse and build the mediaitem meta data so I can setup my Player immediately. I can bypass my initializer as this is a simple cache read.

Is this written somewhere in the official docs or is this presented in the demo-session app?

**Comment by neonwarge04** [comment]
Not sure if this another important use case, though I haven't done an in-depth integration with google assistant. What if I say "Ok Google Play this <trackname> on <My app name>", and when the application is dead. Would it trigger the same behavior here because we woke the service without an accompanying UI hence the foreground exception?

Iirc, this will in turn call `onGetSearchResult`, which base on my example above, my initializer isn't done yet making sure my app is in nominal state. 

The fact that the API returns a Future doesn't seem to help me here either and this is one crucial pain point. I can replicate that `callSourceWhenReady` but I am not knowledgeable how to do this in Kotlin coroutines as my application is written in Kotlin and heavily relies on this. The loading of tracks is done in coroutines and the media Media3 APIs expects a future. Its really hard to tie things together.

**Comment by marcbaechinger** [comment]
> What if I say "Ok Google Play this trackname on My app name", and when the application is dead. Would it trigger the same behavior?

Assistant, that executes the voice command, creates a `MediaBrowser` that starts the service by binding to it. There is no `PendingIntent` involved that would make the system expect that the service is started in the foreground within a given amount of time.

**Comment by marcbaechinger** [comment]
What about the following approach:

1 - When the service is started you [get the media URI, title and the artworkURI from local storage](https://github.com/android/uamp/blob/media3/common/src/main/java/com/example/android/uamp/media/PersistentStorage.kt#L68) create a media item and set it to he player.
2 - Prepare the player with this single item. Notification and everything should work already with the basic data of a single item.
3 -  Start playback (this puts the service into foreground)
4 - Now trigger loading your database asynchronously.
5 -  When the database returns you get the other items of that category/playlist and you can add it to the player to complete the playlist. If you leave the media item that you added in 2 untouched playback is not affected by this.

With this approach you load the minimum very quickly and start playback immediately. Then you are safe of the exception that has caught you above and you have time to load the rest and complete the playlist restorage. 

The user does not have a UI apart from the notification in this resume-when-app-not running case that is started from BT. So the user never sees an incomplete UI unless they are observing the notification very closely and see that suddenly the `skip next` button is available. But the user won't use the BT headset and observe the notification at the same time as the essence of this use case.
