### ISSUE TITLE
Media3 Exoplayer Restarted when Notification Icon Clicked

### ISSUE THREAD

**Issue by ilkeraslan** [androidx/media#28]
When the notification is clicked, the media is reinitialized recreating the activity. I have searched for similar issues without any success.

Related question can be found [here](https://stackoverflow.com/questions/70594071/mediaplayer-reinitialized-when-notification-clicked).

**Comment by marcbaechinger** [comment]
The sample you posted on StackOverflow does eventually always call these line as a consequence of `onCreate` of the `Activity` being called: 

```
 controller.setMediaItem(mediaItem)
 controller.prepare()
 controller.play()
```

This way your code sets a new media item hard coded each time when `onCreate` of your `Activity` is called. I think for that perspective it working as intended. 

What happens is that you have set a `PendingIntent` when you build the `MediaSession` in your service (see you code on stack overflow). You have taken the code from the demo app to do so. I don't know how the `<activity>` element in your manifest is configured, but if you left it in the default setting then `onCreate` is called each time the activity is pushed to the top of the back stack of the current task.

If you want to avoid this you can do this in several way, this is up to you:

In the `onCreate` method add an if statement that checks whether the controller has already been prepared. You can check whether `controller.mediaItemCount > 0` or `controller.playbackState != Player.STATE_PREPARED`. This way you can make sure that the controller player in the service does not replace the current playlist.
 
An alternative would be to configure the activity to not be recreated. Check this [doc about Tasks and the back stack](https://developer.android.com/guide/components/activities/tasks-and-back-stack) that gives you plenty of details about how this works an can be done. One way is to set the `launchMode` to `singleInstance` or `singleInstancePerTask` in the manifest: 

```
<activity
      android:name=".PlayerActivity"
      android:exported="true"
      android:launchMode="singleInstancePerTask">
</activity>
```

When this is set properly `onCreate` is only called once and a subsequent intent that aims for creating this activty results in `onNewIntent(intent: Intent?)` being called instead. This would bypass your initialization code.

Please not that what approach you choose totally depends on the use case you want to do with your app. I can't give you some specific recommendations for this. 

If this is what has caused your issue I recommend reading the [doc about Tasks and the back stack](https://developer.android.com/guide/components/activities/tasks-and-back-stack) and then decide what you want to do. At a first glance this issue seems to be due to the way you create the activity and it seems a bit that you are still in the demo app stage, because you always set only one hard coded `MediaItem` in on create:

```
.setMediaUri("SOME_MEDIA_URL.mp3".toUri())
```

I'm closing this issue. Please re-open if you think the issue is caused by the library.

**Comment by ilkeraslan** [comment]
Thank you for the detailed answer, before creating the issue I have had already tried `launcMode="singleInstancePerTask"` but it didn't work. I tried it again with some logs, and I can see that the activity is recreated each time I press on the notification on the lock screen. I'm sorry but setting the `launchMode` does not resolve the problem.
