### ISSUE TITLE
Could you let me know when I can start using stable API roughly?

### ISSUE THREAD

**Issue by sosh9898** [androidx/media#331]
I'm trying to migrate to Media3.
But now, I have to attach many **UnstableApi** annotations to classes in our app even if I use with @OptIn annotation.

I know **UnstableApi** means just not API-Frozen regardless of quality or performance. That having said, our team wants to use a stable API if possible.

So, we are considering using the Exoplayer until a stable API is available.
Could you let me know when I can start using stable API roughly? 
And please let me know if I can use a stable API before Exoplayer is deprecated.

**Comment by icbaker** [comment]
I think the most important thing to make clear is (since you're migrating from `exoplayer2`): `exoplayer2` has **no API stability guarantees at all**. In `media3` we have made clear which bits of the API we're never going to change, whereas we haven't made that clear in `exoplayer2` (and effectively reserve the right to change anything).

So I don't think it makes sense to delay migration from `exoplayer2` to `media3` over this, since by using `exoplayer2` you're effectively **only** using unstable APIs (by the `media3` definition).

----

That said, we are interested in hearing about 'developer journeys' that are currently not possible with the Media3 stable API, and we are certainly planning to stabilise more parts of the API surface over time. Would you be able to sketch out what parts of the unstable API you're using? It would also be helpful to 'tell the story' of what you're doing with the library that needs those API calls (if that makes sense), so we can understand the context. I may be able to give you an idea of how likely we are to stabilise each of the bits you mention.
