### ISSUE TITLE
EAC3 audio cannot be played on external speaker setup

### ISSUE THREAD

**Issue by vishnuchilakala** [androidx/media#333]
### Media3 Version

ExoPlayer 2.18.4

### Devices that reproduce the issue

TV: Sony Bravia LED TV 4K GB ATV3, Model No: KD-49X8000G
External speakers: WOOFER: SSWSB123 Sony 5.1 speakers
Audio player: BDV-E3200

### Devices that do not reproduce the issue

Any other TV / Speaker combo.
(The same speakers do work with an Mi TV)

### Reproducible in the demo app?

Yes

### Reproduction steps

Play this stream - shared privately to dev.exoplayer@gmail.com

### Expected result

Both video and audio should play.

### Actual result

Only the video plays. There is no audio.

### Media
Content with EAC3 audio that can reproduce the issue - Will send to dev.exoplayer@gmail.com.
Content with EAC3 audio that does not reproduce the issue - https://ott.dolby.com/OnDelKits/DDP/Dolby_Digital_Plus_Online_Delivery_Kit_v1.4.1/Test_Signals/muxed_streams/DASH/OnDemand_MPD/ChID_voices_1280x720p_25fps_h264_6ch_640kbps_ddp_joc.mpd

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by vishnuchilakala** [comment]
Some more details:
- The issue is reproducible on older Exoplayer versions too, atleast until 2.17.2.
- The same setup is able to play EAC3 audio on other OTT applications and some open source contents (Open source test streams from dolby like [this](https://ott.dolby.com/OnDelKits/DDP/Dolby_Digital_Plus_Online_Delivery_Kit_v1.4.1/Test_Signals/muxed_streams/DASH/OnDemand_MPD/ChID_voices_1280x720p_25fps_h264_6ch_640kbps_ddp_joc.mpd), [this](https://ott.dolby.com/OnDelKits/DDP/Dolby_Digital_Plus_Online_Delivery_Kit_v1.4.1/Test_Signals/muxed_streams/DASH/OnDemand_MPD/Silent_25fps_h265_multi_av_rate.mpd) and [this](https://ott.dolby.com/OnDelKits/DDP/Dolby_Digital_Plus_Online_Delivery_Kit_v1.4.1/Test_Signals/muxed_streams/DASH/OnDemand_MPD/ChID_voices_1280x720p_2997fps_h264_multi_lang.mpd)).
- Enabling / disabling tunneling did not help the issue.

I have dropped a mail to dev.exoplayer@gmail.com with the streams to reproduce the issue with the subject "Issue #333".
Please do let me know if you need any further info. Looking forward to hearing from you!

**Comment by vishnuchilakala** [comment]
@christosts Were you able to find any clues from the bug report? Please do let me know. 
Users from production reporting these issues are increasing with time and we would appreciate any possible help. Thanks a lot!

**Comment by christosts** [comment]
From the bug-report, the player is playing the EAC-3 content using passthrough audio. The logs coming from ExoPlayer say that the player thinks everything is working. You're observing no audio but video is playing, which leads me to think the device is not outputting any audio yet the player is feeding the audio and the device's AudioTrack is reporting it's advancing. Otherwise video would not make progress because video progresses based on the progress reported by AudioTrack.

In the bug-report there are several warn and error logs coming out of the platform

```
04-18 16:23:03.488  1041  1347 28373 W AudioFlinger: AudioFlinger::DirectOutputThread::processVolume_l left 1.122018 right 1.122018
...
04-18 16:23:03.489  1041  1311  5277 W StreamHAL: Error from HAL stream in function set_volume: Function not implemented
04-18 16:23:03.490  1041  1347 28373 E AudioFlinger: Error when setting output stream volume: -38
...
04-18 16:23:03.580  1041  1347 28373 W AudioFlinger: pause because of UNDERRUN, framesReady = 0,minFrames = 1, mFormat = 0xa000000
04-18 16:23:03.580  1041  1311  5277 D audio_hw_primary: pause for NON-Tunal AC3
04-18 16:23:03.580  1041  1311  5277 W StreamHAL: Error from HAL stream in function pause: Unknown error -1
04-18 16:23:03.580  1041  1347 28373 E AudioFlinger: Error when pausing output stream: -61
```
so I wonder if the device specifically does not output audio (not sure why) but everything else appears to be working fine. The stream that you say is working is using Atmos but I'd need to have another bug-report to tell whether Atmos is also pushed directly to the speakers or ExoPlayer opens a local decoder for it.

Whether other apps play the EAC3 content: this also depends whether this TV has a decoder for EAC3 and whether the other apps are doing passthrough audio or use a decoder for it - I would need a bug-report for that too to see what the apps are doing. 

May I ask you to do the try the following on the demo app: on the TV with the speakers connected, try disabling audio passthrough for EAC3. On the demo app's [DemoUtil](https://github.com/androidx/media/blob/3c01488f8d478caaa54038431ee6339444ea6e04/demos/main/src/main/java/androidx/media3/demo/main/DemoUtil.java#L85) change the renderer's factory to build an audio sink that can not do passthrough audio for EAC3

```java
return new DefaultRenderersFactory(context.getApplicationContext()) {
      @androidx.annotation.Nullable
      @Override
      protected AudioSink buildAudioSink(Context context, boolean enableFloatOutput,
          boolean enableAudioTrackPlaybackParams, boolean enableOffload) {
        // create default audio sink
        AudioSink audioSink = super.buildAudioSink(context, enableFloatOutput,
            enableAudioTrackPlaybackParams,
            enableOffload);
        // wrap audio sink 
        return new ForwardingAudioSink(audioSink){
          @Override
          public boolean supportsFormat(Format format) {
            return getFormatSupport(format) != AudioSink.SINK_FORMAT_UNSUPPORTED;
          }

          // don't support direct audio for EAC3
          @Override
          public @SinkFormatSupport int getFormatSupport(Format format) {
            if (MimeTypes.AUDIO_E_AC3.equals(format.sampleMimeType)) {
              return AudioSink.SINK_FORMAT_UNSUPPORTED;
            }
            return super.getFormatSupport(format);
          }
        };
      }
    }
        .setExtensionRendererMode(extensionRendererMode);
```

With this audio sink, the player will attempt to find a decoder for EAC3 on the device and if one exists it will use it. The demo app's EventLogger will report events with `audioDecoderInitialized`. If the TV does not have a decoder, the audio tracks will be unsupported.

**Comment by vishnuchilakala** [comment]
Thanks for taking the time @christosts !

<h3>Replacing the default audio sink with the snippet you provided above works!</h3>
What would this say about the root cause of the issue? Is it an Exoplayer bug or an Android bug?<br/><br/>

**I have sent two more bugreports to dev.exoplayer@gmail.com on the same thread with subject "Issue #333"**. One of them is after playing the Dolby open source content with EAC3 audio through the demo app, which works without any issues. The other one is just after playing an EAC3 content from Disney+ streaming app, which also works without any issues.

Here are some more details that we found with our extensive testing on this setup:

1. There is one consistent way to play the affected content on the setup: Start the playback **WITHOUT the speakers plugged in**. After the playback starts, plug them back in. That will cause the audio to be routed to the speakers without any issues. But if the playback is started while the speakers are connected, the audio would not play even after switching back and forth between the TV speakers and the external setup.
2. Playing using an external Android dongle such as a Fire TV / Chromecast to the very same setup also works. **_Would this confirm that this might be a Sony bug?_**
3. I checked the [output](https://github.com/androidx/media/blob/1ef427f640277dc8e0ad09ebf86be972f216eb82/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/audio/AudioCapabilities.java#L93) of `AudioManager.EXTRA_ENCODINGS`. It always is this:
```
AudioCapabilities[maxChannelCount=8, supportedEncodings=[5, 6]]
```
I am guessing this means the platform can definitely support EAC3, but somehow the routing is getting lost just for our content.
4. There is no `audioDecoderInitialized` log from `EventLogger` for any of the playbacks, working or otherwise, unless I replace the default `AudioSink` with the snippet you gave above.

Here are some more device details:
TV Model: Sony Bravia 4K GB ATV3
Android version: 9
Build: BRAVIA_ATV3_4K_PA-user 9 PTT1.190515.001.S52672101 release-keys
No pending software updates. Resetting to factory settings also did not work.

If you need me to test something else on the setup or need more info, please do let me know.

Really appreciate you debugging this complex issue. Thanks a lot!

**Comment by christosts** [comment]
> Replacing the default audio sink with the snippet you provided above works!

Glad to hear but there is a caveat. The decoder may be downmixing audio to stereo. Hence, with 5.1 speakers you may be losing quality because the audio is downmixed to stereo and then sent to the speakers to upmix to multi-channel. Some devices are smart enough to know whether they output to 2 or more speakers and set their decoder behavior accordingly, but this is something an app cannot control, at least not until Android 12L. To be sure whether this is a good option for you, you need to verify the output of the decoder is still multi-channel. I can guide you how to look for that. 

From the additional bug-reports, I still see the same logs output from AudioFlinger as before, so we can rule out that this is not the problem. The one difference I see from the BRs is that EAC3 content bitrates are different. The failing content has 192 and 384 kbps encodes whereas the working audio is at 256 kbps. For the disney content, I can't tell what's happening because the BR has logs for the `aac` decoder and I don't know what the app is doing there.

From your overall experiments, it sounds like this is a TV specific issue. There was an issue before ExoPlayer 2.18.3 (media3 1.0.0-rc01) related to audio passthrough but the symptom was that the player would get stuck, which I don't think you're hitting, since video plays fine.

**Comment by christosts** [comment]
> To be sure whether this is a good option for you, you need to verify the output of the decoder is still multi-channel. I can guide you how to look for that.

On the `ForwardingAudioSink` I shared before, add an override for `AudioSink.configure()` to inspect the channelCount of the `inputFormat`:

```java
@Override
public void configure(Format inputFormat, int specifiedBufferSize,
    @androidx.annotation.Nullable int[] outputChannels) throws ConfigurationException {
  // inspect inputFormat.channelCount. You may also use inputFormat.toString() 
  // or Format.toLogString(inputFormat).
  super.configure(inputFormat, specifiedBufferSize, outputChannels);
}
```

I'm inclined to close this as device-specific where ExoPlayer cannot do more than what I described. You can reach out to Sony to report the issue. Feel free to re-open if you think I may have missed something.

**Comment by vishnuchilakala** [comment]
@christosts Oops, I think you might be right.

With the snippet you gave above, the input format shows only 2 channels. 
But this code does return 6 :
```
Format audio = ((ExoPlayer) player).getAudioFormat();
Log.e("EAC3Test", "channel count = "+ audio.channelCount);
```
But the output seems to be coming only from 2 of the 6 speaker setup. It is definitely not working as expected.

I guess it is still possible that this is an Exoplayer bug of not handling a different kind of EAC3 input properly? I say this because Android's MediaPlayer with the same setup does play the same content as expected.

Or is it possible that it is something wrong with the content itself?

Please do let me know what you think. Thank you!

**Comment by christosts** [comment]
> I guess it is still possible that this is an Exoplayer bug of not handling a different kind of EAC3 input properly? I say this because Android's MediaPlayer with the same setup does play the same content as expected.

How do you play DASH content with MediaPlayer? Please send us a bug-report with MediaPlayer on the same content you play with ExoPlayer.

**Comment by vishnuchilakala** [comment]
@christosts I used an audio-only MP4 file from our pipeline to test this scenario which I was hoping would narrow down the investigation.

**I have mailed two bugreports on the same thread called "Issue #333" - one after playing the MP4 using the Exoplayer Demo app and one after playing the same MP4 with a test app I built using MediaPlayer.**

MediaPlayer outputs stereo audio (only 2 speakers work) by default whereas Exoplayer does not seem to realise that there is no audio unless we do the above mentioned override.

Please take a look and let me know what you think. Thank you!

**Comment by christosts** [comment]
I think there are some conflicting statements between

> I say this because Android's MediaPlayer with the same setup does play the same content as expected.

and 

> MediaPlayer outputs stereo audio (only 2 speakers work) by default 

The bug-report from MediaPlayer shows that MediaPlayer occupied a decoder which then downmixed the audio to stereo. This is equivalent to original solution I offered with disabling audio passthrough. I think this is an issue with the TV.

**Comment by vishnuchilakala** [comment]
Got it. We will take this up with Sony. Thanks for the help!
