### ISSUE TITLE
onRenderedFirstFrame called before onMediaItemTransition

### ISSUE THREAD

**Issue by Stronger197** [androidx/media#341]
### Media3 Version

Media3 1.0.1

### Devices that reproduce the issue

* Pixel 7 pro Android 13
* Pixel 6 pro Android 12
* Emulator api 33

### Reproducible in the demo app?

Yes

### Reproduction steps

In demo app:
1. override `onRenderedFirstFrame` and `onMediaItemTransition` in `Player.Listener` and log timestamps
2. launch playlist, e.g. **Audio -> Video -> Audio**
3. wait until the current media item completes normally, **don't click next button**, but you can seek almost to the end so as not to waste a lot of time
4. check the logcat output.

### Expected result

onMediaItemTransition event/custom message event before the onRenderedFirstFrame event, as it work if we click "next" button during the playback.

// clicked next button before the end of the current media source
03:30:39.622 onMediaItemTransition
03:30:40.397 onRenderedFirstFrame

### Actual result

`onRenderedFirstFrame` is called 50ms early then `onMediaItemTransition`
03:10:36.161 onRenderedFirstFrame
03:10:36.216 onMediaItemTransition

Also same happens if i schedule a custom message at the end of mediaSource
```
player.createMessage((messageType, message) -> Log.e("ExoTag", "New message: " + message))
              .setLooper(Looper.getMainLooper())
              .setPosition(i, C.TIME_END_OF_SOURCE)
              .setPayload("Custom payload")
              .send();
```
03:23:27.739 onRenderedFirstFrame
03:23:27.777 New message: Custom payload

The problem is this: I can't determine that the current media source is ended in order to pause playback. I will see the first frame of the next video.

### Media

Not applicable

### Bug Report

- [x] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
This is actually working as intended and reporting the order of events correctly. 

When automatically transitioning from one item to the next, the player continuously releases output frames to the surface as if everything was a single stream. This ensures super smooth transitions without any gaps. "Releasing a frame" happens very shortly before you can actually see it (up to 50ms in fact). This is needed because of the low-level display logic that needs the new data two sync intervals before it is shown. So the player is actually triggering the first frame of the new video shortly before the timestamp transitions between the two items. The resulting effect for the user is a smooth transition. 

The question you could ask is: can't we just "correct" the order to allow association of events to the media items? The answer is generally no, because we want to maintain events in the order in which they actually occur. When you use `AnalyticsListener`, every callback has an `EventTime` parameter telling you details about which item the event belongs to (e.g. using `eventTime.windowIndex`). There are actually other events, for example `onLoadStarted`, that happen a long time in advance for another time, so this isn't just about rendering the first frame.

> I can't determine that the current media source is ended in order to pause playback. I will see the first frame of the next video.

Assuming this is actual goal, then you should just use `ExoPlayer.setPauseAtEndOfMediaItems` to auto-pause on exactly the last frame of each item. You can also enable it in the `ExoPlayer.Builder` or toggle it later if needed.

**Comment by Stronger197** [comment]
Ok, thanks for the quick response an explanation!

**Comment by Stronger197** [comment]
@tonihei oh, and one more thing.
You are the best open source team I have ever seen. You're doing a great project, always help quickly, open to contributions without an infinite number of circles of hell.
Thanks!
