### ISSUE TITLE
How to play video media on child process

### ISSUE THREAD

**Issue by sunhb** [androidx/media#37]
I have a player service on a child process named ":player",  and the UI components is in main process. 
I want to know how to render video from child process to VideoView in main process.

**Comment by sunhb** [comment]
Any Tips？

**Comment by andrewlewis** [comment]
At a high level you can pass a `Surface` to render to from you UI process to the player process.

I'm not sure what specific component you mean by `VideoView` (perhaps you mean the one in the framework) but I expect it can't be used in the setup described because it probably has playback built into it.

The easiest way in AndroidX Media3 is to add a `PlayerView` in the UI process, create a `MediaController` and then attach to a `MediaSession` that's hosted by your playback service in another process. The `Surface` to render to gets passed between processes by the implementation of media sessions under the hood.
