### ISSUE TITLE
Unresolved reference: createTextSampleFormat,How do I add subtitles to the player

### ISSUE THREAD

**Issue by BraveHL** [androidx/media#401]
![image](https://github.com/androidx/media/assets/22335503/d0354a34-db4d-4f21-9158-38cb842e7b33)

**Comment by BraveHL** [comment]
Please help me write a simple example, in the latest version, it seems that many functions have changed

**Comment by BraveHL** [comment]
I need to sideload a video in 1.0.1, MediaSource doesn't seem to be able to create it directly, Format.createTextSampleFormat also reports an error, please write a simple example for me

**Comment by icbaker** [comment]
To answer your original question of what to use instead of `createTextSampleFormat`, check the [release notes of ExoPlayer 2.15.0](https://github.com/google/ExoPlayer/blob/release-v2/RELEASENOTES.md#2150-2021-08-10):
> * Remove `Format.create` methods. Use `Format.Builder` instead.

For your second question, you can see an example for sideloading subtitles here: https://developer.android.com/guide/topics/media/exoplayer/media-items#sideloading_subtitle_tracks
