### ISSUE TITLE
Playback starts with 4s offset in DASH live stream

### ISSUE THREAD

**Issue by vishnuchilakala** [androidx/media#414]
### Media3 Version

ExoPlayer 2.18.4

### Devices that reproduce the issue

All devices

### Reproducible in the demo app?

Yes

### Reproduction steps

Happens only on some contents. 
Exoplayer always starts the playback from 4s. But the same content starts at 0s with Shaka player.

### Expected result

Playback should start from 0s i.e. start of the manifest.

### Actual result

Playback starts at 4s.

### Media

I cannot share the media, but will share the manifest to dev.exoplayer@gmail.com.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
The manifest you shared via email is a live stream and the player will start playback at the specified `suggestedPresentationDelay="PT13.9304S"`, meaning 13.9 seconds behind the current real-time. So "start from 0s" is never the expected result for this manifest and doing this sounds more like a bug in Shaka player. 

Where exactly in the manifest ExoPlayer starts depends on the exact timing of the playback request because the player aligns it with the current UTC time. Since your manifest doesn't define a `UTCTiming` element, the player falls back to a NTP request to obtain the current time. Adding a `UTCTiming` element is also recommend by the DASH interop guidelines to achieve a consistent behavior across clients: https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html#clock-sync 

Possibly related to your question: the manifest also defines `minBufferTime="PT4.0S"`, which means that the player should never attempt to play closer than 4 seconds to the *end* of the available live window. The value usually represents the level of variation in the content encoding and is recommend to be set to one GOP size. This ensures there is no sudden data underrun for extreme variations in the encoding process. See https://dashif-documents.azurewebsites.net/DASH-IF-IOP/master/DASH-IF-IOP.html#minbuffertime-feature. I wonder if that's the 4s value you are referring to? It's more relevant as an offset from the end of the live window though (not from the start) and doesn't seem to match your problem description.

**Comment by vishnuchilakala** [comment]
I thought so too, which is why I am just as perplexed with this behaviour.

About `suggestedPresentationDelay` and `minBufferTime`, I have tried hardcoding all possible values to figure out which property is throwing off the player. To be specific, I edited [`buildMediaPresentationDescription`](https://github.com/google/ExoPlayer/blob/release-v2/library/dash/src/main/java/com/google/android/exoplayer2/source/dash/manifest/DashManifestParser.java#L228)  from `DashManifestParser` to return this:
```
  return new DashManifest(
      availabilityStartTime,
      C.TIME_UNSET,
      C.TIME_UNSET,
      dynamic,
      C.TIME_UNSET,
      C.TIME_UNSET,
      C.TIME_UNSET,
      C.TIME_UNSET,
      null,
      utcTiming,
      null,
      null,
      periods);
```

The behaviour has a slight change:
With the `minUpdateTimeMs` taken from manifest, the playback is starting from `3.99s` i.e. the original issue that I mentioned. But if I set it to `C.TIME_UNSET`, the playback starts from `5.00s`. I confirmed this using `EventLogger` logs where it shows that the position changes due to a source update.
```
2023-05-24 21:30:12.845 13687-13687 EventLogger             com.google.android.exoplayer2.demo   D  timeline [eventTime=4.36, mediaPos=3.99, window=0, period=0, periodCount=2, windowCount=1, reason=SOURCE_UPDATE
```
None of the other properties seem to have any effect on the starting position.

I have also tried adding `setLiveConfiguration(new MediaItem.LiveConfiguration.Builder().setTargetOffsetMs(0L).build())` to [`createMediaItemFromIntent`](https://github.com/google/ExoPlayer/blob/release-v2/demos/main/src/main/java/com/google/android/exoplayer2/demo/IntentUtil.java#L126) but that caused no change in initial position.

Nevertheless, none of these changes could make the playback start from 00:00. As you can see from the manifest, there are two segments in the pre roll - a 4s one and a 2s one. But in action, I guess only 2s of the pre roll is being played and somehow the first segment is not being played.

Could this be a function of `availabilityStartTime` and the `start` property of the period? If there is any other property you would like me to test, please do let me know.

Appreciate you taking the time! Thanks!

**Comment by vishnuchilakala** [comment]
@tonihei I have raised a PR to make the `minLiveStartPosition` configurable: #425 
Can you please check this and let me know what you think? Thanks!

**Comment by vishnuchilakala** [comment]
@tonihei we are waiting on your review to fix a critical production bug, so would appreciate your help here. Thanks!

**Comment by tonihei** [comment]
I'll close this issue because the general behavior is WAI as far as I can see. The feature request to make the min live position configurable is discussed in #425.
