### ISSUE TITLE
Where to remove png or bmp file header

### ISSUE THREAD

**Issue by FongMi** [androidx/media#417]
Here is a png ts example.
"   ![4db62d91c95e4b84ae567a8decd09d33](https://github.com/androidx/media/assets/3471963/0423e6aa-d66d-4684-8b9c-4517a0c0bca7)   "

I need remove the file header 
![image](https://github.com/androidx/media/assets/3471963/6fb4186f-b28a-4285-a83a-77f7663f8f1d)

Can someone tell me where to remove ?

I think is TsExtractor

**Comment by tonihei** [comment]
Can you explain how the TS stream ends up with a PNG or BMP header? This sounds unusual and I'm not sure where this would be an expected media setup. If it's just about preprocessing file before starting playback, then this is something your app has to do itself. You could for example use a custom `DataSource` that filters the first header bytes out when reading the stream.

**Comment by FongMi** [comment]
Here are some introductions
https://blog.csdn.net/ZuoYueLiang/article/details/129995675

**Comment by FongMi** [comment]
I want edit source code directly.
Becasue I make a spider player.
There are many playback formats to deal with.

**Comment by FongMi** [comment]
This problem is relative to https://github.com/google/ExoPlayer/issues/8471
The ts file firest packet is not 0x47, so make it sync fail.
Is there way to optimize find the 0x47 ?

**Comment by tonihei** [comment]
ExoPlayer's TSExtractor is capable of finding the first 0x467 sync byte for a stand-alone TS file. But for HLS, it will only do so for the first segment while identifying the format.

The HLS spec [clearly says](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-3) that *Each Media Segment MUST carry the continuation of the encoded bitstream from the end of the segment with the previous Media   Sequence Number*. So wrapping each segment with additional bytes is invalid for HLS.

You could try to provide a custom `DataSource` that removes the png/bmp headers, but since this is outside of spec-compliant playback, we can't provide 1:1 help with the implementation.
