### ISSUE TITLE
Cast demo not working for HLS

### ISSUE THREAD

**Issue by mohsinDPRO** [androidx/media#452]
### Media3 Version

ExoPlayer 2.18.7

### Devices that reproduce the issue

OnePlus 5T, 6, 6T
Android OS - 9, 10, 11, 12, 13

### Devices that do not reproduce the issue

None that I know of

### Reproducible in the demo app?

Yes

### Reproduction steps

1) Run the demo cast app
2) Select Clear HLS: Angel one title
3) the title shows up on the TV, but It fails to play

There are no logs in the console, which I could share

### Expected result

Expected result is that the media should start playing on the chromecast device as well.
But apart from HLS rest of the streams are casting to the device, but not the HLS

### Actual result

The selected title is shown on the tv screen, even the casting controls show up on the phone from which the casting session was initiated, but the stream does not starts playback on the TV ever

### Media

Clear HLS: Angel One - this is the stream from the demo itself, which is not playing

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by marcbaechinger** [comment]
This is because the cast device or the receiver does not support this HLS stream.

The user here (https://github.com/google/ExoPlayer/issues/11018) says creating your own receiver app solves the problem. I haven't tried that though. If recall trying this out with about 4 different cast devices and it worked on a Next Hub but not on a Chromecast Ultra (first gen). I also think that I was able to play it on an audio only cast device. That's why I think it is device specific. 

I don't expect you will use the ExoPlayer receiver app for your app, so doing this would be part of your app anyways. Sorry for not being able to give you a better answer.

**Comment by mohsinDPRO** [comment]
Ahh, thanks for the quick reply.
As I understand there would be no other way to make the hls streams cast directly to the chromecast device? Can we not explicity set CORS or user-agent or something, which will help get the hls stream be casted

**Comment by mohsinDPRO** [comment]
Hi,
I tried this example at my end on multiple phones and it seems to be casting, just fine, 
there must be some changes in the original sdk vs our exoplayer extension, what can we do to debug it?

**Comment by mohsinDPRO** [comment]
I tried the demo app provided by https://github.com/googlecast/CastVideos-android
The casting here is somehow working with the same chromecast device and phone which I've been using to test the exoplayer cast extension as well.

 - Casting device I am using is chrome cast 1st gen & mi android tv 
 - Phones used for testing is OnePlus 3t, 5T, 6, 6T, Samsung Tablet

Can we look into what different are they doing, which we can do to get our extension work

**Comment by marcbaechinger** [comment]
I have looked into this a bit more closely as it looks we need to clean up/document some things in the cast demo app.
The matters is quite complicated due to the number of involved components end to end.

For a HLS stream being successfully played on a cast device by the demo app the following components are involved.

- `androidx.media3.cast.CastPlayer`: An implementation of `androidx.media3.common.Player` that translates calls to the `Player` to calls to the Android Cast SDK.
- `Android Cast SDK`: The Cast SDK provides an API for Android to create a sender app. It roughly enables an app to send a media URI and metadata to a remote cast device for playback.
- [`Cast receiver app`](url): The [cast receiver](https://developers.google.com/cast/docs/web_receiver) app is a HTML/JS app that runs on the cast device. It receives the commands form the sender app.
- `Media player`: Used by the receiver app and actually plays the media URI (`.m3u8` in the case of HLS).
- `Cast device`: The cast device provides the media codecs with which the player decodes the media.

> Cast demo not working with HLS

For reference the [page with the formats supported](https://developers.google.com/cast/docs/media) by the [default receiver app](https://developers.google.com/cast/docs/web_receiver#default_media_web_receiver) that we are using in the demo app.

I have tested 3 HLS streams

* Apples HLS test stream (HLS/TS): https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8
* CastVideos-android sample: `Designing For Google Cast` (HLS/TS): https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/hls/DesigningForGoogleCast.m3u8
* Angel One (HLS/MP4): https://storage.googleapis.com/shaka-demo-assets/angel-one-hls/hls.m3u8 

with these devices:

* ChromecastUltra
* Chromecast Google TV
* Nest Hub

I tried this with the [*Media3 cast demo*](https://github.com/androidx/media/tree/release/demos/cast) app and with the [*reference Android sender app*](https://github.com/googlecast/CastVideos-android) that you mentioned.

**Test results**

The 2 HLS/TS streams play well with any app and on every device.

The Angel One (HLS/MP4) stream didn't play with neither of these devices and with neither of these sender or receiver apps.

On both Chromecast devices with the Media3 demo app, when I tried to play the `Angel One` stream, the receiver app hung at playback start as you describe. Seeking to another item or similar didn't help to recover. To get out of this state I had to stop casting entirely using the Cast icon top-right.
 
I was able to play the `Angel One` stream on all devices with the [*Shaka player demo*](https://shaka-player-demo.appspot.com/demo/#build=uncompiled) from an Android mobile phone.

From all this I'd say that the reason for the `Angel One` stream failing to play with the Media3 cast demo, is that the media player that is used in the default receiver app can't play HLS/MP4 files. The Shaka demo app uses it's own receiver app with the Shaka media player that [explicitly documents support for HLS/MP4](https://github.com/shaka-project/shaka-player#hls-features).

**Choosing a receiver app**
> Can we look into what different are they doing, which we can do to get our extension work

From what I've seen with the tested HLS streams there is no difference between these two demo sender apps that are using the default receiver app.

I'd focus looking into the receiver app first. [A choice](https://developers.google.com/cast/docs/web_receiver) that you need to do anyway. You can change the receiver app used by the Media3 cast demo by providing your own `OptionsProvider`:

```
public CastOptions getCastOptions(Context context) {
    return new CastOptions.Builder()
        .setReceiverApplicationId(YOUR_RECEIVER_APP_ID)
        // more options
        .build();
  }
```
Reference your class in the `AndroidManifest.xml` of the demo app:

```
<meta-data android:name="com.google.android.gms.cast.framework.OPTIONS_PROVIDER_CLASS_NAME"
        android:value="com.example.DemoOptionsProvider"/>
```

Then test your media with it.

I'm not an expert in that matters, so I can't really give you guidance for this I'm afraid. From the testing above I'd continue looking for a receiver that uses Shaka player if you need HLS/MP4 support.

**Changes for Media3**

If you, or someone else reading this, know how we can use different metadata or use the SDK API  differently to make the `Angel One` stream work with the default receiver app, then we are interested to hear this. I'm not aware of this.

And lastly, I really don't understand why we are not having a working HLS stream in our demo app, but instead one that is not supported. Apologize for the confusion. Besides, I'm afraid but failing is the expected behavior of playing the `Angel One` stream with the demo app. We have no plans in changing the receiver app of the cast demo app in the near future. 

We keep this as an enhancement: 

* clean up HLS samples in [`DemoUtil`](https://github.com/androidx/media/blob/release/demos/cast/src/main/java/androidx/media3/demo/cast/DemoUtil.java)
* document parts of the above and how to change the receiver app in the demo. Probably in the [README](https://github.com/google/ExoPlayer/blob/release-v2/demos/cast/README.md) of the cast demo.
* low prio: consider using a receiver supporting HLS/MP4 streams in the cast demo.

**Comment by mohsinDPRO** [comment]
Thank you for testing out the sample at your end too.

I went ahead and further did the testing of changing the 
The Receiver app id used inside the Exoplayer cast extension is APP_ID_DEFAULT_RECEIVER_WITH_DRM = "A12D4273";
The Receiver app id used inside the Google Cast-Android is APP_ID_DEFAULT_RECEIVER = "CC1AD845";

I tried these on the media3 cast demo [Media3 cast demo](https://github.com/androidx/media/tree/release/demos/cast)
And the results I got was the same, where the app kept crashing after casting. This was happening with mp4, dash & hls as well.

But when I tried the same with the example provided by [Google Cast-Android](https://github.com/googlecast/CastVideos-android) the mp4, dash & hls seems to be working fine.

So after all these testing I have come to believe that the issue seems to be in the exoplayer cast extension, where it is crashing the app after the session is established and the playback is just about to start. 

I am afraid that even after bulding a receiver app, the problem will be the same as I would still be using the exoplayer cast extension. Can you please share a sample where the exoplayer cast extension is used to cast to any working receiver, which would be playing the stream successfully on the chromecast/tv without crashing the app on phone as well.

**Comment by marcbaechinger** [comment]
> I have come to believe that the issue seems to be in the exoplayer cast extension,
> mp4, dash & hls seems to be working fine.
> app kept crashing after casting

Thanks. I have different results based on the testing I did. If the media works on the cast device, the demo app works well.

If you want me to look into this some further, please provide some more details in what exact media URIs you've used, clear repro steps and provide a bug report with the stack traces.

**Comment by mohsinDPRO** [comment]
Hi Marc,

Following are the steps which I have been following to test the casting extension
Devices used for testing: Chromecast 1st generation, MiTV, OnePlus 6T
Android OS:- 10, 11, 12

Results observed:- casting started on TV, but the app kept crashing when using the exoplayer-cast-extension
Whereas, When I use the same m3u8 url on "Google cast-android" the casting worked just fine.
their demo app also worked just fine.

So I have come to the conclusion that there is an issue with the observer within the exoplayer-cast-extension.

Here is the link to the demo app which I am using which is having the issue:- https://drive.google.com/file/d/1iB17ShL7VG3lu9BMDZC7arL5Lv6ouv8n/view?usp=sharing

Here is the link in which the casting seems to be working just fine:-
https://drive.google.com/file/d/1qLPNRt_uRaOSYW50KwjW9MIaqT9ekrA9/view?usp=sharing

**Comment by marcbaechinger** [comment]
Please provide complete information as requested in the issue template. The issue template can be found [here](https://github.com/google/ExoPlayer/blob/release-v2/.github/ISSUE_TEMPLATE/bug.md). If you're unable to share bug reports or test content publicly, please send them to dev.exoplayer@gmail.com using a subject in the format "Issue #1234", where "#1234" should be replaced with your issue number. Please also update this issue to indicate you’ve done this.

**Comment by shaikhmohsink** [comment]
Hi Marc,

I went ahead and tried to find the root cause of the crash I was getting after the casting session was active.
Here are my findings, hope full this will help resolve the actual crash in media or exoplayer's cast extension.

I took the example of [Google Cast-Android](https://github.com/googlecast/CastVideos-android) and was able to successfully create the issue that is happening on the exoplayer's cast extension.

And the conclusion that I came to, was the missing images that are to be added to the MediaMetadata object which is wrapped by the MediaInfo and sent to the connected remoteMediaClient.


Here is the piece of code which worked for me, maybe using these changes it could resolve the crashes in the exoplayers cast-exension as well.


`public void castVideo(String videoURL, String strTitle) {
        MediaMetadata movieMetadata = new MediaMetadata(MediaMetadata.MEDIA_TYPE_MOVIE);

        movieMetadata.putString(MediaMetadata.KEY_TITLE, strTitle);
        movieMetadata.putString(MediaMetadata.KEY_SUBTITLE, "");
        if(playerThumb != null && playerThumb.length() > 0)
            movieMetadata.addImage(new WebImage(Uri.parse(playerThumb+"/"+480+"/"+270)));
        else
            movieMetadata.addImage(new WebImage(Uri.parse("http://via.placeholder.com/5x5")));
        if(playerThumb != null && playerThumb.length() > 0)
            movieMetadata.addImage(new WebImage(Uri.parse(playerThumb+"/"+887+"/"+1200)));
        else
            movieMetadata.addImage(new WebImage(Uri.parse("http://via.placeholder.com/5x5")));

        MediaInfo mediaInfo = new MediaInfo.Builder(videoURL)
                .setStreamType(MediaInfo.STREAM_TYPE_BUFFERED)
                .setContentType("application/x-mpegURL")
                .setMetadata(movieMetadata)
                .build();
        RemoteMediaClient remoteMediaClient = mSessionManager.getCurrentCastSession().getRemoteMediaClient();
        remoteMediaClient.load(new MediaLoadRequestData.Builder().setMediaInfo(mediaInfo).build());

    }`

**Comment by marcbaechinger** [comment]
Thank you!

I'm not sure what your code does differently to what the demo app does:
https://github.com/androidx/media/blob/release/libraries/cast/src/main/java/androidx/media3/cast/DefaultMediaItemConverter.java#L93

> these changes it could resolve the crashes in the exoplayers cast-exension as well.

I would be interested to see a stack trace of this crash. I was asking for this already. I'm able to play the media that is in included in the demo app. Can you provide me with a stack trace of the crash you are mentioning. Another way to make this actionable for us, would be to have repro steps with the demo app that explains how this can be reproduced.
