### ISSUE TITLE
java.lang.NoClassDefFoundError: androidx.media3.exoplayer.ExoPlayer$Builder$$ExternalSyntheticLambda11

### ISSUE THREAD

**Issue by DoctorDooom** [androidx/media#453]
### Media3 Version

Media3 1.0.2

### Devices that reproduce the issue

50% :  Oppo
22% : Huawei
22% : Samsung
6% : Lenovo Mobile

### Devices that do not reproduce the issue

other devices

### Reproducible in the demo app?

No

### Reproduction steps

i got the error in firebase dashboard Sorry

### Expected result

no ANR

### Actual result

the app crashes

### Media

self hosted songs

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by icbaker** [comment]
Have a look through previous issues, there are various suggested fixes depending on the exact root cause you're experiencing: https://github.com/search?q=repo%3Agoogle%2FExoPlayer+noclassdeffounderror&type=issues

Specifically, try depending on android-specific Guava if you currently depend on the JRE variant: https://github.com/google/ExoPlayer/issues/9704#issuecomment-975390727
