### ISSUE TITLE
M3U8(HLS) Streams are not showing .vtt file subtitles in video when trying to play it on Android TV from Android Mobile by connecting Android TV Chromecast.

### ISSUE THREAD

**Issue by ajayhack** [androidx/media#513]
### Version

ExoPlayer 2.18.5

### Devices that reproduce the issue

Android TV's including
Mi Android TV

### Reproducible in the demo app?

Yes

### Reproduction steps

We are sharing Stream and also .vtt subtitle file on mail to reproduce this issue by casting it on Android TV. 

### Expected result

.vtt file subtitles should show on Adnroid TV Chromecast VideoPlayback for HLS(Stream).

### Actual result

.vtt file subtitle not showing when casting HLS(Stream) on Android TV.

### Media

NA

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
What happens on the Cast device is out of the control of our libraries. Please see [this reply](https://github.com/androidx/media/issues/509#issuecomment-1628584002) to a very similar sounding problem.

Is this a recent issue? Given this the second issue within a few days where this was reported, I wonder if was caused by some update on the Cast device.

**Comment by ajayhack** [comment]
@tonihei 
We are following this Google Cast Official Doc : https://developers.google.com/cast/docs/android_sender/media_tracks to send subtitle information to Cast Device but then also it's not working , Can you explain why official doc thing not working?

Also we are not using Custom Receiver , only Default Receiver is used on Cast Device.
