### ISSUE TITLE
Duplicate text in 1.1.0 release

### ISSUE THREAD

**Issue by TacoTheDank** [androidx/media#515]
I didn't know what template to use, so hopefully this is fine.

In https://github.com/androidx/media/releases/tag/1.1.0 and https://github.com/androidx/media/blob/release/RELEASENOTES.md#110-2023-07-05, there is duplicated text under the "Session" section, which needs to be fixed.

The duplicated text in question:

- Add default implementation to MediaSession.Callback.onAddMediaItems to allow requested MediaItems to be passed onto Player if they have LocalConfiguration (e.g. URI) (https://github.com/androidx/media/issues/282).
- Add "seek to previous" and "seek to next" command buttons on compact media notification view by default for Android 12 and below (https://github.com/androidx/media/issues/410).

Thank you.

**Comment by tonihei** [comment]
Thanks for reporting, I'll fix this!

**Comment by TacoTheDank** [comment]
@tonihei It doesn't seem to have been fixed yet in https://github.com/androidx/media/blob/release/RELEASENOTES.md#110-2023-07-05, unless there's a commit that hasn't been pushed or made public?

**Comment by tonihei** [comment]
It has been fixed in https://github.com/androidx/media/releases/tag/1.1.0 and the internal commit to fix the release notes file itself hasn't been uploaded yet. It should appear here the next time someone triggers an upload (about once a week). But note that the fix will be in the "main" branch and only after we've done a 1.1.1 or 1.2.0 release it will also appear to be fixed on the "release" branch.
