### ISSUE TITLE
Why Exoplayer:playback thread's loading at Android 14 is higher than Android 13?

### ISSUE THREAD

**Issue by guczOasis** [androidx/media#517]
I found a power consumption issue about Exoplayer at Android 14.The increment is about 10mA.
When I play a same 1080P mp4 video with 2.18.6 or 2.13.2 Exoplayer demo apk.The loading of Exoplayer:playback thread at Android 14 is higher than Android 13.And I got the mips data of all threads when playback the video.The data of Exoplayer:playback thread is also larger than Android 13.
Could you help me to confirm this problem?

**Comment by tonihei** [comment]
Can you explain how you measure this exactly (=what do we need to do to observe the same effect?)

CPU measurements are also quite difficult to compare because the actual usage depends on operating system level scheduling and CPU affinity, CPU frequency and similar properties. The app itself may also be compiled differently or in different stages of JIT compiler optimizations.

**Comment by guczOasis** [comment]
Thanks for your reply.We found the reason that it's the difference between debug apk and release apk.It's normal when we use release apk.
