### ISSUE TITLE
Player stops when discontinuity is found (chunks are skipped)

### ISSUE THREAD

**Issue by mreigosa** [androidx/media#519]
I'm getting this response when playing content using the library:

```#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:539646
#EXT-X-DISCONTINUITY-SEQUENCE:539644
#EXT-X-DISCONTINUITY
#EXTINF:1.28,
media_w1765802363_539646.ts
#EXT-X-DISCONTINUITY
#EXTINF:1.28,
media_w1765802363_539647.ts
#EXT-X-DISCONTINUITY
#EXTINF:1.28,
media_w1765802363_539648.ts
```

I'm using the library to play some live videos from webcams. It works for all of them but not for this one. I found that this one is including the `#EXT-X-DISCONTINUITY` which is causing the player to stop playing. 

❓ I would like to know if that is the expected behavior or if this might be a bug.

I tried using the error listener. Restarting the player when the `BehindLiveWindowException` is thrown. With this the player is restarted and the next 3 chunks are downloaded. But as with the first request, it plays the first chunk and gets frozen again.

**Comment by tonihei** [comment]
ExoPlayer generally supports `#EXT-X-DISCONTINUITY` tags in HLS. I assume that the player gets stuck due to some other reason related to the media segments itself. Would you be able to share this stream with us? You can send an email to android-media-github@google.com with subject "#519" and report back here once you've done that if you like.

**Comment by mreigosa** [comment]
Hello.

I saw an email moving the question to stale because I didn't provide
information. I sent the email days ago. I sent it again now just in case.
Could you confirm you receive it?

Cheers.

**Comment by tonihei** [comment]
We don't monitor the email address actively, so I didn't realize you sent this information until your update here.

It looks it has nothing to do with the discontinuity tags, but rather with the fact that your playlist declares a target duration of a single sample of 10 seconds (`#EXT-X-TARGETDURATION:10`), but the entire playlist is never longer than 4-5 seconds. This means the player will get stuck after playing 4-5 seconds because it has logic to not reload playlists within the duration of a single sample.

I don't think the playlist is technically wrong (just a bit unusual), so I'll mark it as a bug because the player should be able to detect and handle this correctly.

**Comment by tonihei** [comment]
Actually, the reload algorithm is prescribed by the HLS spec and the spec also says that
```
The server MUST NOT remove a Media Segment from a Playlist file
   without an EXT-X-ENDLIST tag if that would produce a Playlist whose
   duration is less than three times the Target Duration.  Doing so can
   trigger playback stalls.
```
The mentioned playback stall is exactly what happens here because old segments are removed too early. So it's more bad media. If you control the playlist creation, you can just make the segments available for longer and the problem should be fixed.
