### ISSUE TITLE
create ConcatenatingMediaSource2 from mediaItem

### ISSUE THREAD

**Issue by suman-selegic** [androidx/media#529]
```kotlin
  val mi = MediaItem.Builder().run {
            setMediaId(playItem.id)
            setRequestMetadata(
                MediaItem.RequestMetadata.Builder()
                    .setExtras(Bundle().apply {
                        putString("artwork_uri", imageUri)
                        putString("title", playItem.name)
                        putString("album", playItem.bookName)
                        putString("artist", playItem.author)
                        putString("description", playItem.description)
                    }).build()
                    .setMediaUri(Uri.parse(audioUri)).build())
            build()
        }  
  val ms = ConcatenatingMediaSource2.Builder()
      .useDefaultMediaSourceFactory(requireContext())
      .add(mi)
      .add(mi)
      .build()
  player.setMediaItem(ms.mediaItem)
```
I simply want to concatenate two media items into a single timeline.
However the above code doesn't work, it fails assertion that `mi.liveConfiguration` is not null on the `.add(mi)`  line
```
java.lang.NullPointerException
at androidx.media3.common.util.Assertions.checkNotNull(Assertions.java:155)
at androidx.media3.exoplayer.source.DefaultMediaSourceFactory.createMediaSource(DefaultMediaSourceFactory.java:422)
at androidx.media3.exoplayer.source.ConcatenatingMediaSource2$Builder.add(ConcatenatingMediaSource2.java:157)
```
the player instance is from a background MediaSession

I would be grateful for any pointers to make this work.

**Comment by icbaker** [comment]
> However the above code doesn't work, it fails assertion that `mi.liveConfiguration` is not null on the `.add(mi)` line

What version of the library are you using? `DefaultMediaSourceFactory.java:422` in 1.0.2 looks like it's failing because `mediaItem.localConfiguration` is null (not `liveConfiguration`) (L422 doesn't seem to match a `checkNotNull` invocation in 1.1.0):
https://github.com/androidx/media/blob/2fc189d6a40f116bd54da69ab9a065219f6973e7/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/source/DefaultMediaSourceFactory.java#L422

I see you're using `MediaItem.requestMetadata`. This is generally used when passing media items to a `MediaController` (rather than to the player directly powering the `MediaSession`). In this case apps transform the `RequestMetadata` into a 'playable' `MediaItem` (i.e. with `localConfiguration != null`) in [`MediaSession.Callback#onAddMediaItems`](https://developer.android.com/reference/androidx/media3/session/MediaSession.Callback#onAddMediaItems(androidx.media3.session.MediaSession,androidx.media3.session.MediaSession.ControllerInfo,java.util.List%3Candroidx.media3.common.MediaItem%3E)).

You are passing your `MediaItem` instance to `DefaultMediaSourceFactory` (via `ConcatenatingMediaSource2`), so it never goes via `MediaSession.Callback#onAddMediaItems` or any similar logic to set the `localConfiguration`. You therefore need to ensure this is non-null yourself. You can do this by using [`MediaItem.Builder.setUri`](https://developer.android.com/reference/androidx/media3/common/MediaItem.Builder#setUri(java.lang.String)) (instead of `MediaItem.RequestMetadata.Builder.setMediaUri`).

----

```
  val ms = ConcatenatingMediaSource2.Builder()
      .useDefaultMediaSourceFactory(requireContext())
      .add(mi)
      .add(mi)
      .build()
  player.setMediaItem(ms.mediaItem)
```

Building a `MediaSource` and then calling `player.setMediaItem(mediaSource.getMediaItem())` will generally not do what you expect. The [`MediaSource.getMediaItem()`](https://developer.android.com/reference/androidx/media3/exoplayer/source/MediaSource#getMediaItem()) method is documented as:
> Should not be called directly from application code.

If you are building `MediaSource` instances manually you need to use `ExoPlayer.setMediaSource` methods to pass them to the player: https://developer.android.com/guide/topics/media/exoplayer/media-sources

If you are trying to do this on a `MediaController` (and therefore the `setMediaSource` methods are not available), that's expected - you cannot configure a `MediaSource` instance on the controller side and pass it over the controller -> session connection. If you need to manually build `MediaSource` instances you need to rearchitect your app so that all the `MediaSource` instantiation happens on the session side (where the `ExoPlayer.setMediaSource` methods should be available on the underlying ExoPlayer instance).

**Comment by suman-selegic** [comment]
@icbaker thank you for the explanation, So is there a way I can `setMediaSource` on a `MediaController`?

**Comment by icbaker** [comment]
> thank you for the explanation, So is there a way I can `setMediaSource` on a `MediaController`?

No, `MediaSource` is only a concept on `ExoPlayer`. `MediaController` is a `Player` (not `ExoPlayer`).

If you are building both the controller and session then, as I said above, you need to move the `MediaSource` instantiation to the session side.

If you **aren't** building the session (you're only building the controller) then you can't guarantee the session you're connecting to is backed by `ExoPlayer` (it could be a different `Player` implementation), so it makes sense you can't try and pass a `MediaSource` to it.

----

> How can I wrap around the background `MediaSession` so that I can pass custom parameters to the media controller? From what I've seen only custom commands seem passable.

You could use [`MediaSession.setSessopmExtras`](https://developer.android.com/reference/androidx/media3/session/MediaSession#setSessionExtras(androidx.media3.session.MediaSession.ControllerInfo,android.os.Bundle)) and implement [`MediaController.Listener.onExtrasChanged`](https://developer.android.com/reference/androidx/media3/session/MediaController.Listener#onExtrasChanged(androidx.media3.session.MediaController,android.os.Bundle)) on the controller side.

**Comment by suman-selegic** [comment]
I am building both the session and controller. so it looks like I have to build this functionality on the session side.

>You could use [MediaSession.setSessionExtras](https://developer.android.com/reference/androidx/media3/session/MediaSession#setSessionExtras(androidx.media3.session.MediaSession.ControllerInfo,android.os.Bundle)) and implement [MediaController.Listener.onExtrasChanged](https://developer.android.com/reference/androidx/media3/session/MediaController.Listener#onExtrasChanged(androidx.media3.session.MediaController,android.os.Bundle)) on the controller side.

Sorry, I meant pass custom parameters from media controller to the Media session, so that I can Instantiate the MediaSource from the session side and add to the playlist. I realize now that I can do that by passing a bundle along with the custom command.

but this is also very useful to know. I'll start working on this.

**Comment by icbaker** [comment]
> Sorry, I meant pass custom parameters from media controller to the Media session, so that I can Instantiate the MediaSource from the session side and add to the playlist. I realize now that I can do that by passing a bundle along with the custom command.

Ah right - you could also use `MediaItem.requestMetadata.extras`, if you want to provide info about how a particular `MediaItem` should be turned into a `MediaSource` - and then handle this in the custom `MediaSource.Factory` you will probably end up using in your `ExoPlayer` instance.

Closing this issue because I think the questions here have been answered - please file new issues if you have new questions.
