### ISSUE TITLE
Using Transformer is it possible to speed up the video?

### ISSUE THREAD

**Issue by jordond** [androidx/media#559]
Say I had a `Composition` of a dozen video files. Is there a way to set the speed? Like speed up the video by 2x, etc.

**Comment by kim-vde** [comment]
Yes, it is possible by doing the following:

1. Create a new video speed change effect:
    - Create a new `SpeedChangeShaderProgram` that extends `BaseGlShaderProgram`, uses a `GlProgram` that just copies the frames, and overwrites `queueInputFrame()` by dividing the `presentationTimeUs` by the speed.
    - Create a new `SpeedChangeEffect` that implements `GlEffect` and returns a `SpeedChangeShaderProgram` in `toGlShaderProgram()`.
2. Set up the `Composition`:
    - For each `EditedMediaItem`, add the effect created above in the video effects and a `SonicAudioProcessor` with the desired speed in the audio effects.

This approach has a few limitations:
- Audio speed change is slightly inaccurate so it could be possible that your audio and video tracks are drifting apart if the output video is very long.
- The video speed change effect wouldn't work if you pass it to `ExoPlayer.setVideoEffects()` because we only support video effects that do not change the timestamps for preview.

I have implemented the `SpeedChangeEffect` and `SpeedChangeShaderProgram` so that you don't have to implement the first part, but it will be a few days until they are added to the main branch. They should be part of the next release.
