### ISSUE TITLE
Unable to play HLS stream without any error

### ISSUE THREAD

**Issue by lguipeng** [androidx/media#567]
Hi, We are running into an issue with TS files in our HLS stream. When TsExtractor unpacks, the CRC32 check inside will fail, resulting in a direct return without any error. If I modify this part of the logic and ignore the result of the verification, it will be able to play normally. Because other platforms such as iOS's AVPlayer can be played directly, I would like to ask if I can ignore the checksum and play, will it cause other problems?
Below is my TS file, thanks
[1690427132198.ts.zip](https://github.com/androidx/media/files/12272844/1690427132198.ts.zip)

**Comment by tianyif** [comment]
Hi @lguipeng,

The CRC32 verifies the correctness of the data, and I think it is working as intended that we [discard the invalid](https://github.com/androidx/media/blob/release/libraries/extractor/src/main/java/androidx/media3/extractor/ts/SectionReader.java#L128) section. I would recommend to use a valid media instead of ignoring the verification.
