### ISSUE TITLE
Exoplayer eventually thows ExoPlaybackException: MediaCodecAudioRenderer  on slow network

### ISSUE THREAD

**Issue by fourofspades** [androidx/media#585]
### Version

Media3 1.1.0

### More version details

Media3.1.1.0

### Devices that reproduce the issue

Android Emulator
Google Pixel 7

### Devices that do not reproduce the issue

None, to my knowledge

### Reproducible in the demo app?

Not tested

### Reproduction steps

configure app to play a M4A audio stream on a network with insufficient bandwidth.
Wait
Exploplayer throws exception and never resumes when network becomes good.

### Expected result

Exoplayer starts playing when a network of sufficient speed is available and a buffer is complete.

### Actual result

Exoplayer gives up eventually.

### Media

http://cast1.asurahosting.com:8621/med

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by fourofspades** [comment]
[logcat.txt](https://github.com/androidx/media/files/12358469/logcat.txt)

**Comment by tonihei** [comment]
Thanks for reporting. The interesting log line is 
```
[c2.android.aac.decoder] previous call to queue exceeded timeout
```

It seems that the underlying codec on these devices has an internal timeout that automatically throws an exception if no new data is queued for a long time. Unfortunately, the error isn't marked as recoverable by the codec, so ExoPlayer can't retry automatically. This issue has been reported before for this codec and I'm trying to follow up on the existing internal bug, but any fix will be done via OS software updates. 

For your app, I assume it's acceptable to let the user trigger a retry if needed or you can retry automatically within your app (by calling `player.prepare()` again)? 

In any case, this means I can close this issue because there doesn't seem to be a solution we can put into the player code (the error from the codec unfortunately uses a generic error code that doesn't tell us anything).
