### ISSUE TITLE
Prevent re-requesting DRM licence on BehindLiveWindowException/ERROR_CODE_BEHIND_LIVE_WINDOW

### ISSUE THREAD

**Issue by darrentaft** [androidx/media#596]
We're serving live Widevine protected DASH streams in our app, with an availability window of only 42 seconds.  This means it's not uncommon for clients to trigger a BehindLiveWindowException with error code ERROR_CODE_BEHIND_LIVE_WINDOW on poorer connections where buffering means they've slipped further behind live.

The advice for this seems to be to simply catch the error and call:

player.seekToDefaultPosition()
player.prepare()

However this results in a call to request the DRM licence again.  The licence URLs we use are signed, and only last 30 seconds. Thus by the time the player attempts to use it again, it has expired and the play session fails with a licence error instead.

Given that I'm not re-creating the player, I'd have hoped that it would continue to use the existing licence that it had already loaded.  Is there a way to force the existing DrmSession to be reused for this stream re-start?

**Comment by marcbaechinger** [comment]
When a playback exception is thrown, the player is put back into `STATE_IDLE`. That probably closes the DRM session also.
Assigning to @icbaker who knows more details.

**Comment by icbaker** [comment]
Marc's theory sounds right - the DRM session and all related machinery (including the licence) will be released by the Player if it goes to the `IDLE` state.

If the problem is that the license URL is now stale, what about updating to a 'fresh' URL when requesting the license when re-preparing? You can do this by using `ResolvingDataSource` inside a `HttpMediaDrmCallback` and providing this when you build your `DefaultDrmSessionManager` instance.

See here for more info about `ResolvingDataSource` https://developer.android.com/guide/topics/media/exoplayer/customization#customizing_server_interactions

Or you could revisit the decision on your side to make your DRM license URLs only valid for 30s.

**Comment by darrentaft** [comment]
We're dealing with premium TV channels and movies, so unfortunately the studios require our content and licence URLs to be signed with 30 second expiry.

Requesting updated URLs is an expensive operation, so that would need to be a last resort.

Are there any options to override this behaviour?  e.g. by overriding the segment selection to just catch up instead of throwing the exception? It seems strange to me that the default behaviour in this (surely very common scenario) is to die, with no options otherwise?

**Comment by icbaker** [comment]
Once the `BehindLiveWindowException` has been thrown, it's basically too late - so if you want to ensure the player stays prepared you need to try and avoid the exception being thrown in the first place.

Some ideas:

* You can try enabling automatic speed adjustment, so if the player falls behind the live edge due to rebuffering it will speed up a bit to catch up: https://developer.android.com/guide/topics/media/exoplayer/live-streaming#playback_speed_adjustment
* Since you know your live window is 42s long, you can detect when you're nearing the trailing edge of that window and proactively call `seekToDefaultPosition` - e.g. when you detect playback is 30s behind the live edge.

**Comment by darrentaft** [comment]
In trying to add monitoring for this issue, I've discovered bug #607 - as the player is always running at the trailing edge of the manifest, it only takes a single 2 second buffering event to cause playback to fail.
Ironically, it's the playback speed adjustment (DefaultLivePlaybackSpeedControl) that is causing it to fail, by forcing the target offset to greater than the manifest offers.

**Comment by darrentaft** [comment]
Having found the cause for #607 I've now got a satisfactory solution using automatic speed adjustment.  Thanks for all the input.
