### ISSUE TITLE
Modify headers of http request that will follow a redirect received by a stream request with Cronet

### ISSUE THREAD

**Issue by vcamargo** [androidx/media#628]
When using Cronet on Exoplayer, is it possible to access to the `UrlRequest.Callback` of a `CronetDataSource` ?

In case of a response to a stream request that contains a redirect URL, I'd like to access the headers of the request that will follow the redirect. As Cronet will copy all the headers of the original request to the subsequent one I'd need to modify the headers in that case. Is it possible?

I noticed that `Okhttp`, and `DefaultHttpDataSource` doesn't copy the headers from the original request in a redirect scenario, so I wonder if there's a way of achieve the same result with Cronet.

For example the following stream request with a custom header parameter `My-Header: custom-value`

```
GET uamp/The_Kyoto_Connection_-_Wake_Up/01_-_Intro_-_The_Way_Of_Waking_Up_feat_Alan_Watts.mp3 HTTP/1.1
Host: storage.googleapis.com
Connection: keep-alive
Accept-Encoding: gzip, deflate
My-Header: custom-value
```

It receives a 302 response with a redirect

```
HTTP/1.1 302 Found
Date: Fri, 01 Sep 2023 12:12:31 GMT
Content-Length: 0
Connection: keep-alive
cache-control: private, max-age=0, no-cache
location: https://redirected-url/uamp/The_Kyoto_Connection_-_Wake_Up/01_-_Intro_-_The_Way_Of_Waking_Up_feat_Alan_Watts.mp3
```

Then the request that will follow the redirect have the header parameter `My-Header: custom-value`, but I want to avoid that.

```
GET uamp/The_Kyoto_Connection_-_Wake_Up/01_-_Intro_-_The_Way_Of_Waking_Up_feat_Alan_Watts.mp3 HTTP/1.1
Host: redirected-url
Connection: keep-alive
Accept-Encoding: gzip, deflate
My-Header: custom-value
```

**Comment by icbaker** [comment]
media3's `CronetDataSource` usually delegates redirect logic to Cronet's [`UrlRequest.followRedirect()`](https://developer.android.com/guide/topics/connectivity/cronet/reference/org/chromium/net/UrlRequest.html#followRedirect()) here (except when switching from POST to GET or if needing to preserve cookie headers):
https://github.com/androidx/media/blob/8d7d129066e39539c4eed3513b25d3d246540d1b/libraries/datasource_cronet/src/main/java/androidx/media3/datasource/cronet/CronetDataSource.java#L1123-L1135

`DefaultHttpDataSource` similarly delegates to `HttpUrlConnection` via [`setInstanceFollowRedirects(boolean)`](https://developer.android.com/reference/java/net/HttpURLConnection#setInstanceFollowRedirects(boolean)) here:
https://github.com/androidx/media/blob/8d7d129066e39539c4eed3513b25d3d246540d1b/libraries/datasource/src/main/java/androidx/media3/datasource/DefaultHttpDataSource.java#L667

`OkHttpDataSource` has no special handling for redirects, so they're completely handled by the underlying OkHttp stack.

So this difference you're seeing is in the underlying HTTP stacks (rather than in media3 logic), so if you want Cronet to clear headers when redirecting you should file that request against Cronet: https://bugs.chromium.org/p/chromium/issues/list
