### ISSUE TITLE
Is it possible to convert an image to a video using Transformer?

### ISSUE THREAD

**Issue by jordond** [androidx/media#657]
Basically I have some videos and images I want to concatenate into a single video. But the photos would need to be converted to a video (with no audio) and a set duration (ex 5 seconds).  Is something like this possible?

**Comment by tof-tof** [comment]
Yes! Transformer has a image transcoding feature so that when you provide an image asset, it transcodes it into a video of your specified duration and frame rate, whilst concatenating it with any other video or image assets you specifiy. To do what you describe, you can do the following:

1. For each video/image asset, create an [`EditedMediaItem`](https://github.com/androidx/media/blob/release/libraries/transformer/src/main/java/androidx/media3/transformer/EditedMediaItem.java):
   * For images, you can set a duration and frame rate 
```
  new EditedMediaItem.Builder(MediaItem.fromUri(uri))
        .setDurationUs(5* C.MICROS_PER_SECOND)
        .setFrameRate(frameCount)
        .build()
 ``` 
(note that these setters have no effect for non-image assets)

 2. Add all those assets to a [`EditedMediaItemSequence`](https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/transformer/src/main/java/androidx/media3/transformer/EditedMediaItemSequence.java#L55)
 3. Add that Sequence to a [`Composition`](https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/transformer/src/main/java/androidx/media3/transformer/Composition.java) which you can pass into `Transformer.start`

One thing to note: for Transformer to detect that an `EditedMediaItem` is an image asset either the uri must end with an image extension (ex. "sample.png") or you must build a [MediaItem with an image mime type](https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/common/src/main/java/androidx/media3/common/MediaItem.java#L166). 

See [`TransformerMixedInputEndToEndTest`](https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/transformer/src/androidTest/java/androidx/media3/transformer/TransformerMixedInputEndToEndTest.java) for more detailed examples of this.
