### ISSUE TITLE
MP4 video play error: Leaf atom defines extended atom size (unsupported).

### ISSUE THREAD

**Issue by Caij** [androidx/media#667]
### Version

ExoPlayer 2.18.2

### Devices that reproduce the issue

* xiaomi 11 Android 13
* all devices

### Reproducible in the demo app?

Yes

### Reproduction steps

play source

### Expected result

play success

### Actual result

play error Leaf atom defines extended atom size (unsupported).

### Media

https://video.twimg.com/amplify_video/1704654962834214912/vid/avc1/1280x720/50-birosgYs_rDGX.mp4?tag=14

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by rohitjoins** [comment]
Hi @Caij,

This failure occurred because the `mvhd` leaf atom defines an extended atom size for the media URL above.

The structure of the `mvhd` box is defined by the ISO/IEC 14496-12 standard, and it has a fixed format with specific fields, such as creation time, modification time, time scale, and others. The structure and length of these fields are well-defined by the standard, and there is no provision for extending the header length or using a `wide` atom in the `mvhd` box itself.
