### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by tzugen** [androidx/media#67]
Hi there!

Can you share a roadmap of the releases? When do you plan to come out of alpha?
Will media3 eventually supersede exoplayer?

**Comment by marcbaechinger** [comment]
We can't share a concrete roadmap yet I'm afraid.

Eventually ExoPlayer will be published under `androidx.media3` and the old package/repository `com.google.android.exoplayer2` will go away. The actual code is identical but will be published with a different package/module structure. The two repositories will co-exist in parallel for a while to provide some time for developers to migrate. We can't share a timeline for this because it hasn't be decided yet.

**Comment by tzugen** [comment]
Thank you! That helps for making a choice...
