### ISSUE TITLE
Increase Buffer Size for Decrypted Audio in ExoPlayer

### ISSUE THREAD

**Issue by lemondoglol** [androidx/media#718]
Hi team, we are currently facing audio stuttering issue for some low end devices. 

Here are the things that we already tried:
- our ExoPlayer version 2.16.1
- Enabled AsyncronousMode for MediaCodecAdapter
- Increased minBufferMs (set to 30mins) and maxBufferMs (set to 60 mins) for LoadControl
- implemented onAudioUnderrun to check when the stuttering happens, and then use L3. (we used to use L1, but notice a lot of users are having stuttering issue) Changing to L3 can improve the stuttering issue, but we are still seeing users having this stuttering issue

As a result, we looked into the code, realized that for Widevine, the same buffer is 50s, but it's filled with encrypted content. Decryption here is done just in time as the player pulls audio through the pipeline. The buffers here are short (<= 1 s). Is there anyway we can increase that buffer size? Or Is there any other ways we can fix this stuttering issue?

**Comment by lemondoglol** [comment]
here are the additional updates:
- we are now using L1 for testing for the following cases
- so recently, we found that increasing AudioSink MIN_BUFFER_DURATION_US to 1s can significantly reduced stuttering. (now only 20% of the time it will be detected by onAudioUnderrun callback, but we dont hear stuttering)
- we also tried to bump that field to 5s, but doing so will increase a lot of weird behaviors when playing in higher playback speed (the buffer size in that case will auto times by the playback speed) and seeking. 
- hence we would like to know if there is any **official suggestions** for what is the best value for MIN_BUFFER_DURATION_US? 

also here are some related issues:
- https://github.com/google/ExoPlayer/issues/6751 glitch when bufferSize is set to too big
- https://github.com/google/ExoPlayer/issues/8891 where you guys introduced the method where we can configure min buffer
- https://github.com/google/ExoPlayer/issues/9712 AudioTrack fail when buffer size is too big

Please let us know if there are any other information you need. Or is there any other suggestions. Thanks in advance!

**Comment by tonihei** [comment]
`DefaultAudioTrackBufferSizeProvider` already encapsulates many of the "official" suggestions.

The default logic for regular PCM playback is roughly:
 - Use `4 * AudioTrack.getMinBufferSize(..)`. This is to ensure there is sufficient buffer in general to not underrun playback during normal streaming. The factor `4` can be customized via `setPcmBufferMultiplicationFactor`
 - Constrain the effective buffer duration to between `250` and `750` ms. This value influences how quickly changes to audio output can take effect. For example, playback speed changes mid-playback are always "delayed" by the duration of the current buffer. These min and max duration constraints can be customized via `setMin/MaxPcmBufferDurationUs`.
 - Further correctness adjustments to not use less than `AudioTrack.getMinBufferSize(..)` and round size to an integer number of frames.
- A fallback mechanism that retries `AudioTrack` setup failures with `1 MB` of buffer if the original requested buffer was larger than `1 MB`. 

The problem you are seeing with DRM protected playback is likely caused by the fact the decoder blocks while it's decrypting the samples. Using asynchronous mode on `MediaCodecAdapter` should already help to unblock the playback thread, but there is still an inevitable time delay until new samples are ready. If it can't produce new buffers fast enough, the `AudioTrack` buffer will eventually run out and you see an underrun/stuttering. Increasing the AudioTrack buffer size decreases the likelihood of this happening if the delays are only temporary, but it wouldn't help if the decoding process is generally not fast enough.

- You could try to conditionally increase the buffer size on these low-end devices. But it comes with the mentioned problems of additional delays when applying changes (like speed changes) and potential `AudioTrack` failures if the size becomes too large. For this reason, I wouldn't change our default logic. 
- Some devices may simply not be performant enough to stream DRM-protected content efficiently. Trying to force L3 may help (although audio is mostly using L3 paths anyway, but it will help for video), or reduce the maximum bitrate/resolution/samplerate, if you have a choice of doing so, to make the life of the decoder easier. We also have a pending feature request to use the number of dropped video frames or audio underruns to automatically switch down in case the device is not capable of sustaining a high performance for a stream (internal: b/110519506).

**Comment by tonihei** [comment]
I think the question was answered. One final comment for future readers:

> playback speed changes mid-playback are always "delayed" by the duration of the current buffer

This statement is only true for ExoPlayer's built-in speed adjustment processor. When enabling AudioTrack based speed adjustment with `DefaultRenderersFactory.setEnableAudioTrackPlaybackParams`, the adjustment takes place almost immediately. The potential delay still applies to all other types of audio processing though.
