### ISSUE TITLE
How to detect that the user dismissed the notification of the MediaLibraryService?

### ISSUE THREAD

**Issue by yannallain** [androidx/media#72]
Hello, 

I'm trying the current alpha and when I swipe the media notification, the media is not stopped.

What is the good way to be informed that the user swiped the media notification in order to stop the media?

Thanks

**Comment by marcbaechinger** [comment]
If you say the `media is not stopped` then you mean `paused` I think. In this case you are on API level 30 or higher and this means that you have a [mini player in the Quick Settings](https://android-developers.googleblog.com/2020/08/playing-nicely-with-media-controls.html) that you can make appear when pulling down the notification drawer down a bit further after dismissing. The mini player can't be dismissed. Below API 30 the notification can not be dismissed when media is playing because then the service is started in the foreground.

In case you are technically referring to the `PendingIntent` that can be set with `NotificationCompat.builder.setDeleteIntent(PendingIntent)`. This intent is not used with `MediaLibraryService`. Main reason for this is that the delete event is not delivered on these API levels with a mini player (I just tested on a device running S to confirm my guess and I didn't receive any pending intents, while I received them on API ).

**Comment by yannallain** [comment]
Great, thank you very much for your answer @marcbaechinger. 

You confirmed my doubts concerning the delivery of the delete event for the `NotificationCompat.builder.setDeleteIntent(PendingIntent)`.
