### ISSUE TITLE
Overlay GIF on Video using Transform 

### ISSUE THREAD

**Issue by pawaom** [androidx/media#735]
### [REQUIRED] Use case description

Overlay GIF on Video using Transform with ability to control animations based on Time using various features in 
[OverlaySettings.java](https://github.com/androidx/media/blob/main/libraries/effect/src/main/java/androidx/media3/effect/OverlaySettings.java)
Like 

alphaScale
backgroundFrameAnchor
overlayFrameAnchor
scale
rotationDegrees

### Proposed solution
[youtube create.](https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.producer)

### Alternatives considered
 [youtube create ](https://play.google.com/store/apps/details?id=com.google.android.apps.youtube.producer) already has these features

**Comment by tof-tof** [comment]
So Transformer doesn't support GIFs out of the box, but there are various customizations you can make so that it works with GIFs.

When setting up a Transfomer, you can pass in a custom [`AssetLoaderFactory`](https://github.com/androidx/media/blob/841b4fba9a56ac6f97b33e93e560bfd9dc5a338b/libraries/transformer/src/main/java/androidx/media3/transformer/AssetLoader.java#L54). Here you can pass in a factory that makes a custom `GIFAssetLoader` (that you write), which would work similarly to our [`ImageAssetLoader`](https://github.com/androidx/media/blob/main/libraries/transformer/src/main/java/androidx/media3/transformer/ImageAssetLoader.java). The main difference is that instead of [`queuing one bitmap`](https://github.com/androidx/media/blob/841b4fba9a56ac6f97b33e93e560bfd9dc5a338b/libraries/transformer/src/main/java/androidx/media3/transformer/ImageAssetLoader.java#L189) you would queue multiple (calling this method many times with different bitmaps, one for each frame of the GIF). When queuing a bitmap, you will also need to queue a [`TimeStampIterator`](https://github.com/androidx/media/blob/main/libraries/common/src/main/java/androidx/media3/common/util/TimestampIterator.java) with one value that is the time stamp of the current frame (the first frame will have a time stamp of 0, the second being the duration of the first frame etc.).

To extract the GIF into a sequence of bitmaps, you will probably need another library like [Glide](https://github.com/bumptech/glide)




Alternatively, you can convert GIFs into an mp4 file outside of Transformer then pass that mp4 into transformer as well.
