### ISSUE TITLE
Player drops RTP packet when sequence number resets from 65535 to 0

### ISSUE THREAD

**Issue by equeim** [androidx/media#738]
### Version

Media3 1.1.1

### More version details

When sequence number of RTP packets resets to zero, exoplayer drops packet with zero sequence number. This results in video/audio artifacts and following message in logs:
```
Received RTP packet with unexpected sequence number. Expected: 0; received: 1. Dropping packet.
```

My research concluded that packet is dropped in `RtpPacketReorderingQueue.offer()` method, although I'm not noot sure how to properly fix this.

### Devices that reproduce the issue

Pixel 4a 5G running Android 14.

### Reproducible in the demo app?

Yes

### Reproduction steps

I streamed Big Buck Bunny video (https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_1080p_h264.mov) using mediamtx and ffmpeg.
1. Launch mediamtx
2. Launch ffmpeg:
```
ffmpeg -loglevel verbose -re -i bbb_sunflower_1080p_30fps_normal.mp4 -map 0:0 -map 0:1 -c:v copy -c:a aac -f rtsp 'rtsp://0.0.0.0:8554/bbb'
```
3. Launch demo app and start rtsp playback using "rtsp://ip:8554/bbb"
Sequence number roll-over happens after about 4 minutes.

### Expected result

No artifacts or interruptions in video.

### Actual result

Video artifacts when sequence number is rolled over.

### Media

https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_1080p_h264.mov

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by equeim** [comment]
`calculateSequenceNumberShift` returns false, and [this](https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/exoplayer_rtsp/src/main/java/androidx/media3/exoplayer/rtsp/RtpPacketReorderingQueue.java#L108) condition evaluates to false. Packet is therefore not added to queue.

**Comment by microkatz** [comment]
I really appreciate your helping us in the debug process with your scenario. 

Interesting. The call to `calculateSequenceNumberShift` in that condition returns 0? In that case, because your dropped packet is 0, your packetSequenceNumber and lastDequeuedSequenceNumber would both be 0. 

A couple of things that would be great to know. 
* In your research, what is the last sequence number before rollover?
* Does the RTP packet with sequence number of 1 arrive before the 0 packet and cause a reset in the queue due to a leap greater than MAX_SEQUENCE_LEAP_ALLOWED?

If the latter bullet is true, then that would cause lastDequeuedSequenceNumber to be 0 even if the last polled packet wasn't one with sequence number 0. It seems like a very edge condition but the alternative for both packetSequenceNumber and lastDequeuedSequenceNumber to be the same number would be if the packets wrapped around before any other packet was dequeued by poll.

**Comment by microkatz** [comment]
@equeim. Just checking in. Were you able to run the debugging tests for the requested information?

**Comment by microkatz** [comment]
I'm closing this issue as there had not been a response to the queries. If you are still hitting this issue then please open a new one. Thank you!
