### ISSUE TITLE
How to write custom shaders for Transformer or Exoplayers

### ISSUE THREAD

**Issue by pawaom** [androidx/media#750]
How to write custom shaders for Transformer or Exoplayer 

We are trying to write a custom shaders  for greyscale for Exoplayer 

Like this

 ```
vec2 uv = fragCoord.xy / iResolution.xy;

    vec4 tex = texture(iChannel0, uv);
    vec3 greyScale = vec3(.5, .5, .5);
    fragColor = vec4( vec3(dot( tex.rgb, greyScale)), tex.a);
```

While the demo application provides example of greyscale  and few others for color manipulation, which are based on ` Grayscale transformation matrix using the BT.709 luminance coefficients  ` 
 [here](https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/effect/src/main/java/androidx/media3/effect/RgbFilter.java#L34C2-L34C3rl)
 
how do we work with GLSL openGL shaders

**Comment by dway123** [comment]
To use a custom shader in Transformer or ExoPlayer, you'll want to implement a GlEffect and corresponding GlShaderProgram, extending [BaseGlShaderProgram](https://github.com/androidx/media/blob/main/libraries/effect/src/main/java/androidx/media3/effect/BaseGlShaderProgram.java), where the GlShaderProgram must reference your custom shader.

A similar GlEffect, which uses a relatively-simple fragment shader and mostly-default behavior otherwise, is HslShaderProgram, where [HslAdjustment](https://github.com/androidx/media/blob/main/libraries/effect/src/main/java/androidx/media3/effect/HslAdjustment.java) is the GlEffect and [HslShaderProgram](https://github.com/androidx/media/blob/main/libraries/effect/src/main/java/androidx/media3/effect/HslShaderProgram.java) is the GlShaderProgram. You can see that HslShaderProgram extends BaseGlShaderProgram, which implements most of the common logic used in most GlShaderPrograms. From there, the GlShaderProgram references the custom shader, [fragment_shader_hsl_es2.glsl](https://github.com/androidx/media/blob/main/libraries/effect/src/main/assets/shaders/fragment_shader_hsl_es2.glsl).

That said, just a heads up that the sample glsl you provided seems to me like it might multiply RGB channels by .5 each, which would make them darker but not really "grayscale". Please let us know if there's any issues with our existing RgbFilter grayscale implementation, and we can consider improving it as needed

**Comment by pawaom** [comment]
`That said, just a heads up that the sample glsl you provided seems to me like it might multiply RGB channels by .5 each, which would make them darker but not really "grayscale". ` 

i am not saying the Grayscale you provided is wrong I am just  trying to implement  different shaders thanks for the Help
