### ISSUE TITLE
Buffering between periods (multi-period dash)

### ISSUE THREAD

**Issue by dgewe** [androidx/media#761]
Hi!

I have a issue with buffering (100-200ms) between periods when playing a multi-period DASH (DAI) stream.
This issue is also visible for me in this sample when using the ExoPlayer demo app:

media.exolist.json
```
      {
        "name": "Secure -> Clear -> Secure (cenc)",
        "uri": "https://storage.googleapis.com/exoplayer-test-media-1/widevine/tears_enc_clear_enc.mpd",
        "drm_scheme": "widevine",
        "drm_license_uri": "https://proxy.uat.widevine.com/proxy?video_id=2015_tears&provider=widevine_test",
        "drm_session_for_clear_content": true
      }
```

So far I have tested with these two devices when using ExoPlayer version 2.19.1 / 2.18.7 / 1.2.0-beta1:
- Samsung galaxy s20 -> No buffering
- STB -> Buffering (Not always, seems to be about a 50% chance)

**Part of the logs:**
`EventLogger: state [eventTime=107.79, mediaPos=734.02, window=0, period=1, BUFFERING]`
`EventLogger: state [eventTime=108.06, mediaPos=734.02, window=0, period=1, READY]`

**Logs:**
[test-logs.txt](https://github.com/androidx/media/files/13113659/test-logs.txt)

**Questions**
1. Could you please help me to understand what could be the cause of this buffering?
2. Do you have any suggestions on how I can improve this and mitigate the buffering? e.g if there are any specific parameters that I can use.

Thanks in advance.

**Comment by icbaker** [comment]
From the logs it looks like the `OMX.amlogic.avc.decoder.awesome2.secure` codec is logging a lot while you're seeing the buffering. I'm surprised it needs to flush - I wouldn't expect that instruction to have come directly from ExoPlayer (we feed a constant stream of buffers to the decoder over the transition point, to avoid needing to flush).

```
10-24 12:28:18.116  3937 29369 I OmxComponent: OMX.amlogic.avc.decoder.awesome2.secure: flush input
```

Based on the information you've provided I think this is likely related to the way the amlogic secure decoder implements switching between DRM sessions. By using `"drm_session_for_clear_content": true` you've ensured that ExoPlayer can use the same (secure) decoder for both the encrypted and clear content (which is good, since initializing a whole new decoder is slow(er)), but we still swap the DRM session associated with the decoder on each transition point (between the session that contains the keys for the protected content, and an 'empty' session for the clear content). This switch is implemented here:

https://github.com/androidx/media/blob/3f366109b7e5cbf7b7e5b46e8b923e167e9ae893/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/mediacodec/MediaCodecRenderer.java#L2217

This would explain why you only see the issue on the STB and not on the Samsung S20 (since I would expect the Samsung decoder has a different, less intrusive, implementation of this swapping logic).

----

I'm not sure we actually **need** to switch from the 'real' session to the placeholder one - and some quick experimentation on a Pixel 7a suggests that the `"Secure -> Clear -> Secure (cenc)"` sample still works even with that switch disabled (i.e. we just always keep the real session, even when playing the clear content in the middle). Would you be able to try this too by commenting out the `mediaCrypto.setMediaDrmSession(((FrameworkCryptoConfig) cryptoConfig).sessionId);` line in `MediaCodecRenderer` that I linked above? This is **not** a generally safe change, because it will break lots of DRM playback, but if it resolves your buffering issue then we can look into making a more in-depth change that avoids switching DRM session if we determine that we don't need to.

**Comment by dgewe** [comment]
@icbaker 
Thanks for the follow-up.

Removing that line did not help unfortunately, the buffering is the same as before.
I tested it on both release version 1.1.1 and 1.2.0 using the ExoPlayer demo sample.

```
EventLogger: state [eventTime=110.09, mediaPos=734.03, window=0, period=1, BUFFERING]
EventLogger: state [eventTime=110.36, mediaPos=734.03, window=0, period=1, READY]
```

The logs below are with your suggested change and I also included logs for when the buffering does not happen (50/50 chance)

Logs with buffering:
[output.txt](https://github.com/androidx/media/files/13187267/output.txt)

Logs without buffering:
[output-no-buffering.txt](https://github.com/androidx/media/files/13187360/output-no-buffering.txt)

**Comment by icbaker** [comment]
Thanks for the two files, it's helpful to compare them (i stripped the timestamps off the front before diffing). It seems this log line is present **many** times (200) in the buffering case (with incrementing values of `mEosCheckCount`), while it is much less common in the no-buffering case. The `state [eventTime=110.09, mediaPos=734.03, window=0, period=1, BUFFERING]` line shows up in the middle of this big logging block, so it seems they might be related.

```
AmlogicVideoDecoderAwesome: mEosCheckCount=129, mInPutFrameCount=329, mOutBufferNo=333, mMaxInputTimeStamp=1000754958333, mLastTimeStamp=1000733916666
```
----

These lines are also present in both:

```
OmxComponent: OMX.amlogic.avc.decoder.awesome2
AmlogicVideoDecoderAwesome: flushOutput:1244 >
```

But they are only followed by these extra lines in the buffering case:

```
AmlogicVideoDecoderAwesome: displayThread__flushOutput__fillBufferDone
chatty  : uid=1046(mediacodec) awesome2.secure identical 1 line
AmlogicVideoDecoderAwesome: displayThread__flushOutput__fillBufferDone
```

---

I'm afraid this is looking like a device-specific issue with the amlogic codecs in the device you're using, and investigating why their codec is causing rebuffers is out of scope for this issue tracker. I suggest you report this issue to the device manufacturer.

**Comment by changxiangzhong** [comment]
I'm running the same test with a broadcom 72180 based box, there's no BUFFERING state during the transition.

It seems like a few frame have been dropped/flush. I guess Broadcom's implementation is less intrusive.
```
352 10-27 14:23:02.946  3629 13002 W bomx_buffer_tracker: [OMX.bcm.vdec.avc.secure] PTS 0 not in tracker
353 10-27 14:23:02.946  3629 13002 W bomx_video_decoder: Unable to find tracker entry for pts 0
354 10-27 14:23:03.071  3629 13002 D bomx_video_decoder: id stats ib:1629 rb:1630 nrb:0
355 10-27 14:23:03.100  3629 13002 W bomx_video_decoder: Dropping outstanding frame 1901 still owned by client - flushing
356 10-27 14:23:03.101  3629 13002 W bomx_video_decoder: Dropping outstanding frame 1902 still owned by client - flushing
357 10-27 14:23:03.101  3629 13002 W bomx_video_decoder: Dropping outstanding frame 1903 still owned by client - flushing
358 10-27 14:23:03.101  3629 13002 W bomx_video_decoder: Dropping outstanding frame 1904 still owned by client - flushing
359 10-27 14:23:03.101  3629 13002 W bomx_video_decoder: Dropping outstanding frame 1905 still owned by client - flushing
360 10-27 14:23:03.101  3629 13002 W bomx_video_decoder: Dropping outstanding frame 1906 still owned by client - flushing
361 10-27 14:23:03.111  3629 13004 W bomx_video_decoder: Request to display buffer 1905 not found in list (duplicate?)
362 10-27 14:23:03.212  3455  3550 E NEXUS   : !!!Error BERR_UNKNOWN(0x9) at nexus/platforms/common/src/linuxuser.proxy/nexus_platform_os.c:1863
363 10-27 14:23:03.212  3455  3550 E RenderEngine: failed to create EGLImage: 0x3003
364 10-27 14:23:03.212  3455  3550 E RenderEngine: Failed to create image. size=1920x856 st=1920 usage=0x10006900 fmt=842094169
365 10-27 14:23:03.215 12887 12887 D EventLogger: renderedFirstFrame [eventTime=81.71, mediaPos=734.04, window=0, period=1, Surface(name=null)/@0x7897176]
366 10-27 14:23:03.318 12887 12887 D EventLogger: positionDiscontinuity [eventTime=81.81, mediaPos=734.12, window=0, period=1, reason=AUTO_TRANSITION, PositionInfo:old [mediaItem=0, period=    0, pos=734000], PositionInfo:new [mediaItem=0, period=1, pos=734000]]
367 10-27 14:23:03.332 12887 12887 D EventLogger: tracks [eventTime=81.82, mediaPos=734.15, window=0, period=1
368 10-27 14:23:03.332 12887 12887 D EventLogger:   group [
369 10-27 14:23:03.333 12887 12887 D EventLogger:     [X] Track:0, id=1, mimeType=video/avc, bitrate=769255, codecs=avc1.42c01e, res=320x142, fps=24.0, supported=YES
370 10-27 14:23:03.333 12887 12887 D EventLogger:     [X] Track:1, id=2, mimeType=video/avc, bitrate=1774254, codecs=avc1.4d401f, res=854x380, fps=24.0, supported=YES
371 10-27 14:23:03.333 12887 12887 D EventLogger:     [X] Track:2, id=3, mimeType=video/avc, bitrate=7203938, codecs=avc1.4d4028, res=1280x570, fps=24.0, supported=YES
372 10-27 14:23:03.334 12887 12887 D EventLogger:     [X] Track:3, id=4, mimeType=video/avc, bitrate=18316946, codecs=avc1.64002a, res=1920x856, fps=24.0, supported=YES
373 10-27 14:23:03.334 12887 12887 D EventLogger:   ]
374 10-27 14:23:03.334 12887 12887 D EventLogger:   group [
375 10-27 14:23:03.334 12887 12887 D EventLogger:     [X] Track:0, id=0, mimeType=audio/mp4a-latm, bitrate=131596, codecs=mp4a.40.2, channels=2, sample_rate=44100, language=en, supported=YE    S
376 10-27 14:23:03.335 12887 12887 D EventLogger:   ]
377 10-27 14:23:03.335 12887 12887 D EventLogger: ]
```


[broadcom-72180.log](https://github.com/androidx/media/files/13189005/broadcom-72180.log)

**Comment by dgewe** [comment]
@icbaker 

Thanks for the assistance, I will report this issue to the device manufacturer.

I will close this issue for now.
