### ISSUE TITLE
how to load full info media item

### ISSUE THREAD

**Issue by BoikoIlya** [androidx/media#778]
if i set media items list to controller that contains only mediaId how and when then load other info about track?

**Comment by 75Hassan1975** [comment]
الااا

**Comment by oceanjules** [comment]
Hi @BoikoIlya,

Could you please provide a code fragment with what you are trying to achieve and describe in more detail what information you are trying to load?

**Comment by icbaker** [comment]
You can override [`MediaSession.Callback.onAddMediaItems`](https://developer.android.com/reference/androidx/media3/session/MediaSession.Callback#onAddMediaItems(androidx.media3.session.MediaSession,androidx.media3.session.MediaSession.ControllerInfo,java.util.List%3Candroidx.media3.common.MediaItem%3E)) to handle resolve media items added from a controller.

See also the 'note' here: https://developer.android.com/guide/topics/media/session/mediasession#granting-control

**Comment by BoikoIlya** [comment]
> You can override [`MediaSession.Callback.onAddMediaItems`](https://developer.android.com/reference/androidx/media3/session/MediaSession.Callback#onAddMediaItems(androidx.media3.session.MediaSession,androidx.media3.session.MediaSession.ControllerInfo,java.util.List%3Candroidx.media3.common.MediaItem%3E)) to handle resolve media items added from a controller.
> 
> See also the 'note' here: https://developer.android.com/guide/topics/media/session/mediasession#granting-control

What you have wrote is that solution for perfomance increase as mentioned in other issues. So i set only media items with id to media conroller and then inflate all list in media session callback. Am i understandood right?

**Comment by icbaker** [comment]
If you are passing `MediaItem` instances without a URI from a controller then you will need to override `MediaSession.Callback.onAddMediaItems` in order to populate the URI and other information in order to make them playable. Whether you're choosing to do this for performance reasons or not is really orthogonal to this question. I'm going to close this as I think we've answered your question - please reply with more detail as requested above if not.
