### ISSUE TITLE
Flutter: When i set video effects it shows black screen preview instead of video preview.

### ISSUE THREAD

**Issue by YogendraAlgo** [androidx/media#779]
I am using Media3 ExoPlayer in flutter. I have just migrated code of plugin **[video_player_android](https://github.com/flutter/packages/blob/main/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java#L79)** to Media3 ExoPlayer. 

It is working perfectly after migration.
Problem: When i set video effects like below snippet it shows black screen instead of video preview.
I am not getting any error or exception in log so i am not able to debug cause.

 ExoPlayer exoPlayer = new ExoPlayer.Builder(context).build();
 ImmutableList.Builder<Effect> effects = new ImmutableList.Builder<>();
 effects.add(RgbFilter.createInvertedFilter());
 **exoPlayer.setVideoEffects(effects.build());**
    
<img width="292" alt="Screenshot 2023-10-31 at 12 24 02 AM" src="https://github.com/androidx/media/assets/147655821/6267a1bf-d09d-48f2-93d6-dc6e5d5585ad">

**Comment by claincly** [comment]
I'm afraid we have not tested the effect implementation against flutter. One possible cause is, flutter is using a type of rendering destination (like a `Surface`, or a `TextureView`) that the effect implementation does not support. We currently only support `SurfaceView` and `SurfaceHolder`. 

-----

I checked the plug in code and yes it is using `Surface` for video output which we don't support currently, and due to platform limitation we won't be able to support it.

https://github.com/flutter/packages/blob/b236d83c4a0ad839f7c2cc4ca7d643e80cecf431/packages/video_player/video_player_android/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java#L189-L190
