### ISSUE TITLE
How to fill MediaItem.localConfiguration that is removed when sent to the media session from a controller?

### ISSUE THREAD

**Issue by re-ovo** [androidx/media#8]
https://stackoverflow.com/questions/70096715/adding-mediaitem-when-using-the-media3-library-caused-an-error

**Comment by marcbaechinger** [comment]
Can you please file separate bugs for each question. This makes it possible to have issues titles that match the topic and then it is easy to find for other users that search for a similar question. I'm going to answer 1) as per title of the issue. Please file other issues for the other questions. Many thanks and sorry for any inconvenience.

**Comment by marcbaechinger** [comment]
The `localConfiguration` property is removed when it is sent from a `MediaController` to the `MediaSession`.

There is a `MediaItemFiller` that can be set to the  the [`MediaSession.Builder`](https://github.com/androidx/media/blob/main/libraries/session/src/main/java/androidx/media3/session/MediaSession.java#L297) or the [`MediaLibraryService.Builder`](https://github.com/androidx/media/blob/main/libraries/session/src/main/java/androidx/media3/session/MediaLibraryService.java#L414).

The setter is currently package-private on the [`MediaSession.Builder`](https://github.com/androidx/media/blob/main/libraries/session/src/main/java/androidx/media3/session/MediaSession.java#L297) which is a bug because of which I marked this issue as a such. You can set the `Mediaitem.mediaId` as an identifier to look up the data required to fill the rest of the media item properties:

In its most simplest form this would be something like below:

```
mediaSession =
        new MediaSession.Builder(/* context= */ this, player)
            .setMediaItemFiller(
                new MediaSession.MediaItemFiller() {
                  @Override
                  public MediaItem fillInLocalConfiguration(
                      MediaSession session,
                      MediaSession.ControllerInfo controller,
                      MediaItem mediaItem) {
                    return mediaItem
                        .buildUpon()
                        .setUri(lookupUriForMediaId(mediaItem.mediaId))
                        .build();
                  }
                })
            .build();
```

**Comment by re-ovo** [comment]
Sorry, modified my question

**Comment by neonwarge04** [comment]
How one will implement a `lookupUriForMediaId()`?

**Comment by marcbaechinger** [comment]
You are correct.

The snippet above is out of date as it was based on the `MediaItemFiller` that has been replaced by `Callback.onAddMediaItems()` that is returning a `Future` and hence is can be asynchronous.
