### ISSUE TITLE
AAC decoder overriding with component recommendation

### ISSUE THREAD

**Issue by FlogFly** [androidx/media#804]
10-13 16:14:18.934 6573 9560 D CCodec : client requested max input size 499, which is smaller than what component recommended (8192); overriding with component recommendation.
10-13 16:14:18.934 6573 9560 W CCodec : This behavior is subject to change. It is recommended that app developers double check whether the requested max input size is in reasonable range.

10-13 16:14:18.941 6573 9560 E Codec2-types: Failed to send buffer with BufferPool. Error: 4.
10-13 16:14:18.941 6573 9560 E Codec2-types: Invalid block data in C2ConstLinearBlock.
10-13 16:14:18.941 6573 9560 E Codec2-types: Invalid C2BufferData::linearBlocks. (Destination index = 0.)
10-13 16:14:18.941 6573 9560 E Codec2-types: Invalid C2Buffer::data.
10-13 16:14:18.941 6573 9560 E Codec2-types: Invalid C2FrameData::buffers[0].
10-13 16:14:18.941 6573 9560 E Codec2-types: Invalid C2Work::input.
10-13 16:14:18.941 6573 9560 E Codec2Client: queue – bad input.

**The max input size value set when creating the AAC decoder is too small, resulting in an input buffer exception**

But currently, I haven't seen any API related introduction on how to set this Max input size during the initialization of Exoplayer, because this issue doesn't always occur, even when playing the same audio, it's not necessary to do so.

thanks

**Comment by rohitjoins** [comment]
Hi @FlogFly,

> CCodec : client requested max input size 499, which is smaller than what component recommended (8192); overriding with component recommendation.

Based on the log you've pasted above it seems the codec is still assigning a buffer of 8K.

For us to investigate this further, can you please try and reproduce this issue on the demo app, and provide us with the bug report and media file with which this issue is reproduced. 

If you're unable to share [bug reports](https://developer.android.com/studio/debug/bug-report) or test content publicly, please send them to android-media-github@google.com with the subject `Issue #804`. Please also update this issue to indicate you've done this.
