### ISSUE TITLE
Advanced device-independent HDR tone mapping in ExoPlayer (as present e.g. in MPV)

### ISSUE THREAD

**Issue by jan-kleks** [androidx/media#826]
### [REQUIRED] Use case description
Some devices (especially projectors) need tone mapping for HDR content to look good. That is why, it might be worth to explore how ExoPlayer handles HDR videos on SDR displays, and how it could be improved.

### Proposed solution
There have been recently quite a few advancements in [the open-source video player MPV](https://github.com/mpv-player) when it comes to HDR tone mapping. It could be a good idea to look into MPV's implementation of this feature set, as such functionality would IMHO be greatly appreciated by the ExoPlayer users as well.

Apart from stock MPV, see also hdr-toys: https://github.com/natural-harmonia-gropius/hdr-toys

**Comment by dway123** [comment]
ExoPlayer doesn't currently use this, but maybe it could be helpful to use something like `ExoPlayer.setVideoEffects` to tone-map HDR to SDR on these devices. This can make use of OpenGL tone-mapping, which is relatively well-defined and should work at least down to API 29 ([code](https://github.com/androidx/media/blob/ec08db458e6cedcb79a42f10eaac7f8da7e7bcdb/libraries/effect/src/main/assets/shaders/fragment_shader_transformation_external_yuv_es3.glsl#L110-L209)). OpenGL tone-mapping might not have the ideal tone-mapping algorithms, but these algorithms can also be improved in the future.

**Comment by christosts** [comment]
@dway123 is tone mapping handled automatically when effects are enabled? Or does the app have to configure the effects in a specific way?

**Comment by dway123** [comment]
Oops thanks @christosts , `Transformer` applies tone-mapping automatically, if encoders don't support FEATURE_HdrEditing. For `ExoPlayer`, the output color is only automatically updated to [convert](https://github.com/androidx/media/blob/4f5038bc07c06910b74e53408b3866dfe8dbc43d/libraries/exoplayer/src/main/java/androidx/media3/exoplayer/video/CompositingVideoSinkProvider.java#L237-L246) HLG to PQ, but not HDR to SDR, because for ExoPlayer, HDR output is ~always supported as long as decoding is supported.

Therefore, the app does need to configure the effects in a specific way. To do this, you'll need to set up a custom `VideoFrameProcessor.Factory` that overrides the create method of `DefaultVideoFrameProcessor.Factory`'s `create()` method, to force `outputColorInfo` to be `ColorInfo.COLOR_TRANSFER_GAMMA_2_2`. This factory would be input into a custom `MediaCodecVideoRenderer` (other values could be default or passthrough values), which could be output in an override of `RenderersFactory#buildVideoRenderers()` in a `CustomRenderersFactory extends DefaultRenderersFactory`. This `RendererFactory` could then be input into `ExoPlayer` via `ExoPlayer.Builder.setRenderersFactory`

**Comment by christosts** [comment]
Recording some notes: As of API 31, we can ask MediaCodec to apply tone-mapping to decoded video frames. The API to do that is to include key [MediaFormat.KEY_COLOR_TRANSFER_REQUEST](https://developer.android.com/reference/android/media/MediaFormat#KEY_COLOR_TRANSFER_REQUEST) when configuring the codec, and after `MediaCodec.configure()` returns, we check the codec's input format to see if the requested tone mapping feature is supported.

We need to explore how to incorporate this on ExoPlayer's model of querying codec capabilities, since this feature requires the codec to be created and configured first in order to query whether tone mapping is supported.

**Comment by dway123** [comment]
This is possible, per the prior comment from Nov27.

I've created a github gist that better demonstrates how you could set up this code (based on the ExoPlayer demo), here: https://gist.github.com/dway123/934126c050482e9a2d3dcd43934b3730

**Comment by dway123** [comment]
This admittedly is a bit complicated to set up at the moment, because we didn't think this was too common of a codepath. If many folks use this, we may want to consider making a simpler codepath. One way to do this could be to implement a sort of color management in our VideoFrameProcessor pipeline (knowing input/output color combos), and allow tone-mapping to be an injectable GlEffect

**Comment by dway123** [comment]
Closing as fixed, as this is now possible, per the last two comments
