### ISSUE TITLE
Dismissing a paused notification leads to a new notification popping up on Android 28

### ISSUE THREAD

**Issue by tzugen** [androidx/media#83]
Dismissing a paused notification will call the STOP command.
In MediaNotificationManager the library is listening for EVENT_PLAYBACK_STATE_CHANGED events.
``stopForegroundServiceIfNeeded()``is correctly called, but stopForeground is called with false as an argument.
For some reason on Android 28, this will cause the Notification to pop up again immidiately after swiping it away.
The second time will then work, because the player is already stopped and there won't be another EVENT_PLAYBACK_STATE_CHANGED event.

**Comment by tzugen** [comment]
Actually the issue is slightly somewhere else.
stopForegroundServiceIfNeeded() actually works ok.
But in MediaNotificationManager, L167, there is another call to ``notificationManagerCompat.notify(id, notification)``immidiately afterwards.

**Comment by marcbaechinger** [comment]
Thanks for reporting!

When I try this with the `main` branch I can not repro this because this was fixed since the version you are using that is probably `1.0.0-alpha03` ([see L167 of the release branch that you are mentioning](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaNotificationManager.java#L167)). 

The `MediaNotificationManager` of the `main` branch does not post another notification because `canStartPlayback(...)` returns false [here](https://github.com/androidx/media/blob/main/libraries/session/src/main/java/androidx/media3/session/MediaNotificationManager.java#L165). The `stop` command is called and the player goes to `STATE_IDLE` which prevents posting another notification. 

You can verify this with the `main` branch or wait for the next release. I'm closing this issue, please re-open if I'm mistaken.
