### ISSUE TITLE
reason for `TextRenderer` class not open for extending

### ISSUE THREAD

**Issue by anilbeesetti** [androidx/media#841]
Hey guys, I was just wondering why `TextRenderer` class is marked as final why can't it be open for extending. Is there a reason for this? I wanted to add subtitle sync functionality to the TextRenderer by extending it but can't since it's marked as final class

**Comment by icbaker** [comment]
`TextRenderer` is not designed to be subclassed. This allows us to evolve its implementation with more flexibility, because it is easier to reason about how it cooperates with other components. See also Items 18 and 19 in Effective Java 3rd Edition: Item 18: 'Favor composition over inheritance' and 'Design and document for inheritance or else prohibit it'. We follow this rule for many components of ExoPlayer.

As a concrete example, we recently made significant changes to the functionality of `TextRenderer` in https://github.com/androidx/media/commit/6ad54d72adf50df7604094da4f62fe102a9c7707. This change would have been a lot harder to make while maintaining behavioural compatibility with all possible subclasses that might have been created by users of the library.

----

If you have specific functionality in `TextRenderer` that you would like to customize, please consider how it could be extracted as a well-defined compositional component which we could encapsulate in a new interface.
