### ISSUE TITLE
How to customize previous/ next icon on Android 13+

### ISSUE THREAD

**Issue by kevinguitar** [androidx/media#847]
![Untitled](https://github.com/androidx/media/assets/18852983/02c21b0f-bb96-4a94-b7f3-0aec7f64f8ec)

Hi media team 👋  I have a similar question to https://github.com/androidx/media/issues/751, but it was closed, so I decided to file one new issue.

I extended `DefaultMediaNotificationProvider` and override `getMediaButtons` to provide our icons for the actions, but the icons are applied only on Android 12 and before, the default skip previous/ forward icons are still displayed on Android 13+, I wonder what's the correct way to customize them? Thanks!

**Comment by Tolriq** [comment]
You can't if the media session expose that skip next / previous are available then the buttons are shown.

https://developer.android.com/media/implement/surfaces/mobile

The hack is to not expose the commands are available and publish custom commands.

**Comment by kevinguitar** [comment]
Thanks @Tolriq , I wonder if there is any plan to provide a proper way to override those icons?

**Comment by tianyif** [comment]
Hi @kevinguitar,

Before Android 13, the buttons are derived from the actions added with the notification. And starting from Android 13, the system derives media controls from `PlaybackState`, and the available commands (specifically to the "seek to prev" and "seek to next" buttons) - https://developer.android.com/media/implement/surfaces/mobile. So that's why overriding `DefaultMediaNotificationProvider.getMediaButtons` only works on Android 12 and below.

I think @Tolriq's answer is right here, to customize the icons for "seek to prev" and "seek to next" buttons, you may want to:

1. Do not expose the commands [COMMAND_SEEK_TO_PREVIOUS](https://developer.android.com/reference/androidx/media3/common/Player#COMMAND_SEEK_TO_PREVIOUS()), [COMMAND_SEEK_TO_PREVIOUS_MEDIA_ITEM](https://developer.android.com/reference/androidx/media3/common/Player#COMMAND_SEEK_TO_PREVIOUS_MEDIA_ITEM()), [COMMAND_SEEK_TO_NEXT](https://developer.android.com/reference/androidx/media3/common/Player#COMMAND_SEEK_TO_NEXT()) and [COMMAND_SEEK_TO_NEXT_MEDIA_ITEM](https://developer.android.com/reference/androidx/media3/common/Player#COMMAND_SEEK_TO_NEXT_MEDIA_ITEM()) as available, thus the system buttons of "seek to prev" and "seek to next" won't display. Please refer to the point 3 in this [comment](https://github.com/androidx/media/issues/216#issuecomment-1339701795) on how to hide these buttons with `ForwardingPlayer`.
2. Then you can set the custom buttons (with your customized icons) of the session and the available commands of controllers accordingly. You can refer to this [documentation](https://developer.android.com/media/implement/surfaces/mobile#config-action-buttons) for this step.
3. Also as stated in https://github.com/androidx/media/issues/751, with the above steps, the commands of "seek to prev" and "seek to next" sent from the bluetooth headset will be ignored  as we don't expose them as available. So from media3 1.2.0, [`MediaSession.onMediaButtonEvent`](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSession.java#L1470) was added, by overriding this method, the button events of "seek to prev" and "seek to next" can be handled by app [before](https://github.com/androidx/media/blob/release/libraries/session/src/main/java/androidx/media3/session/MediaSessionImpl.java#L1108) being handled by the library which ignores the unavailable commands.

Hope the above steps can help in your case!

**Comment by kevinguitar** [comment]
@tianyif Thank you for your reply 👍  I'm good to close the issue
