### ISSUE TITLE
Drm protected Video lagging when played on 2X speed

### ISSUE THREAD

**Issue by Kaushar-Adda247** [androidx/media#862]
### Version

Media3 1.2.0

### Devices that reproduce the issue

- Realme 6 | 11
- Redmi 6 Pro | 10
- Redmi 9 power

### Devices that do not reproduce the issue

Except redmi and realme devices, in all others it is playing.

### Reproducible in the demo app?

Yes

### Reproduction steps

Try to play any video from this playlist "Widevine DASH (MP4, H264)" at 2x speed.

### Expected result

It should play smoothly at 2x speed.

### Actual result

Video start lagging.

bugreport : [bugreport-RMX2001-RP1A.200720.011-2023-12-05-11-46-38.zip](https://github.com/androidx/media/files/13556538/bugreport-RMX2001-RP1A.200720.011-2023-12-05-11-46-38.zip)

### Media

We are facing the same lagging issue in you demo app also while playing **Widevine DASH (MP4, H264)** videos at 1.75x and 2x speed. So you can get the details from your demo app and try to reproduce.

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by tonihei** [comment]
Decrypting sample can be quite demanding on the playback pipeline and the player is generally more likely to run into performance issue, especially at higher playback speeds where everything has to work faster to keep up. 

ExoPlayer also has a different mode when interacting with the codec that helps to solve some of the known DRM decryption slowness. It's enabled by default on API >= 31 only due to some device-specific issues with the new mode we observed on lower API levels. You can try if it helps in your case by force enabling it with [forceEnableMediaCodecAsynchronousQueing](https://developer.android.com/reference/androidx/media3/exoplayer/DefaultRenderersFactory#forceEnableMediaCodecAsynchronousQueueing()). The method is on `DefaultRenderersFactory` that can be set in the `ExoPlayer.Builder`. 

Other than that I'm afraid there is not much we can do about it if the device is too slow to keep up with decrypting and decoding in real-time. If you have multiple resolutions available, you may want to restrict the resolution when playing at higher speeds for example to help with this issue?
