### ISSUE TITLE
Incorrect results when using SpeedChangeEffect

### ISSUE THREAD

**Issue by jordond** [androidx/media#865]
### Version

Media3 1.2.0

### Devices that reproduce the issue

- Z Fold 4
- Z Flip 5
- S21 Ultra
- Note 20 Ultra
- Pixel 7 Pro
- Pixel 3a
- Emulator

### Reproducible in the demo app?

[Yes, in my fork](https://github.com/jordond/media/tree/bug/speed-change)

### Reproduction steps

When using the `SpeedChangeEffect` if not all of your items in an `EditedMediaItemSequence` contain the effect. Then the resulting output will speed up the item, then freeze on the last frame for the original duration.

In order to reproduce first you need to clone my modified [repo](https://github.com/jordond/media/tree/bug/speed-change). I've changed the demo to do the following:

1. Create a `EditedMediaItemSequence` with two `EditedMediaItem`'s
2. The two items are the same EXCEPT the first one has a `SpeedChangeEffect(6f)`
3. Both items have `setRemoveAudio(true)`

Steps:

1. Clone [my fork](https://github.com/jordond/media/tree/bug/speed-change)
2. Select `demo-transformer` and run it on a device
4. Click the "Export" button
    - The demo is already setup to trigger the bug, don't change any of the configuration options.
5. View the output file

### Expected result

The first video should be rendered at 6x the speed, and the second video should be normal speed. Meaning the duration for the final output should be roughly 11.6 seconds.

### Actual result

Output is the original duration of 20 seconds. The first video is sped up 6x, then pauses on the last frame for the original duration.

### Media

https://github.com/androidx/media/assets/528792/394b3318-ba2a-4331-a378-ff004c6a282e

### Bug Report

- [X] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by droid-girl** [comment]
Thank you for reporting this, the team will investigate

**Comment by claincly** [comment]
Thanks for reporting this, it's definitely a limitation on our side. To provide more detail as to what happened:

The first media item is sped up 6x, so the output timestamps range from 0 to `1,662,772` us. However, as the second media's first output timestamp is `10,000,000` and last being `20,000,000`, that's why the resulting video is 20s. In fact the video is not frozen, you'll see the second video playing at the normal speed if you wait 10s.

A different problem arises if you speed up the second media item only. The first item outputs timestamp from 0 to `10_000_000`. However, as the second media's first frame's presentation time is `10,033,366`, it gets scaled down to `10,033,366 / 6 = 1,672,227` which is again incorrect.

We'll address this issue in the team, but not sure about the timeline just yet.

**Comment by tof-tof** [comment]
I'm currently working on a similar task and have found a way to resolve this issue. Have to discuss the with the team but I will assign this task to myself since it is within my remit

**Comment by tof-tof** [comment]
Forgot to add the automatic taging to the commit message, but d269b9375532c00ed205628e459cb81224a3c0cf on main branch submitted a fix to this issue. I've requested this commit to be included in the upcoming release.
