### ISSUE TITLE
apk file size bigger 100M+

### ISSUE THREAD

**Issue by 309152665** [androidx/media#885]
### Version

Media3 1.2.0

### More version details

when use media3 v1.2.0
![89096db41559aebe2664107f78530e8d](https://github.com/androidx/media/assets/7857673/4e13aa61-fd94-4547-8a9a-dc3ed0be5269)

when use media3 v1.1.1
<img width="1551" alt="image" src="https://github.com/androidx/media/assets/7857673/0c3c4279-0d7f-4b0f-b6be-daf3ebb63ce5">

### Devices that reproduce the issue

1

### Devices that do not reproduce the issue

1

### Reproducible in the demo app?

Yes

### Reproduction steps

1

### Expected result

1

### Actual result

1

### Media

1

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by icbaker** [comment]
There isn't enough information here to investigate.

I'm not aware of any font changes in the media3 library between 1.1.1 and 1.2.0.

The only font file I'm aware of in the library is [`roboto_medium_numbers.ttf`](https://github.com/androidx/media/blob/release/libraries/ui/src/main/res/font/roboto_medium_numbers.ttf) which has been [present since ExoPlayer 2.12.0](https://github.com/google/ExoPlayer/commit/a3bbcf3395094bc47ed931d2afe9fe765426da36).

Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem in a way that we can build locally.

The easiest way to do this is probably to fork this project and make changes in one of the demo apps, then link us to the fork.

Alternatively it could be an Android Studio project zipped up and sent to android-media-github@gmail.com  with the subject "Issue #1234". If emailing please also update this issue to indicate you’ve done this.

If this is not possible, please provide more information we can use to investigate.

**Comment by 309152665** [comment]
@icbaker 
<img width="1115" alt="image" src="https://github.com/androidx/media/assets/7857673/2021c8ea-b85f-4e9b-981a-170b4ffcdafd">
changes in the media3 library between 1.1.1 and 1.2.0.
run the project , the apk output
<img width="2419" alt="image" src="https://github.com/androidx/media/assets/7857673/4271367a-5f43-46bb-b99c-28a532c08e2f">

this is empty project , use version 1.2.0 , the apk file size 180M+ , and generate "fonts" folder , the folder size is  120M+ , 
change version 1.1.1 , the "fonts" folder is dismiss .

the demo:
[demos.zip](https://github.com/androidx/media/files/13667224/demos.zip)

**Comment by icbaker** [comment]
I built your example project with 1.1.1 and 1.2.0 and got an APK of ~56MB and ~185MB respectively. I then noticed these lines in your `build.gradle` file which mean your production APK has a dependency on our testing libraries, which transitively pulls in the whole of Robolectric:

```
api("androidx.media3:media3-test-utils:$media3_version")
api("androidx.media3:media3-test-utils-robolectric:$media3_version")
```

Removing these lines and re-building with 1.2.0 produces a 13.8MB APK.

The difference is likely due to us bumping the Robolectric version from 4.8.1 to 4.10.3: https://github.com/androidx/media/commit/fe667560d0f67b43a63f82adc15ec205beb49cad

You shouldn't need our test utilities in your app, especially the whole of Robolectric (and in fact its presence might confuse things because it might create duplicate classes on the classpath since it contains 'copies' of most/every Android framework class), so I suggest you remove these dependencies - and I think you'll see a significantly smaller APK.

----

I further reduced the size of the APK to 6.6MB by enabling R8 minification and resource shrinking. And reduced it to 2.6MB by only depending on `media3-exoplayer` - since your example project depends on **every** media3 module, which is adding needless bloat if you don't need the functionality of each module (e.g. you probably don't need **both** okhttp and cronet...?).

See also https://developer.android.com/guide/topics/media/exoplayer/shrinking
