### ISSUE TITLE
Notification COMMAND_SKIP_TO_PREVIOUS action need to click twice

### ISSUE THREAD

**Issue by XuQK** [androidx/media#89]
### Media3 Version

1.0.0-beta01

### Devices that reproduce the issue

Pixel5 running Android 12
Samsung galaxy note 10 5G running Android 11

### Reproducible in the demo app?

Yes

### Reproduction steps

1. run demo-session
2. click "Album Folder", "Youtube Audio Library Rock", "Awakening"
3. wait 5s
4. click prev button in notification

### Expected result

Skip to previous item.

### Actual result

Just skip to begin of current item.

### Media

Not applicable

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to dev.exoplayer@gmail.com after filing this issue.

**Comment by tonihei** [comment]
This is working as intended because the skip to previous action only seeks back to the beginning of the item once the playback position has passed `Player.getMaxSeekToPreviousPosition()`. See the documentation of `Player.seekToPrevious` for more details: https://exoplayer.dev/doc/reference/com/google/android/exoplayer2/Player.html#seekToPrevious()
