### ISSUE TITLE
CC is broken

### ISSUE THREAD

**Issue by Pradip-whiz** [androidx/media#896]
Hi Team,

I tried following live stream in media 1.2.0 and I can not see CC tracks. I can see CC tracks in old version of Exoplayer 2.8.4 and 2.16.0. I think something is changed after exoplayer 2.16.0 because I tried playing this live stream on all exoplayer versions after 2.16.0.

Live stream URL is https://live.field59.com/kwtv/kwtv1/playlist.m3u8

Please can you help me with this?. We have a lot of customers/users in USA, uses our apps to watch live news broadcast.

Thanks.

**Comment by Pradip-whiz** [comment]
@icbaker Any update for me? We have Android phone,Android TV and Fire TV apps; which are on hold to release to the respective stores, Because if we do not show CC then apps will get rejected as per US FCC (ADA) law.

Thanks.

**Comment by icbaker** [comment]
Subtitles show up on the stream you provided if I [disable chunkless preparation](https://developer.android.com/reference/androidx/media3/exoplayer/hls/HlsMediaSource.Factory#setAllowChunklessPreparation(boolean)). Chunkless preparation was enabled by default in 2.17.0 (see [release notes](https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6)). See [this blog post](https://medium.com/google-exoplayer/faster-hls-preparation-f6611aa15ea6) from when this feature was first introduced.

This is because the playlist doesn't declare that the stream contains captions using the `CLOSED-CAPTIONS` attribute, and therefore it's not possible to know the captions will be present just from reading the playlist.
