### ISSUE TITLE
Is there a synchronous way to check if the first frame has been rendered?

### ISSUE THREAD

**Issue by saket** [androidx/media#934]
I'm in a weird situation where my `Player.Listener` can get registered with some delay, causing my listener to miss its `onRenderedFirstFrame()` callback. Is it possible to synchronously read this state without setting a listener?

**Comment by marcbaechinger** [comment]
I don't think there is such an API, bnecause the `Listener` is that API and it's a bit unclear why this can't happen at the very beginning.

I would recommend adding the listener just after you've built the player.  This is the preferred way to get this information. 

If you use an `AnalyticsListener` and add it with `exoPlayer.addAnalyticsListener(listener)` instead of a `Player.Listener`.  The callback includes some additional information about the `EventTime`. So in case you add this listener at the very beginning, you can buffer these events and figure out afterwards whether first frame rendered has bee called for a given media period.

A similar think should work without the `EventTime` with `Player.Listener`.

**Comment by saket** [comment]
Got it, thanks for answering!
