### ISSUE TITLE
Notifying clients about custom state changes

### ISSUE THREAD

**Issue by derat** [androidx/media#969]
I'm updating a music app to use `androidx.media3:media3-session:1.2.0` for communication between its activities and service. Custom commands are working well for letting activities trigger functionality that's outside the scope of Media3, but I'm less sure of how to let the service notify activities about custom state changes. These include things like the following:

* initialization complete at startup
* progress notifications while syncing the library from the server
* changes to the total size of locally-cached data

I haven't found any obvious way to attach custom data to a `SimpleBasePlayer.State` (e.g. no `Builder.setExtras` or `Player.Listener.onExtrasChanged` methods) or report it via `MediaBrowser.Listener`.

I can think of various hacks that would probably work, like having the activity subscribe to a fake `parentId` via `MediaBrowser` and then having the service pass custom data via `LibraryParams.extras`. Before going that route, I figured it'd be good to ask if there's a recommended way of handling this that I missed. :-)

**Comment by marcbaechinger** [comment]
Technically there isn't another approach than using session extras or sending custom commands I think. 

The examples you list are not necessarily related to the player if I understand correctly. Progress notifications of syncing the library for instance are a library session feature rather than a player session feature, so I would not expect this inside a player implementation like `SimpleBasePlayer`.

From what you suggest, I think you can use the session extras. We will release 1.2.1 this week and it contains [this commit](https://github.com/androidx/media/commit/a063d137b4307348a140ec6a2b6d254db294395e#diff-5a11b03b6b2f566827d740c84d814d71c81b0a73588c3b71e73507c5d7c574fd) which improves the API of session extras if this is an approach that would work for you. This would allow you to update the session extras.

Alternatively you can define a custom command like `APP_STATE_UPDATE` or similar and then send a `Bundle` with the data describing that state to controllers. 

In both cases like session extras and a custom command, the controller can then take the `Bundle` and trigger logic on the controller side according to values having been changed.

**Comment by derat** [comment]
Thanks! `MediaSession.broadcastCustomCommand`/`sendCustomCommand` and `MediaController.Listener.onCustomCommand` are the pieces that I was missing. `setSessionExtras` looks like it'll work well here, too.

In a possibly-related vein, is there an efficient way to push updates about a single `MediaItem` from the service to clients? I currently display songs' download statuses (as percentages) in the playlist. I'm worried that storing the status as an extra somewhere in the `MediaItem` and then publishing it via updates to `SimpleBasePlayer.State` could cause performance problems. Is that concern unfounded, or would I be better off using some out-of-band mechanism to announce updates like this?

**Comment by marcbaechinger** [comment]
That pretty much relies on the app, the data produced/used by the app and the use cases you want to cover.

If you have a huge playlist and you want to update the downloaded percentage of a single item, then updating a single media item may cause the entire `Timeline` to be sent to the controller. Whether this actually is a noticeable performance issue probably depends on how large the playlist is and how often the percentage is updated. The most important criteria is whether the controller is running in the same or another process. 

If all controllers are running in the same process, there isn't be an issue at all. However, controllers connecting from System UI or Android Auto are running in another process. If you see perf issues, then you can try removing the command `COMMAND_GET_TIMELINE` for the [media notification controller](https://developer.android.com/media/media3/session/background-playback#media-notification-controller). If this command is removed, the timeline isn't synced to the queue of the platform session anymore. While this doesn't make a difference for System UI that produces the notification without using the queue, Android Auto users may not be able to access the items in the queue for selection. 

So if you still have concerns after reading the above or you have a large playlist and a Media3 controller that accesses the timeline is running in a different process than your service, then an out-of-band mechanism would probably make sense. You can then send only the float/double along with the mediaId over the binder and when received you can merge this into the existing data structure your controller is maintaining.

**Comment by derat** [comment]
Thank you for the thorough reply. I'd like to continue exposing the playlist to Android Auto, so I'll plan to use a different approach to pass download statuses to my controller.
