### ISSUE TITLE
ExoPlayer getCurrentLiveOffset() support for Shoutcast live streams

### ISSUE THREAD

**Issue by algrid** [androidx/media#980]
I'm using `getCurrentLiveOffset()` to get the offset of the current playback position vs the live stream "edge".
It works fine for HLS streams, but for audio Shoutcast/Icecast streams it returns `C.TIME_UNSET`.

Should it work currently or are there any plans to add support for it? That would be quite handy.

If it helps, I was testing the audio-only stream for "Geek News Central" podcast.
Stream URL (afaik it's only live at a specific time once or twice a week): https://altair.streamerr.co/stream/podcastradio 

HTTP headers: 
```
HTTP/1.1 200 OK
< Server: nginx/1.22.1
< Date: Mon, 15 Jan 2024 23:19:18 GMT
< Content-Type: audio/aacp; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< icy-notice1: <BR>This stream requires <a href="http://www.winamp.com">Winamp</a><BR>
< icy-notice2: Shoutcast DNAS/posix(linux x64) v2.6.1.777<BR>
< Accept-Ranges: none
< Access-Control-Allow-Origin: *
< Cache-Control: no-cache,no-store,must-revalidate,max-age=0
< icy-name: Stream
< icy-genre: Misc
< icy-br: 128
< icy-sr: 44100
< icy-url: http://www.shoutcast.com
< icy-pub: 1
< X-Clacks-Overhead: GNU Terry Pratchett
```

**Comment by marcbaechinger** [comment]
There is [`Player.getBufferedPosition()`](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/Player.java#L3072) and [`Player.getTotalBufferedDuration`](https://github.com/androidx/media/blob/release/libraries/common/src/main/java/androidx/media3/common/Player.java#L3072).

> how far behind the current playback position is

I don't think the player knows about the current playback position on the server. When the player starts playing such a progressive live stream it just starts playing where the stream starts which is determined by state on the server. When the player then is paused, it continues buffering up to the duration that is configured to be buffered by `LoadControl` (for instance 50 secs by default).

If playback is paused longer than the given buffer duration and then resumed, I'd think some data is lost because the stream would just deliver data at the position the server has advanced to in the meanwhile. Lets say we pause 10 minutes, then 50 secs are buffered. When we resume after 10 minutes the stream on the server side has advanced and the 9 minutes and 10 seconds is not available anymore for download.

**Comment by algrid** [comment]
@marcbaechinger thank you for the information!  👍 
I see that indeed it's not quite possible to make `getCurrentLiveOffset()` work reasonably well/precise in this case.
And for my use case (kind of best effort) `getBufferedPosition()` or `getTotalBufferedDuration()` will do exactly what I need, I didn't know that those calls exist.

**Comment by marcbaechinger** [comment]
Glad this helped! Thanks for confirming!

I'm closing this issue!
